### PR TITLE
#3673 Added color Independent snack function

### LINKED ISSUE #3673: Snackbar action color
**Describe the bug**

The action text color in Snackbar is not consistent(for dark theme).

**Expected behavior**

It should be black.

**Steps to reproduce the behavior:**
1. Open a ZIM

**Screenshots**

photo_6140912444634152213_y

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT
- OS version : 13

**Logs**

### PR DESCRIPTION
**Pull request by Sagar0-0**
Fixes #3673

**Screenshots** 
Other places:
photo_6145368357239634245_y
photo_6145368357239634246_y
Bookmark:
photo_6145368357239634248_y
photo_6145368357239634247_y

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt [hunk 1]
```diff
@@ -25,6 +25,20 @@ import androidx.annotation.ColorInt
 import com.google.android.material.snackbar.BaseTransientBottomBar
 import com.google.android.material.snackbar.Snackbar
 
+@SuppressLint("ShowToast")
+fun View.snack(
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:29]: @Sagar0-0 I understand what you want to do, for that, we should not change this function, we should write code that can be reuseable. we can define the `actionTextColor` as null, and remove the `actionTextColor` parameter from the `CoreReaderFragment` and then it will do the same what you want to achieve. Here is the code snippet you can follow.


```kotlin
@SuppressLint("ShowToast")
fun View.snack(
  stringId: Int,
  anchor: View? = null,
  actionStringId: Int? = null,
  actionClick: (() -> Unit)? = null,
  @ColorInt actionTextColor: Int? = null
) {
  Snackbar.make(
    this, stringId, Snackbar.LENGTH_LONG
  ).apply {
    actionStringId?.let { setAction(it) { actionClick?.invoke() } }
    actionTextColor?.let(::setActionTextColor)
    anchor?.let {
      anchorView = anchor
      addCallback(object : BaseTransientBottomBar.BaseCallback<Snackbar>() {
        override fun onDismissed(transientBottomBar: Snackbar?, event: Int) {
          transientBottomBar?.anchorView = null
        }
      })
    }
  }.show()
}

@SuppressLint("ShowToast")
fun View.snack(
  message: String,
  anchor: View,
  actionStringId: Int? = null,
  actionClick: (() -> Unit)? = null,
  @ColorInt actionTextColor: Int? = null
) {
  Snackbar.make(
    this, message, Snackbar.LENGTH_LONG
  ).apply {
    actionStringId?.let { setAction(it) { actionClick?.invoke() } }
    actionTextColor?.let(::setActionTextColor)
    anchorView = anchor
    addCallback(object : BaseTransientBottomBar.BaseCallback<Snackbar>() {
      override fun onDismissed(transientBottomBar: Snackbar?, event: Int) {
        transientBottomBar?.anchorView = null
      }
    })
  }.show()
}

fun View.snack(stringId: Int) {
  snack(stringId, null, null)
}

```

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt (hunk 1 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:29]: I agree,  this way is more accurate. But, what is the requirement of the last function with just one param, I saw it is no different from the first one?

Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:29]: The same goes for the second snack function with anchor parameter, I think having only one snack function (the first one) covers all the use cases we are having.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:29]: @Sagar0-0 Thanks for pointing out this, it was introduced a long time ago and definitely that time it has some purpose, but now it is redundant we can remove it.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt]: > The same goes for the second snack function with anchor parameter, I think having only one snack function (the first one) covers all the use cases we are having.

@Sagar0-0 The first two snack bars have a difference. See the first parameter of both snack bars. The first one takes the `stringId`, and the second one takes the `string`. We did this to maintain the separate concern.

In my last comment I was talking about the below function it is now redundant.

```kotlin
fun View.snack(stringId: Int) {
  snack(stringId, null, null)
}
```

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt]: > The same goes for the second snack function with anchor parameter, I think having only one snack function (the first one) covers all the use cases we are having.

@Sagar0-0 The first two snack bars have a difference. See the first parameter of both snack bars. The first one takes the stringId, and the second one takes the string. We did this to maintain the separate concern.

In my last comment I was talking about the below function it is now redundant.

```kotlin
fun View.snack(stringId: Int) {
  snack(stringId, null, null)
}
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt [hunk 2]
```diff
@@ -48,29 +48,3 @@ fun View.snack(
     }
   }.show()
 }
-
-@SuppressLint("ShowToast")
-fun View.snack(
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:53]: Please check its usage before removing anything. Don't remove this function we are using this to show the message see https://github.com/kiwix/kiwix-android/blob/3f19f55b99c83152d9f6be2d910894c9409c8637/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt#L539

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
See project is not even compiling https://github.com/kiwix/kiwix-android/actions/runs/7581453829/job/20649079672?pr=3676#step:4:688

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt (hunk 2 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:53]: Sorry, for the inconvenience. I am fixing it rn.

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Please fix the Code formatting and detekt issues.

```kotlin
> Task :core:ktlintMainSourceSetCheck FAILED
/home/runner/work/kiwix-android/kiwix-android/core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:1:1 File must end with a newline (\n)
/home/runner/work/kiwix-android/kiwix-android/core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:22:1 Unused import
```

**Review by MohitMaliFtechiz — APPROVED** [review]
@Sagar0-0 Thanks :tada: :tada: .
