### PR TITLE
FIX: 2469 KiwixPrefsFragment is leaking

### LINKED ISSUE #2469: KiwixPrefsFragment is leaking
**Describe the bug**
KiwixPrefsFrament is leaking if we open Settings.

**Expected behavior**
There shouldn't be this leak on KiwixPresFragment.

**Steps to reproduce the behavior:**
1. Open Application
2. Go to the Settings
3. Go back to home Fragment

**Screenshots**
Screenshot 2020-11-02 at 4 32 12 PM

**Environment**
- Version of Kiwix Android : develop
- Device: Google Pixel
- OS version: 10

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2469

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt [hunk 1]
```diff
@@ -52,4 +53,12 @@ abstract class CoreSettingsFragment : BaseFragment() {
     activity.supportActionBar!!.setHomeButtonEnabled(true)
     activity.supportActionBar!!.setDisplayHomeAsUpEnabled(true)
   }
+
+  override fun onDestroyView() {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt:57]: this seems like using a hammer instead of a tweezers. Can you post the full leak, I would imagine some listeners just need to be cleared in CorePrefsFragment's onDestroyView

Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt:57]: [Here](https://github.com/kiwix/kiwix-android/issues/2469#issue-734409801) I post a screenshot about this.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt:57]: I have seen that but it doesn't look like the whole story, is there any more?

**Comment by macgills** [comment]
Also in future please make sure you are doing your work off of the most up to date develop branch, this is 137 commits behind develop giving us this strange coverage report. You don't even need to be on a fork anymore and can work directly on the main repo as you are a contributor

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt (hunk 1 above)
Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt:57]: Leakcanary is showing this.
<details>
<summary>Logs</summary>

```
D/ColorViewRootUtil: nav gesture mode swipeFromBottom ignore true downX 1075 downY 1459 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 3 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=1075.0, y[0]=1459.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=379441393, downTime=379441393, deviceId=4, source=0x1002, displayId=0 } rotation 0
I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
D/LeakCanary: Watching instance of androidx.coordinatorlayout.widget.CoordinatorLayout (org.kiwix.kiwixmobile.settings.KiwixSettingsFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 1a1ce802-0030-473d-a566-5f87ff580104
    Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key 097790c8-b474-49d3-8759-0f70f2619956
    Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key 8557be10-f008-4c77-85b3-0a9a3841eaa4
D/LeakCanary: Watching instance of org.kiwix.kiwixmobile.settings.KiwixSettingsFragment (org.kiwix.kiwixmobile.settings.KiwixSettingsFragment received Fragment#onDestroy() callback) with key 807dd1f1-73d3-4d78-a25a-637752534c8f
I/Choreographer: Skipped 3 frames!  The application may be doing too much work on its main thread.
I/Choreographer: Skipped 11 frames!  The application may be doing too much work on its main thread.
W/RxCachedThreadS: type=1400 audit(0.0:106190): avc: denied { getattr } for path="/mnt/product" dev="tmpfs" ino=15551 scontext=u:r:untrusted_app:s0:c22,c257,c512,c768 tcontext=u:object_r:mnt_product_file:s0 tclass=dir permissive=0
E/kiwix: Attempting to create reader with: /storage/emulated/0/Android/data/org.kiwix.kiwixmobile/files/Kiwix/energypedia_en_all_nopic_2020-09.zim
D/ZimFileReader: reading  M/Tags(mime: text/plain, size: 61) finished.
E/kiwix: Attempting to create reader with: /storage/9016-4EF8/Android/data/org.kiwix.kiwixcustomcustomexample/files/Kiwix/wikipedia_fr_test.zim
D/ZimFileReader: reading  M/Tags(mime: text/plain, size: 55) finished.
D/LeakCanary: Scheduling check for retained objects because found new object retained
D/LeakCanary: Ignoring request to check for retained objects (found new object retained), already scheduled in 0ms
I/wix.kiwixmobil: Explicit concurrent copying GC freed 14429(554KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 24MB/49MB, paused 80us total 183.231ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
I/wix.kiwixmobil: Explicit concurrent copying GC freed 3469(240KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 24MB/49MB, paused 109us total 205.627ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
I/wix.kiwixmobil: Explicit concurrent copying GC freed 282(144KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 24MB/49MB, paused 114us total 218.912ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
I/wix.kiwixmobil: Explicit concurrent copying GC freed 329(143KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 24MB/49MB, paused 96us total 213.792ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
I/wix.kiwixmobil: Explicit concurrent copying GC freed 311(159KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 24MB/49MB, paused 108us total 193.784ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
I/wix.kiwixmobil: Explicit concurrent copying GC freed 279(143KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 24MB/49MB, paused 96us total 162.249ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
D/LibGlobalFetchLib: PriorityIterator backoffTime increased to 4 minute(s)
I/wix.kiwixmobil: Explicit concurrent copying GC freed 382(173KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 24MB/49MB, paused 255us total 214.711ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
I/wix.kiwixmobil: Explicit concurrent copying GC freed 413(163KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 24MB/49MB, paused 96us total 214.778ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
I/wix.kiwixmobil: Explicit concurrent copying GC freed 316(159KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 24MB/49MB, paused 94us total 189.589ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
I/wix.kiwixmobil: Explicit concurrent copying GC freed 329(143KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 24MB/49MB, paused 97us total 222.500ms
D/LeakCanary: Rescheduling check for retained objects in 2000ms because found only 2 retained objects (< 5 while app visible)
```

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt:57]: that doesn't give me any information, usually they also print the report to logs. I'll investigate on monday when I am back on the project

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt:57]:
```
2020-11-16 08:38:47.803 D/LeakCanary: Analysis in progress, working on: REPORTING_HEAP_ANALYSIS
2020-11-16 08:38:47.836 D/LeakCanary: ====================================
2020-11-16 08:38:47.836 D/LeakCanary: HEAP ANALYSIS RESULT
2020-11-16 08:38:47.836 D/LeakCanary: ====================================
2020-11-16 08:38:47.836 D/LeakCanary: 1 APPLICATION LEAKS
2020-11-16 08:38:47.836 D/LeakCanary: References underlined with "~~~" are likely causes.
2020-11-16 08:38:47.836 D/LeakCanary: Learn more at https://squ.re/leaks.
2020-11-16 08:38:47.836 D/LeakCanary: 4300 bytes retained by leaking objects
2020-11-16 08:38:47.836 D/LeakCanary: Signature: b09159442fbbf2e7e3f16fcf5f685a1fe13f65ba
2020-11-16 08:38:47.836 D/LeakCanary: ┬───
2020-11-16 08:38:47.836 D/LeakCanary: │ GC Root: Input or output parameters in native code
2020-11-16 08:38:47.836 D/LeakCanary: │
2020-11-16 08:38:47.836 D/LeakCanary: ├─ okio.AsyncTimeout class
2020-11-16 08:38:47.836 D/LeakCanary: │    Leaking: NO (PathClassLoader↓ is not leaking and a class is never leaking)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ static AsyncTimeout.$class$classLoader
2020-11-16 08:38:47.837 D/LeakCanary: ├─ dalvik.system.PathClassLoader instance
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (InternalLeakCanary↓ is not leaking and A ClassLoader is never leaking)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ PathClassLoader.runtimeInternalObjects
2020-11-16 08:38:47.837 D/LeakCanary: ├─ java.lang.Object[] array
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (InternalLeakCanary↓ is not leaking)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ Object[].[1052]
2020-11-16 08:38:47.837 D/LeakCanary: ├─ leakcanary.internal.InternalLeakCanary class
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (KiwixMainActivity↓ is not leaking and a class is never leaking)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ static InternalLeakCanary.resumedActivity
2020-11-16 08:38:47.837 D/LeakCanary: ├─ org.kiwix.kiwixmobile.main.KiwixMainActivity instance
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (KiwixPrefsFragment↓ is not leaking and Activity#mDestroyed is false)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ KiwixMainActivity.mOnBackPressedDispatcher
2020-11-16 08:38:47.837 D/LeakCanary: ├─ androidx.activity.OnBackPressedDispatcher instance
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (KiwixPrefsFragment↓ is not leaking)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ OnBackPressedDispatcher.mOnBackPressedCallbacks
2020-11-16 08:38:47.837 D/LeakCanary: ├─ java.util.ArrayDeque instance
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (KiwixPrefsFragment↓ is not leaking)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ ArrayDeque.elements
2020-11-16 08:38:47.837 D/LeakCanary: ├─ java.lang.Object[] array
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (KiwixPrefsFragment↓ is not leaking)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ Object[].[3]
2020-11-16 08:38:47.837 D/LeakCanary: ├─ androidx.fragment.app.FragmentManager$1 instance
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (KiwixPrefsFragment↓ is not leaking)
2020-11-16 08:38:47.837 D/LeakCanary: │    Anonymous subclass of androidx.activity.OnBackPressedCallback
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ FragmentManager$1.this$0
2020-11-16 08:38:47.837 D/LeakCanary: ├─ androidx.fragment.app.FragmentManagerImpl instance
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (KiwixPrefsFragment↓ is not leaking)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ FragmentManagerImpl.mParent
2020-11-16 08:38:47.837 D/LeakCanary: ├─ org.kiwix.kiwixmobile.settings.KiwixPrefsFragment instance
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: NO (Fragment#mFragmentManager is not null)
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ KiwixPrefsFragment.mContainer
2020-11-16 08:38:47.837 D/LeakCanary: │                         ~~~~~~~~~~
2020-11-16 08:38:47.837 D/LeakCanary: ├─ android.widget.FrameLayout instance
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: YES (View detached and has parent)
2020-11-16 08:38:47.837 D/LeakCanary: │    mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
2020-11-16 08:38:47.837 D/LeakCanary: │    View#mParent is set
2020-11-16 08:38:47.837 D/LeakCanary: │    View#mAttachInfo is null (view detached)
2020-11-16 08:38:47.837 D/LeakCanary: │    View.mID = R.id.content_frame
2020-11-16 08:38:47.837 D/LeakCanary: │    View.mWindowAttachCount = 1
2020-11-16 08:38:47.837 D/LeakCanary: │    ↓ FrameLayout.mParent
2020-11-16 08:38:47.837 D/LeakCanary: ├─ android.widget.LinearLayout instance
2020-11-16 08:38:47.837 D/LeakCanary: │    Leaking: YES (FrameLayout↑ is leaking and View detached and has parent)
2020-11-16 08:38:47.837 D/LeakCanary: │    mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
2020-11-16 08:38:47.837 D/LeakCanary: │    View#mParent is set
2020-11-16 08:38:47.837 D/LeakCanary: │    View#mAttachInfo is null (view detached)
2020-11-16 08:38:47.837 D/LeakCanary: │    View.mWindowAttachCount = 1
2020-11-16 08:38:47.838 D/LeakCanary: │    ↓ LinearLayout.mParent
2020-11-16 08:38:47.838 D/LeakCanary: ╰→ androidx.coordinatorlayout.widget.CoordinatorLayout instance
2020-11-16 08:38:47.838 D/LeakCanary: ​     Leaking: YES (ObjectWatcher was watching this because org.kiwix.kiwixmobile.settings.KiwixSettingsFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks))
2020-11-16 08:38:47.838 D/LeakCanary: ​     key = c747c639-4f9b-4664-9ddf-29b414e841c9
2020-11-16 08:38:47.838 D/LeakCanary: ​     watchDurationMillis = 8474
2020-11-16 08:38:47.838 D/LeakCanary: ​     retainedDurationMillis = 3471
2020-11-16 08:38:47.838 D/LeakCanary: ​     mContext instance of org.kiwix.kiwixmobile.main.KiwixMainActivity with mDestroyed = false
2020-11-16 08:38:47.838 D/LeakCanary: ​     View#mParent is null
2020-11-16 08:38:47.838 D/LeakCanary: ​     View#mAttachInfo is null (view detached)
2020-11-16 08:38:47.838 D/LeakCanary: ​     View.mWindowAttachCount = 1
2020-11-16 08:38:47.838 D/LeakCanary: ====================================
2020-11-16 08:38:47.838 D/LeakCanary: 0 LIBRARY LEAKS
2020-11-16 08:38:47.838 D/LeakCanary: A Library Leak is a leak caused by a known bug in 3rd party code that you do not have control over.
2020-11-16 08:38:47.838 D/LeakCanary: See https://square.github.io/leakcanary/fundamentals-how-leakcanary-works/#4-categorizing-leaks
2020-11-16 08:38:47.838 D/LeakCanary: ====================================
2020-11-16 08:38:47.838 D/LeakCanary: METADATA
2020-11-16 08:38:47.838 D/LeakCanary: Please include this in bug reports and Stack Overflow questions.
2020-11-16 08:38:47.838 D/LeakCanary: Build.VERSION.SDK_INT: 27
2020-11-16 08:38:47.838 D/LeakCanary: Build.MANUFACTURER: LGE
2020-11-16 08:38:47.838 D/LeakCanary: LeakCanary version: 2.4
2020-11-16 08:38:47.838 D/LeakCanary: App process name: org.kiwix.kiwixmobile
2020-11-16 08:38:47.838 D/LeakCanary: Analysis duration: 54913 ms
2020-11-16 08:38:47.838 D/LeakCanary: Heap dump file path: /data/user/0/org.kiwix.kiwixmobile/files/leakcanary/2020-11-16_08-37-49_878.hprof
2020-11-16 08:38:47.838 D/LeakCanary: Heap dump timestamp: 1605515927802
2020-11-16 08:38:47.838 D/LeakCanary: ====================================
```

So it is quite odd that we add a fragment to add a fragment, I think we should fix that first, it is a relic of how `CoreSettingsFragment` used to be an activity. That should clean up this situation

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java [hunk 2]
```diff
@@ -84,13 +92,23 @@ public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
       .build()
       .inject(this);
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java:93]: delete the injection here, it wasn't using the cached component anyway

Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java:93]: @macgills I tried to remove this line but it crashes.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java:93]: Post the crash

Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java:93]: <description>
<summary>
Logs
</summary>

```
2020-11-17 15:38:32.230 25989-25989/org.kiwix.kiwixmobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 25989
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.kiwix.kiwixmobile.core.utils.SharedPreferenceUtil.getPrefStorage()' on a null object reference
        at org.kiwix.kiwixmobile.settings.KiwixPrefsFragment.setStorage(KiwixPrefsFragment.kt:43)
        at org.kiwix.kiwixmobile.core.settings.CorePrefsFragment.onCreatePreferences(CorePrefsFragment.java:96)
        at org.kiwix.kiwixmobile.settings.KiwixPrefsFragment.onCreatePreferences(KiwixPrefsFragment.kt:37)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2685)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
```
</description>

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/BasePrefsFragment.kt [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+import android.os.Bundle
+import androidx.fragment.app.Fragment
+import androidx.preference.PreferenceFragmentCompat
+import org.kiwix.kiwixmobile.core.base.BaseActivity
+import org.kiwix.kiwixmobile.core.base.BaseFragment
+
+abstract class BasePrefsFragment : PreferenceFragmentCompat() {
+
+  override fun onCreatePreferences(savedInstanceState: Bundle?, rootKey: String?) {
+    inject(activity as BaseActivity)
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/BasePrefsFragment.kt:32]: do this in onCreate instead to resolve that crash maybe

**Review by macgills — APPROVED** [review]
