### PR TITLE
Change the method to get data directory path in Android 10+

### LINKED ISSUE #2592: Unable to open ZIM files that Kiwix for Android did not download.
**Describe the bug**
BLUF: It seems like it should be possible for Kiwix for Android to open .zim files that it did not download.  It can't.

Background: I live in a very bandwidth contstrained location; it is feasible for me to use Kiwix to download smaller .zim files (e.g., InstallGentoo Wiki - 2019-09-18 - 9MB) but not to download larger ones (wikipedia_en_all_maxi_2020-12.zim - 73.9 GB).  So, my workaround is to take a flash drive to work, plug it into my machine there, and have it download .zim files with wget.  Then the next time I'm in the area I pick up the flash drive, plug it into my laptop, plug my phone or tablet's microSD card into my laptop, and copy the .zim file over.

The thing is, this doesn't actually work.  Only files that Kiwix for Android has downloaded are in the Kiwix Library.

If I use my file manager to open the .zim file (Open With -> Kiwix) the Kiwix app open and very briefly the "loading" indicator shows at the top, but the .zim file is not added to the Library.

On all of my devices I have Kiwix configured to use my phone's microSD card as its source of truth (sandwich menu -> Settings -> Storage -> External).

**Expected behavior**
If a new .zim file is in the storage location Kiwix is configured for: By opening the Kiwix app's Library screen the new .zim file should be present and I should be able to open and read through or search it just like .zim files that Kiwix downloaded on its own.

If a new .zim file has been copied onto the storage location Kiwix is configured for: I should be able to open the file's "do stuf" menu, tap on "Open with", select Kiwix, and Kiwix should add that file to its Library screen and let me read through or search it.

**Steps to reproduce the behavior:**
1. Download a .zim file, but not with Kiwix.  Use a web browser, or copy a .zim file onto the Android device's storage somehow (say, by copying the file with a file manager)
2. Open Kiwix
3. Tap the Library icon
4. The .zim file is not present

Alternatively, trying to open the file with "Open with"
1. Download a .zim file, but not with Kiwix.  Use a web browser, or copy a .zim file onto the Android device's storage somehow (say, by copying the file with a file manager)
2. Open the Android device's file manager.
3. Navigate to where the new .zim file is stored (on my devices, that is my phone's microSD card -> Android -> Data -> org.kiwix.kiwixmobile -> Files -> Kiwix)
4. Tap on the "do stuff with this file" menu icon for the file (for me it's a kebab menu icon)
5. "Open with"
6. Select Kiwix
7. The .zim fie does not open.  The .zim file is also not in the Library.

**Screenshots**
Can supply screenshots upon request.

**Environment**
- Version of Kiwix Android : v3.4.3 build 623403 from the Google Play store on both devices
- Device : 
    - Samsung SM-G965U phone
    - Samsung SM-T290 tablet
- OS version : Both are running Android 10, unmodified

**Logs**
* Phone: https://drive.google.com/file/d/1umINHzLqnYJwWGFbjT-P2DH1BmehB48J/view?usp=sharing
* Tablet: https://drive.google.com/file/d/1YaJRE4gjD64iSNtzqSflIk_TVdSR8ciC/view?usp=sharing

### LINKED ISSUE #2787: ZIM files copied into Kiwix storage dir never get listed in the app
Also mentioned here: #2676

Due to Kiwix instable download mechanic, (which I won't get into here), I eventually downloaded my ZIM files on desktop and then moved them to my phone, into the same dir where other ZIM files already exist and newly downloaded ones appear. 
But ZIM files added this way never show up in the app. I tried restarting the app and the phone. 
Placing the ZIM files into external or internal storage makes no difference.

Expected behavior would be that ZIM files added to Kiwix storage get listed in the app.

- Version of Kiwix Android :  current official and current beta
- Device : Samsung Galaxy S10+ 
- OS version :  Android 12

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2787
Fixes #2592 

Just change the method to get data directory path in android 10 or above.

### CODE REVIEW

File: core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt [hunk 1]
```diff
@@ -63,9 +63,9 @@ object StorageDeviceUtils {
       ?.map { dir -> StorageDevice(dir, false) }
       .orEmpty()
 
-  private fun environmentDevices() =
+  private fun environmentDevices(context: Context) =
     StorageDevice(
-      generalisePath(Environment.getExternalStorageDirectory().path, false),
+      generalisePath(context.getExternalFilesDir("").toString(), true),
       Environment.isExternalStorageEmulated()
```
Comment (gouri-panda) [inline core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt:69]: This `environmentDevices` function is responsible for getting Environment external storage directory. Which can be shared by other applications.  I don't understand why do we wanna switch to `getExternalFilesDir`which is internal to the application and it's not visible to other applications.

Comment (MohitMaliFtechiz) [reply core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt:69]: Hi gouri-panda,

Actually ```Environment.getExternalStorageDirectory().path ``` is not working on android 10 and above because this method is depreciated. On android 10 and above its not returning any data. 

you can check the link.
https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()

Comment (gouri-panda) [reply core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt:69]: Sure! but is the alternative API is the right approach? There are a couple of things that don't satisfy our requirements.
1. It will be our private internal folder. Other applications can't search the zim files if they want to.
2. The data inside the folder will be deleted if the user wants to uninstall it.

Is `MediaStore` API will be the right option?

Comment (MohitMaliFtechiz) [reply core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt:69]: hi @gouri-panda ,

1. Yes according to current flow all zim files saved in app specific data directory ,app specific data directory can be shareable to other app  only below android 10. From android 10 and above they restricted access to another app data directory so we must need to move to public folders.
2. By changing using the ```Mediastore Api``` we can fix some of the existing issue like https://github.com/kiwix/kiwix-android/issues/2690.

So i think ```Mediastore Api``` will be better one.

**Comment by kelson42** [comment]
@gouri-panda Can we move on with the review of this PR please?
@MohitMaliFtechiz Please don't put the ticket numbers in the commits, but link them in the PRs description (see how I have done it).

**Comment by MohitMaliFtechiz** [comment]
> 

Ok @kelson42 I will take care in next PR and commits.

**Comment by gouri-panda** [comment]
@kelson42 As @MohitMaliFtechiz and I discussed before we will need  `MediaStore` API for these kinds of issues.

File: core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt (hunk 1 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt:69]: hi @gouri-panda and @kelson42 ,

I figure it out the solutions that app data must be in shareable folder with both internal and external storage. this will resolve lots of existing issues.

### Problem statement 
I tried with both ```file storage``` and ```MediaStore API``` but the problem is detection of  sdcard as secondary storage according to google doc on sdcard we can only create app specific folder. 
``` 
The WRITE_EXTERNAL_STORAGE permission must only grant write access to the primary external 
storage on a device. Apps must not be allowed to write to secondary external storage 
devices, except in their package-specific directories as allowed by synthesized 
permissions. Restricting writes in this way ensures the system can clean up files
when applications are uninstalled.
```

## Internal storage
a) I am able to create folder at topmost directory as kiwix and able to save zim file.

## External Storage
a) Since its detecting the sd card as secondary storage and not allowing to create public directory programmatically. App specific directory creation is working but our problem statement were different so only way to achieve this by issue the intent for ```ACTION_OPEN_DOCUMENT_TREE```. It will open file manager to select folder to save zim files on external storage.

I am following this solutions and its working .

https://stackoverflow.com/questions/35996341/android-gain-priviledges-to-write-to-secondary-sd-card-at-runtime

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda and @kelson42 ,

I have commit the solutions of above problem.

### For android 11 and above.
a) Internal :- we are creating folder inside public directory names as kiwix on root.
b) External :- we are using android x documents to allow user to select the folder by which we will get access to that folder then we are allowed to create files on that public folder.

### For below android 11
a) Internal :- we are creating folder inside public directory names as kiwix on root.
b) External :- we are not allowed to create files on any public folder,  only app specific is working so i made check.

**Comment by gouri-panda** [comment]
> hi @gouri-panda and @kelson42 ,
>
>I have commit the solutions of above problem.
>
>For android 11 and above.
a) Internal :- we are creating folder inside public directory names as kiwix on root.
b) External :- we are using android x documents to allow user to select the folder by which we will get access to that folder then we are allowed to create files on that public folder.
>
>For below android 11
a) Internal :- we are creating folder inside public directory names as kiwix on root.
b) External :- we are not allowed to create files on any public folder, only app specific is working so i made check.

@MohitMaliFtechiz Ok. Are you adding external search permission in this patch?

**Comment by MohitMaliFtechiz** [comment]
> > hi @gouri-panda and @kelson42 ,
> > I have commit the solutions of above problem.
> > For android 11 and above.
> > a) Internal :- we are creating folder inside public directory names as kiwix on root.
> > b) External :- we are using android x documents to allow user to select the folder by which we will get access to that folder then we are allowed to create files on that public folder.
> > For below android 11
> > a) Internal :- we are creating folder inside public directory names as kiwix on root.
> > b) External :- we are not allowed to create files on any public folder, only app specific is working so i made check.
> 
> @MohitMaliFtechiz Ok. Are you adding external search permission in this patch?

No actually i am creating public directory for storing and retrieve  files  not changing any search permissions.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Is this PR done?

**Comment by MohitMaliFtechiz** [comment]
Yes @gouri-panda

**Comment by kelson42** [comment]
@gouri-panda It is pretty urgent we move on this to start an extensive test if this PR really solves most of the reported problems.

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java [hunk 2]
```diff
@@ -278,13 +285,47 @@ private Unit onStorageDeviceSelected(StorageDevice storageDevice) {
...
 
+  private void selectFolder() {
+    Intent intent = new Intent(ACTION_OPEN_DOCUMENT_TREE);
+    intent.addFlags(
+      Intent.FLAG_GRANT_READ_URI_PERMISSION
+        | Intent.FLAG_GRANT_WRITE_URI_PERMISSION
+        | Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION
+        | Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);
+    startActivityForResult(intent, REQUEST_SELECT_FOLDER_PERMISSION);
+  }
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java:318]: We are duplicating code twice. Can we make it one?

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt [hunk 3]
```diff
@@ -76,12 +77,20 @@ class SharedPreferenceUtil @Inject constructor(val context: Context) {
     get() {
       val storage = sharedPreferences.getString(PREF_STORAGE, null)
       return when {
-        storage == null -> defaultStorage().also(::putPrefStorage)
-        !File(storage).exists() -> defaultStorage()
+        storage == null -> getActualPath(defaultStorage()).also(::putPrefStorage)
+          .also {
+            putStoragePosition(0)
+          }
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt:83]: We can inline those two functions inside the `also` operator.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt [hunk 4]
```diff
@@ -160,10 +173,21 @@ class SharedPreferenceUtil @Inject constructor(val context: Context) {
       _textZooms.offer(textZoom)
     }
 
+  fun getActualPath(path: String): String {
+    var s = path
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt:177]: This name of the function doesn't justify that the function actually does. A better function name would be nice.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt [hunk 5]
```diff
@@ -160,10 +173,21 @@ class SharedPreferenceUtil @Inject constructor(val context: Context) {
...
+    val separator = context.getString(R.string.android_directory_seperator)
+    val sepPos = path.indexOf(separator)
+    if (sepPos != -1) {
+      s = path.substring(0, sepPos)
+    }
+    return s
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt:183]: Kotlin's `substringBefore` method would fit nicely here.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 6]
```diff
@@ -228,4 +232,29 @@ object FileUtils {
...
+  @JvmStatic fun getPathFromUri(activity: Activity, data: Intent): String {
+    val uri: Uri? = data.data
+    val takeFlags: Int = data.flags and (Intent.FLAG_GRANT_READ_URI_PERMISSION
+      or Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
+    activity.grantUriPermission(
+      activity.packageName, uri,
+      Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION
+    )
+    activity.contentResolver.takePersistableUriPermission(uri!!, takeFlags)
+
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt:246]: Null check here also.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 7]
```diff
@@ -228,4 +232,29 @@ object FileUtils {
...
+    val dFile = DocumentFile.fromTreeUri(activity, uri)
+    val originalPath = dFile!!.uri.path!!.substring(
+      dFile.uri.path!!.lastIndexOf(":") + 1
+    )
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt:250]: Here also.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 8]
```diff
@@ -228,4 +232,29 @@ object FileUtils {
...
+
+    var path = "${activity.getExternalFilesDirs("")[1]}"
+    val separator: String = activity.getString(R.string.android_directory_seperator)
+    val sepPos = path.indexOf(separator)
+    if (sepPos != -1) {
+      path = path.substring(0, sepPos)
+    }
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt:257]: We are writing the same code twice. Utility or extension function would be great!

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt (hunk 7 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: null check added here.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt (hunk 6 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: added

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt (hunk 5 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt]: done

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt (hunk 4 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt]: rename to getPublicDirectoryPath

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt (hunk 3 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt]: done

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt [hunk 9]
```diff
@@ -242,8 +250,47 @@ class OnlineLibraryFragment : BaseFragment(), FragmentActivityExtensions {
...
+  @SuppressLint("WrongConstant") override fun onActivityResult(
+    requestCode: Int,
+    resultCode: Int,
+    data: Intent?
+  ) {
+    super.onActivityResult(requestCode, resultCode, data)
+    if (requestCode == REQUEST_SELECT_FOLDER_PERMISSION && resultCode == Activity.RESULT_OK) {
+      sharedPreferenceUtil.putPrefStorage(
+        getPathFromUri(requireActivity(), data!!)
+      )
```
[the remark this answers is not in the document]
Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt]: done

**Comment by kelson42** [comment]
@MohitMaliDeveloper Please close/collapse "discussions" which are done here on the review page.

File: core/build.gradle.kts [hunk 10]
```diff
@@ -45,6 +45,7 @@ dependencies {
   // SquiDB
   implementation(Libs.squidb)
   implementation(Libs.squidb_annotations)
+  implementation("androidx.documentfile:documentfile:1.0.1")
```
Comment (gouri-panda) [inline core/build.gradle.kts:48]: [nit] For consistency, we should store the name of the library in the `Libs.kt` file.

File: app/src/main/res/values/strings.xml [hunk 11]
```diff
@@ -6,4 +6,5 @@
   <string name="cannot_open_file">Failed to open file\nPlease try looking for this file in the Device Tab of your Library</string>
   <string name="send_files_title">Send Files</string>
   <string name="receive_files_title">Receive Files</string>
+  <string name="error_occurred" translatable="false">System unable to grant permission!</string>
```
Comment (gouri-panda) [inline app/src/main/res/values/strings.xml:9]: We are adding this in core module also. We can get rid of it here. The `core`module will share the resource between `app`  and `custom` module

File: core/src/main/res/values/strings.xml [hunk 12]
```diff
@@ -297,6 +297,7 @@
   <string name="not_allowed">Not allowed</string>
   <string name="android_directory_seperator" translatable="false">/Android</string>
   <string name="select_folder" translatable="false">Please select a folder for external storage.</string>
+  <string name="error_occurred" translatable="false">System unable to grant permission!</string>
```
Comment (gouri-panda) [inline core/src/main/res/values/strings.xml:300]: [nit] Mabe a better string resource name?

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 13]
```diff
@@ -234,27 +236,30 @@ object FileUtils {
...
 
-    var path = "${activity.getExternalFilesDirs("")[1]}"
-    val separator: String = activity.getString(R.string.android_directory_seperator)
-    val sepPos = path.indexOf(separator)
-    if (sepPos != -1) {
-      path = path.substring(0, sepPos)
+      val dFile = DocumentFile.fromTreeUri(activity, uri)
+      if (dFile != null) {
+        val originalPath = dFile.uri.path!!.substring(
+          dFile.uri.path!!.lastIndexOf(":") + 1
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt:253]: Uri's path can be null here. So we should check the null pointer exception.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: done

File: app/src/main/res/values/strings.xml (hunk 11 above)
Comment (MohitMaliFtechiz) [reply app/src/main/res/values/strings.xml]: move to core

File: core/build.gradle.kts (hunk 10 above)
Comment (MohitMaliFtechiz) [reply core/build.gradle.kts]: move to libs.kt

**Comment by kelson42** [comment]
@MohitMaliFtechiz Does this PR is ready for a new review?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Does this PR is ready for a new review?
Yes

**Comment by kelson42** [comment]
@MohitMaliDeveloper Then please rerequest a review, because otherwise no way to know it.

**Review by gouri-panda — DISMISSED** [review]

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz One small request static analysis ci is failing.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please don't forget to rebase on `develop` at the end.

**Comment by mbe57** [comment]
Hi team,
I could not locate an apk download of the nightlys. This Android 11 file access issue really sucks and I would be more than happy to beta test - WITHOUT the need to become an Android developer ...
Can you pls. advise?
TXs and cheers
Michael

**Comment by kelson42** [comment]
@mbe57 You will have to wait that we merge this PR to see it in the nightlies at https://download.kiwix.org/nightly/

**Comment by mbe57** [comment]
TXs for the quick guidance and the link, kelson42.
That would be the file dev-universal-debug.apk? The only apk I found while checking a number of days ...

**Review by gouri-panda — APPROVED** [review]

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Please don't forget to rebase on `develop` at the end.

done

**Review by gouri-panda — DISMISSED** [review]

**Comment by sidsunday** [comment]
You are super heroes, sony 5 ii andro 12. Lib 26gb internal/0/kiwix. But what to do with "leaks" notifications?

**Comment by kelson42** [comment]
@MohitMaliDeveloper A few remarks:
* Please rebase *systematically* on develop when PR is ready to merge.
* Commit message should start with uppercase and be short. If you have a long explanation (which is necessary time to time) please put in the commit description (other with the git revision log not readable).

**Review by kelson42 — APPROVED** [review]

**Comment by kelson42** [comment]
@sidsunday Do you have leaks you can specificaly connect to the code of this PR?

**Comment by gouri-panda** [comment]
@kelson42 I don't think the memory leak is related to this PR.

**Comment by traverseda** [comment]
I can confirm that this is still an issues on my samsung galaxy note 10 s of version 3.4.5

**Comment by kelson42** [comment]
@traverseda Can you please open a new tickets with all the necessary details please (like for example you kiwix exact version)?
