### PR TITLE
#1868 Fix app crash on tab navigation after closing tab.

### LINKED ISSUE #1868: App stops when trying to navigate between tabs after a tab is closed
**Describe the bug**

The app stops when user tries to navigate between different tabs after closing a tab. 

**Expected behavior**

App should not close unexpectedly

**Steps to reproduce the behavior:**
1. Open 2 or more tabs.
2. Close any one of the tabs.
3. Click on the tabs display point.
IMG_20200308_121451
4. App crashes.

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : realme X
- OS version : Android 9

### PR DESCRIPTION
**Pull request by Frans-Lukas**
Fixes #1868

The bug occurs when the `currentWebViewIndex` is the last index of the `webViewList` and a tab is closed. After any tab is closed, the `webViewList` length is reduced by one. When we then try to open any tab: `hideTabSwitcher()` is called, which in turn calls `selectTab(currentWebViewIndex)`. Since `currentWebViewIndex` is the previous last index of the `webViewList` we get an index out of bounds exception. 

To solve this I added `currentWebViewIndex = 0;` to the `closeTab()` method. This seems to fix the issue. A more robust solution might be to calculate the new index when a tab is closed but just setting it  to zero seems to work as well.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 1]
```diff
@@ -845,6 +845,7 @@ private void newTabInBackground(String url) {
   }
 
   private void closeTab(int index) {
+    currentWebViewIndex = 0;
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: we should decrement the current index if the closing index is less than or equal and do nothing if greater than I would say

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Sounds better!

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 2]
```diff
@@ -845,9 +845,11 @@ private void newTabInBackground(String url) {
   }
 
   private void closeTab(int index) {
-    currentWebViewIndex = 0;
     tempForUndo = webViewList.get(index);
     webViewList.remove(index);
+    if(currentWebViewIndex >= webViewList.size()){
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: my thinking was
```
if (index <= currentWebviewIndex){
  currentWebViewIndex--;
}
```

did that not work?

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: oh right, its removing a specific index. Missed that!

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: hmm no what if the index is 0

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: @Frans-Lukas did you see the above comment?

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: oh, no I didnt. I'll fix!
