### PR TITLE
Fixes of Some deprecation warnings are showing in the logs but they are already fixed

### LINKED ISSUE #3443: Some deprecation warnings are showing in the logs but they are already fixed.
**Describe the bug**
Some deprecation warnings are appearing in the logcat, as [mentioned here](https://github.com/kiwix/kiwix-android/actions/runs/5411219667/jobs/9833687025?pr=3440). These warnings are caused by certain methods being deprecated in Android 13. However, since there is no alternative available for these methods prior to Android 13, we need to use them for compatibility with all Android versions.

**Expected behavior**
We should suppress these warnings as we already placed a fix for this type of deprecation.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3443 

As we already fixed the deprecated code for Android 13 and below, we have suppressed the deprecation warning because we do not have any alternative for these methods and these are only deprecated in Android 13.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt [hunk 1]
```diff
@@ -1173,6 +1174,7 @@ abstract class CoreReaderFragment :
     }
   }
 
+  @Suppress("DEPRECATION")
   override fun onOptionsItemSelected(item: MenuItem): Boolean =
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:1178]: Instead of suppressing this method from the lint. We should use the `MenuProvider` option.

**Review by gouri-panda — COMMENTED** [review]
@MohitMaliDeveloper We should use the `MenuProvider` api to remove the deprecated methods of menu.

**Review by gouri-panda — APPROVED** [review]
