### PR TITLE
fix: Only selected Books are being displayed in Browser

### LINKED ISSUE #2447: In browser Hosting books shows after unselecting
**Describe the bug**
After unselecting a book on the phone it still shows on the browser.

**Expected behavior**
It should show books which are selecting.

**Steps to reproduce the behavior:**
1. Start the server on HostFragment
2. Open into your browser and start the server
3. stop the sever on the phone
4. Unselect one book
5. Start the server again
6. Refresh the browser see the unselect book

**Environment**
- Version of Kiwix Android : develop

### PR DESCRIPTION
**Pull request by s-ayush2903**
Close #2447 

~Binded and Un-binded service on server starts and stops to completely terminate connection from server when hotspot is switched off~

UPD: 
* Created new lib and server by the closing and restarting of hotspot. 
* Created a new serverFactory class for creating instances of server.
* Created a new libraryFactory class for creating instances of library.

**Screenshots** 
Entire working depicted here: https://youtu.be/06rimrunI6U

### CODE REVIEW

**Comment by macgills** [comment]
I am not a fan of the client having to implement a fix instead of the the hotspot being changed to be more friendly to use.

The offending segment, as you correctly identified, is

```
private boolean startAndroidWebServer(ArrayList<String> selectedBooksPath) {
    if (!isServerStarted) {
      int DEFAULT_PORT = 8080;
      ServerUtils.port = DEFAULT_PORT;
      for (String path : selectedBooksPath) {
        try {
          boolean isBookAdded = kiwixLibrary.addBook(path);
          Log.v(TAG, "isBookAdded: " + isBookAdded + path);
        } catch (JNIKiwixException e) {
          Log.v(TAG, "Couldn't add book " + path);
        }
      }
      kiwixServer.setPort(ServerUtils.port);
      updateServerState(kiwixServer.start());
      Log.v(TAG, "Server status" + isServerStarted);
    }
    return isServerStarted;
  }
```

The problem is instances of `kiwixLibrary` are shared between server starts & stops. We could simply create a new library before this loop starts, instead of injecting a `Library kiwixLibrary` We could perhaps inject a factory that creates libraries.

**Comment by s-ayush2903** [comment]
So is this amount of work really needed for an issue that can be solved by a subtle change only, would making the new changes needed help us at some other sites too?

**Comment by s-ayush2903** [comment]
Fine, I'll do it. Writing a factory sounds cool to me, I have never written factory for production, it'll be too cool and exciting. On it. Thanks!

**Comment by s-ayush2903** [comment]
How else we can create library, like previously we were injecting it via defining in service module, and it is a class over which we have no control. Then how can we provide custom creation method to it? Like, in the code just pushed in the latest commit, I firmly believe we have the same instances of library in multiple runs, how can we avoid it via providing custom method of creation?

**Comment by macgills** [comment]
> How else we can create library, like previously we were injecting it via defining in service module, and it is a class over which we have no control. Then how can we provide custom creation method to it? Like, in the code just pushed in the latest commit, I firmly believe we have the same instances of library in multiple runs, how can we avoid it via providing custom method of creation?

Your factory is indeed not a factory as it just returns the same instance over and over again. Instead of doing that just create a Library by using its constructor.

Like how in the module we _provide_ a Library
```
  @Provides
  @ServiceScope
  fun providesLibrary(): Library = Library()
```


Looking at the module code this gets a bit more complicated.

The Library used in the `WebServerHelper` & `JNIKiwixServer` must be the same.

**Comment by s-ayush2903** [comment]
* When I create instances of `Library` in factory via `Library()` it doesn't work, means books ain't sent to the server, because when I use `Library()`, it considers it as a constructor in `Library.class`, not the entire class and hence doesn't work. 
* In the serviceModule, we are providing(creating) `Library()`(via `providesLibrary()` fun), the constructor as when I `Ctrl + Click` on it, it takes me to the constructor, and in the JniKiwixServer, we are passing `Library` as param, that's why it works.
* I want to keep the return type of factory to be `Library()` and from the fun defined there, return new instances of `Library`, but as explained previously, when I return `Library()` from the fun, it doesn't work and I know the reason behind it too and unable to fix it

**Comment by macgills** [comment]
>The Library used in the WebServerHelper & JNIKiwixServer must be the same.

At the point where you want to start a server with a new selection of books you need to create a new Library, with that library create a new server, add books to the library and start that server.

**Comment by s-ayush2903** [comment]
And I believe I'm doing exact same thing, given that now the fun in factory _returns_ `Library()`, and still nothing changed.
suree

**Comment by macgills** [comment]
> And I believe I'm doing exact same thing, given that now the fun in factory _returns_ `Library()`, and still nothing changed.
> suree

You are using the same instance of `JNIKiwixServer` which has the old instance of `Library`

**Comment by s-ayush2903** [comment]
But how can I change instance of Library in JNIKiwixServer, it is being injected and how can we supply new different instance of library to it now.

**Comment by macgills** [comment]
How it can be achieved is very simple

```
var server:JNIKiwixServer?= null
.
.
.
library = Library()
server = JNIKiwixServer(library)
```

How it should be achieved is less simple. I would probably introduce a new class KiwixServer, as well as a KiwixServer.Factory. The factory method could look like `fun create(List<String> selectedBooksPath): KiwixServer`.

**Comment by s-ayush2903** [comment]
Should I move LibraryFactory & KiwixServer inside a new package with name _hostUtils_ or _utils_ inside _webserver_ dir, current location of libFactory doesn't look good to me.

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+import javax.inject.Inject
+
+private const val TAG = "KiwixServer"
+
+class KiwixServer @Inject constructor(kiwixLibraryFactory: LibraryFactory) {
+  private val libFactory = kiwixLibraryFactory
+  private lateinit var kiwixLibrary: Library
+
+  fun createKiwixServer(selectedBooksPath: ArrayList<String>): JNIKiwixServer? {
+    kiwixLibrary = libFactory.createKiwixLibrary()
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:35]: can be a local val

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+    for (path in selectedBooksPath) {
+      try {
+        var isBookAdded: Boolean = kiwixLibrary.addBook(path)
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:38]: unused var

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+
+private const val TAG = "KiwixServer"
+
+class KiwixServer @Inject constructor(kiwixLibraryFactory: LibraryFactory) {
+  private val libFactory = kiwixLibraryFactory
+  private lateinit var kiwixLibrary: Library
+
+  fun createKiwixServer(selectedBooksPath: ArrayList<String>): JNIKiwixServer? {
+    kiwixLibrary = libFactory.createKiwixLibrary()
+    for (path in selectedBooksPath) {
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:36]: `forEach` might read nicer

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java [hunk 4]
```diff
@@ -41,14 +40,13 @@
 
 public class WebServerHelper {
   private static final String TAG = "WebServerHelper";
-  private Library kiwixLibrary;
-  private JNIKiwixServer kiwixServer;
+  private KiwixServer kiwixServer;
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:43]: The idea behind KiwixServer was that it would be a facade for JNIKiwixServer, right now you are using KiwixServer as a factory for JniKiwixServer and I'd rather there was a KiwixServer.Factory that creates `KiwixServer`s which have methods `start(port)` & `stop()`

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryFactory.kt [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+ * along with this program. If not, see <http://www.gnu.org/licenses/>.
+ *
+ */
+
+package org.kiwix.kiwixmobile.nav.destination.library
+
+import org.kiwix.kiwixlib.Library
+import javax.inject.Inject
+
+class LibraryFactory @Inject constructor() : Library() {
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryFactory.kt:24]: This is now probably overkill, before we were trying to express that it was important for the functioning of the server that new libraries are created and if we go the KiwixServer.Factory route then that'll express that for us

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java (hunk 4 above)
Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:43]: If I create a start & stop function in `KiwixServer` class, then it'll have to take `server` as a param too or we can avoid that via creating an extension fun on server

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryFactory.kt (hunk 5 above)
Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryFactory.kt:24]: It has been added as a compensation to the deletion of `providesLibrary()` fun from serviceModule. I can remove it from KiwixServer, but is its entire deletion necessary?

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java (hunk 4 above)
Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:43]: KiwixServer will be a class that accepts JNIKiwixServer as a constructor val

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryFactory.kt (hunk 5 above)
Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryFactory.kt:24]: yes, if you create a KiwixServer.Factory then you would have to pass in this LibraryFactory to it for it to be used and then I will have read the word Factory too much and will hate the code. It is also currently inconsistent, you use a factory for the library but not for the JniKiwixServer and if you were to add a JniKiwixServerFactory that would be altogether too many factories.

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+import android.util.Log
+import org.kiwix.kiwixlib.JNIKiwixException
+import org.kiwix.kiwixlib.JNIKiwixServer
+import org.kiwix.kiwixmobile.nav.destination.library.LibraryFactory
+import javax.inject.Inject
+
+private const val TAG = "KiwixServer"
+
+class KiwixServer @Inject constructor(kiwixLibraryFactory: LibraryFactory) {
+  private val libFactory = kiwixLibraryFactory
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:30]: this will disappear but I should highlight this is a mistake, if you just moved `private val` to the constructor parameter then you wouldn't need to assign it to this variable

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryFactory.kt (hunk 5 above)
Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryFactory.kt:24]: Fine, so I'll remove LibFactory then

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java (hunk 4 above)
Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:43]: How's that going to help me, when I'll create a new start function in `KiwixServer`, I won't be able to access the constructor param, then how?

Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:43]: Is there any problem/violation with the usage of extension function?

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:43]: you can access the constructor param, as I said in another comment on this PR eg

```
class KiwixServer(private val jniKiwixServer:JniKiwiServer){

fun stop(){
  jniKiwixServer.stop()
}
```

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:42]: The point of KiwixServer is to be a one stop class that explains this coupled nature of Library/JniKiwixServer if somebody cares to look but from the outside has a simple API that a reader can just breeze through.

Technically I guess KiwixServer.Factory could really just be JniKiwixServerFactory as the Libray with books is just an implementation detail but I prefer having these wrapper classes around our JNI objects, sometimes kiwixlib updates internal representations and it is useful to only have to update in 1 place, not that it matters tooooo much on this one as we only use server in this 1 place, still good practice though.

Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:42]: Ah shoot! missed it

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+import android.util.Log
+import org.kiwix.kiwixlib.JNIKiwixException
+import org.kiwix.kiwixlib.JNIKiwixServer
+import org.kiwix.kiwixlib.Library
+import javax.inject.Inject
+
+private const val TAG = "KiwixServer"
+
+class KiwixServer @Inject constructor(private val jniKiwixServer: JNIKiwixServer) {
+  fun createKiwixServer(selectedBooksPath: ArrayList<String>): JNIKiwixServer? {
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:30]: this method should be a member of `KiwixServer.Factory` ie

```
class KiwixServer {
  class Factory{
     fun createKiwixServer(){ etc }
  }
}

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java (hunk 4 above)
Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:42]: >  KiwixServer will be a class that accepts JNIKiwixServer as a constructor val

If we consider it logically, then we're using `Factory` class inside `KiwixServer` class to create `JNIKiwixServer` and the main class itself needs a `JNIKiwixServer` as a param to create an instance in some other java class, whoah! Sounds extremely weird to me.

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt (hunk 7 above)
Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:30]: Did you find this advice confusing? I can explain it in more detail if you want to highlight the parts you are having trouble with

Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:30]: Nope, this isn't confusing to me, I am able to do this. But to use this factory I have to create an instance of it in the serverHelper class and that is also cool, with this I'm able to create JNIKiwixServer also with the help of factory. But the problem occurs when I call `start` and `stop` server function, it uses the `jniKiwixServer` param which I pass in the constructor of the main class. 

And here comes the problem: it is unable to start the server(when I click concerned button in the device), most probably because we have two different jniKiwixServers being used(the one created from factory and the one that is being injected in the class).

But when I tried hacking it, I removed it as a param in the main class, now I declare this var jniKiwixServer as lateinit, and assign it inside the server creation function that lies inside the factory, with this being done, now I believe that the server being created, started and stopped are same. And when I run it in the device, application crashes saying `propery declared lateinit has not been intialized`, despite the fact I'm initializing it inside the facotry function.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:30]: I am having an tough time parsing this, here is what the code should look like

```
class KiwixServer(private val jniKiwixServer:KiwixServer) {
  class Factory{
     fun createKiwixServer(selectedBooksPath: ArrayList<String>):KiwixServer{
        ...
       return KiwixServer(JNIKiwixServer(library))
   }
  }

 fun start(port:Int):Boolean{
    jniKiwixServer.setPort(port)
    return jniKiwixServer.start()
  }

//also a stop method
}
```

Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:30]: One thing I would add that I'm writing start and stop server functions inside the factory class.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:30]: A factory should only create. In the example above `KiwixServer.Factory` is a different class to `KiwixServer`, `KiwixServer` holds the responsibility of controlling jniKiwixServer. Here is the docs on [nested/inner classes](https://kotlinlang.org/docs/reference/nested-classes.html) they are a bit different from java's in their default behaviour

Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt:30]: Holy Jesus!! (for https://github.com/kiwix/kiwix-android/pull/2536#discussion_r542248089)

File: app/src/main/java/org/kiwix/kiwixmobile/di/modules/ServiceModule.kt [hunk 8]
```diff
@@ -38,10 +39,9 @@ class ServiceModule {
   @Provides
   @ServiceScope
   fun providesWebServerHelper(
-    jniKiwixLibrary: Library,
-    kiwixServer: JNIKiwixServer,
+    kiwixServer: KiwixServer,
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/di/modules/ServiceModule.kt:42]: this will want to be the factory, KiwixServer will either want to be a `lateinit val` or a nullable var

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/di/modules/ServiceModule.kt:42]: ugh, right Java. Well it'll just be a private field

Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/di/modules/ServiceModule.kt]: Yep!

File: app/src/main/java/org/kiwix/kiwixmobile/di/modules/ServiceModule.kt [hunk 9]
```diff
@@ -38,10 +39,9 @@ class ServiceModule {
   @Provides
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/di/modules/ServiceModule.kt:39]: We should delete the providers for Library/Server as they are no longer used

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java [hunk 10]
```diff
@@ -41,15 +39,15 @@
...
+  private KiwixServer.Factory kiwixServerFactory;
   private IpAddressCallbacks ipAddressCallbacks;
   private boolean isServerStarted;
+  private JNIKiwixServer server;
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.java:46]: this is unused

**Review by macgills — APPROVED** [review]
