### PR TITLE
#2037 Crash Report 3.3.0: NPE NightModeViewPainter.deactivateNightMode (NightModeViewPainter.java:55)

### LINKED ISSUE #2037: Crash Report 3.3.0: NPE NightModeViewPainter.deactivateNightMode (NightModeViewPainter.java:55)
**Describe the bug**
```
java.lang.NullPointerException: 

 
  at org.kiwix.kiwixmobile.core.main.NightModeViewPainter.deactivateNightMode (NightModeViewPainter.java:55)

 
  at org.kiwix.kiwixmobile.core.main.NightModeViewPainter.update (NightModeViewPainter.java:50)

 
  at org.kiwix.kiwixmobile.core.main.CoreMainActivity.updateNightMode (CoreMainActivity.java:1551)

 
  at org.kiwix.kiwixmobile.core.main.CoreMainActivity.webViewUrlFinishedLoading (CoreMainActivity.java:1633)

 
  at org.kiwix.kiwixmobile.core.main.CoreWebViewClient.onPageFinished (CoreWebViewClient.java:129)

 
  at O7.b (O7.java:2)

 
  at Do.handleMessage (Do.java:65)

 
  at android.os.Handler.dispatchMessage (Handler.java:107)

 
  at android.os.Looper.loop (Looper.java:214)

 
  at android.app.ActivityThread.main (ActivityThread.java:7356)

 
  at java.lang.reflect.Method.invoke (Method.java)

 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)

 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:930)
```

### PR DESCRIPTION
**Pull request by macgills**
Fixes #2037 

 - make NPE impossible

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 1]
```diff
@@ -1548,8 +1548,11 @@ private void updateUrlProcessor() {
   }
 
   private void updateNightMode() {
-    painter.update(getCurrentWebView(), kiwixWebView -> kiwixWebView.getUrl() == null
-      || !kiwixWebView.getUrl().equals(HOME_URL), videoView);
+    painter.update(getCurrentWebView(), this::shouldActivateNightMode, videoView);
+  }
+
+  private boolean shouldActivateNightMode(KiwixWebView kiwixWebView) {
+    return kiwixWebView!=null && !HOME_URL.equals(kiwixWebView.getUrl());
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java:1555]: Formatting. Space should be added before & after `!=`.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Thanks for the catch, stupid java. Fixed
