### PR TITLE
Feature/gouri-panda/2364 fix text to speech button and bug fix

### LINKED ISSUE #2364: TextToSpeech Pause/Stop buttons no longer visible and subsequent read alouds cause a crash
**Describe the bug**
The buttons do not appear and I got the folllowing crash testing the feature
```
2020-09-07 08:48:00.385 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 15093
    java.lang.NullPointerException: Attempt to read from field 'org.kiwix.kiwixmobile.core.main.KiwixTextToSpeech$TTSTask org.kiwix.kiwixmobile.core.main.KiwixTextToSpeech.currentTTSTask' on a null object reference
        at org.kiwix.kiwixmobile.core.main.CoreReaderFragment.lambda$setUpTTS$3$CoreReaderFragment(CoreReaderFragment.java:683)
        at org.kiwix.kiwixmobile.core.main.-$$Lambda$CoreReaderFragment$dJ7yV3A9jJPxjfun6ekvjOK-1AA.onAudioFocusChange(Unknown Source:2)
        at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2144)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Expected behavior**
Read aloud to be controlled by in app UI and to be free of crashes

**Steps to reproduce the behavior:**
1. Open a zim file
1. click read aloud from the overflow menu
1. hear the contents being read but see no UI for controlling it
1. press back until you exit the app
1. re-launch application and repeat steps 1&2
1. crash

**Screenshots**

**Environment**
- Version of Kiwix Android : develop
- Device : nexus5x
- OS version : 8.1

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2364 

**Screenshots** 
NA

### CODE REVIEW

**Comment by macgills** [comment]
```
E/AndroidRuntime( 3729): java.lang.RuntimeException: Unable to destroy activity {org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.main.KiwixMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kiwix.kiwixmobile.core.main.KiwixTextToSpeech.shutdown()' on a null object reference
```

Instrumentation tests are not happy

**Comment by gouri-panda** [comment]
> ```
> E/AndroidRuntime( 3729): java.lang.RuntimeException: Unable to destroy activity {org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.main.KiwixMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kiwix.kiwixmobile.core.main.KiwixTextToSpeech.shutdown()' on a null object reference
> ```
> 
> Instrumentation tests are not happy

What should I do?

**Comment by macgills** [comment]
Fix them. I would guess a bug has been introduced by making KiwixTextToSpeech null
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kiwix.kiwixmobile.core.main.KiwixTextToSpeech.shutdown()' on a null object reference
```

I don't think we call shutdown in many places, it should be easy to track down.

Intrumentation tests are found in `androidTest` directory, you can run them from the IDE or with gradle

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java [hunk 1]
```diff
@@ -738,8 +740,10 @@ private void handleLocaleCheck() {
     unbinder.unbind();
     // TODO create a base Activity class that class this.
     FileUtils.deleteCachedFiles(getActivity());
+    if (tts != null){
     tts.shutdown();
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:744]: this is not indented properly

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:744]: this is still not indented properly, the body of an if shouldn't be at the same level as the if statement

File: core/src/main/res/layout/reader_fragment_content.xml [hunk 2]
```diff
@@ -95,10 +95,10 @@
     android:text="@string/tts_pause"
     android:textStyle="bold"
     android:visibility="gone"
-    app:layout_constraintBottom_toTopOf="parent"
     app:layout_constraintEnd_toStartOf="@id/activity_main_button_stop_tts"
     app:layout_constraintHorizontal_chainStyle="packed"
-    app:layout_constraintStart_toStartOf="parent" />
+    app:layout_constraintStart_toStartOf="parent"
+    app:layout_constraintTop_toTopOf="parent" />
```
Comment (macgills) [inline core/src/main/res/layout/reader_fragment_content.xml:101]: the pause and stop buttons used to be at the bottom of the screen, it is weird how they are now obscuring the toolbar at the top

Comment (gouri-panda) [reply core/src/main/res/layout/reader_fragment_content.xml:101]: Should I move to the bottom?

Comment (macgills) [reply core/src/main/res/layout/reader_fragment_content.xml:101]: yes

**Comment by macgills** [comment]
Pausing and then resuming does not work. There is also a memory leak from the AudioManager

**Comment by gouri-panda** [comment]
>There is also a memory leak from the AudioManager

@macgills I'm can't find the cause of the leak. LeakCanary tells the following message
```
this because org.kiwix.kiwixmobile.nav.destination.reader.KiwixReaderFragment received Fragment#onDestroy() callback and Fragment#mFragmentManager is null
```
I can't find mFrgamentManager in kiwixReaderFrgament.

**Comment by macgills** [comment]
image
This doesn't look good, ideally the pause/Stop buttons would dodge insets much like our fab does so that they move with our entire bottom section, not just the nav bar

**Comment by macgills** [comment]
Look to the rest of the leak, yes the fragment is ultimately leaking but why?

image


AudioManager is clearly a culprit.

```
val audioFocusRequest = am.requestAudioFocus(
      onAudioFocusChangeListener, AudioManager.STREAM_MUSIC,
      AudioManager.AUDIOFOCUS_GAIN
    )
```
This is the only usage of audioManager in the project. You will probably want to explore the api of AudioManager more to figure out how to clean up this request

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt [hunk 3]
```diff
@@ -160,16 +163,25 @@ class KiwixTextToSpeech internal constructor(
       AudioManager.AUDIOFOCUS_GAIN
     )
     Log.d(TAG_KIWIX, "Audio Focus Requested")
+    abandonAudioFocus()
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt:166]: I doubt we want to immediately abandon the audio focus request. This is probably meant to be in shutdown.

With this our focus change code would not run

```
focusChange -> {
      Log.d(TAG_KIWIX, "Focus change: " + focusChange);
      if (tts.currentTTSTask == null) {
        tts.stop();
        return;
      }
      switch (focusChange) {
        case (AudioManager.AUDIOFOCUS_LOSS):
          if (!tts.currentTTSTask.paused) tts.pauseOrResume();
          pauseTTSButton.setText(R.string.tts_resume);
          break;
        case (AudioManager.AUDIOFOCUS_GAIN):
          pauseTTSButton.setText(R.string.tts_pause);
          break;
      }
    }
```

Is audio focus something you are familiar with? It is basically how the system negotiates who gets to use the speakers so that you don't start playing spotify and a youtube video at the same time.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java [hunk 4]
```diff
@@ -738,8 +740,10 @@ private void handleLocaleCheck() {
     unbinder.unbind();
     // TODO create a base Activity class that class this.
     FileUtils.deleteCachedFiles(getActivity());
-    tts.shutdown();
-    tts = null;
+    if (tts != null) {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:743]: we can just use `tts?.shutdown()` instead of the `if`

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java [hunk 5]
```diff
@@ -1495,10 +1502,14 @@ private void saveTabStates() {
   public void onPause() {
     super.onPause();
     saveTabStates();
+    if (tts != null) {
+      tts.stop();
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1506]: similarly `tts?.stop()`

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt [hunk 6]
```diff
@@ -161,15 +158,19 @@ class KiwixTextToSpeech internal constructor(
     )
     Log.d(TAG_KIWIX, "Audio Focus Requested")
     synchronized(focusLock) {
-      return@requestAudioFocus audioFocusRequest ==
-        AudioManager.AUDIOFOCUS_REQUEST_GRANTED
+      return@requestAudioFocus audioFocusRequest == AudioManager.AUDIOFOCUS_REQUEST_GRANTED
     }
   }
 
+  private fun abandonAudioFocus() {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt:165]: we can inline this method, only 1 usage and the method name just repeats the called method name

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java (hunk 4 above)
Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:743]: @macgills It's in java.

File: core/src/main/res/layout/reader_fragment_content.xml [hunk 7]
```diff
@@ -71,6 +115,8 @@
       app:layout_anchor="@id/bottom_toolbar"
       app:layout_dodgeInsetEdges="bottom"
       tools:visibility="visible" />
+
```
Comment (macgills) [inline core/src/main/res/layout/reader_fragment_content.xml:118]: bit of extra space in this file, format it and it should get rid of it

**Comment by macgills** [comment]
Functionality is all looking good, we should be able to merge very soon

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java (hunk 4 above)
Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:743]: d'oh, stupid java

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt (hunk 6 above)
Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt:165]: @macgills is this okay?
```
private fun abandonAudioFocus() = am.abandonAudioFocus(onAudioFocusChangeListener)
```

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt:165]: inline has a specific meaning. place your cursor on `abandonAudioFocus()`, press `ctrl+alt+n` and you will get inline options

**Review by macgills — DISMISSED** [review]

**Review by macgills — APPROVED** [review]
