### PR TITLE
#1519 JniKiwixException opening Zim file

### LINKED ISSUE #1519: Crash Report 3.0.3: JniKiwixException opening file
**Describe the bug**
```
Caused by: org.kiwix.kiwixlib.JNIKiwixException: 

 
  at org.kiwix.kiwixlib.JNIKiwixReader.<init> (JNIKiwixReader.java:141)

 
  at org.kiwix.kiwixmobile.zim_manager.ZimFileReader.<init> (ZimFileReader.java:50)

 
  at org.kiwix.kiwixmobile.zim_manager.ZimFileReader$Factory$Impl.create (ZimFileReader.java:58)

 
  at org.kiwix.kiwixmobile.zim_manager.ZimReaderContainer.setZimFile (ZimReaderContainer.java:46)

 
  at org.kiwix.kiwixmobile.main.MainActivity.openZimFile (MainActivity.java:1092)

 
  at org.kiwix.kiwixmobile.main.MainActivity.manageExternalLaunchAndRestoringViewState (MainActivity.java:1903)

 
  at org.kiwix.kiwixmobile.main.MainActivity.onCreate (MainActivity.java:383)
```
Opening a file failed

**Expected behavior**
No Crash

**Environment**
- Version of Kiwix Android : 3.0.3
- Device : LGE V20 (elsa)
- OS version : Android 8.0

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1519

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java [hunk 1]
```diff
@@ -1090,18 +1090,24 @@ private void openZimFile(File file, boolean clearHistory) {
...
+            // signal to menu create to show
+            requestInitAllMenuItems = true;
+          }
+          openMainPage();
+          presenter.loadCurrentZimBookmarksUrl();
         } else {
-          // Menu may not be initialized yet. In this case
-          // signal to menu create to show
-          requestInitAllMenuItems = true;
+          Toast.makeText(this, getResources().getString(R.string.error_file_invalid),
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]:
```suggestion
          Toast.makeText(this, R.string.error_file_invalid, Toast.LENGTH_LONG).show();
```

File: app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java [hunk 2]
```diff
@@ -1090,18 +1090,24 @@ private void openZimFile(File file, boolean clearHistory) {
...
+            Toast.LENGTH_LONG).show();
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]:
```suggestion
```

**Comment by macgills** [comment]
I will merge this as we will be releasing 3.0.4 today
