### PR TITLE
Fixed Bottom Navigation disappear after saving language

### LINKED ISSUE #3208: Bottom Navigation disappear after saving language
**Describe the bug**
Bottom Navigation disappear after saving language.

**Expected behavior**
It should not disappear.

**Steps to reproduce the behavior:**
* Go to Download Fragment.
* Click on language icon.
* Select any language and click on save icon.
* You will see bottom navigation is disappear.

**Screenshots**

drawing

**Video**

https://user-images.githubusercontent.com/34593983/213103460-b406d690-b0a1-4f0c-9f43-ca65f0c01b6e.mp4

**Environment**
- Version of Kiwix Android : Current develop branch (3.6.0).
- Device : Redmi Note 9
- OS version : Android 12

**Logs**

```
W/System.err: java.lang.IllegalStateException: Method setCurrentState must be called on the main thread
W/System.err:     at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:323)
W/System.err:     at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:120)
W/System.err:     at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.kt:185)
W/System.err:     at androidx.navigation.NavBackStackEntry.setMaxLifecycle(NavBackStackEntry.kt:156)
W/System.err:     at androidx.navigation.NavController.popEntryFromBackStack(NavController.kt:675)
W/System.err:     at androidx.navigation.NavController.access$popEntryFromBackStack(NavController.kt:68)
W/System.err:     at androidx.navigation.NavController$popBackStackInternal$2.invoke(NavController.kt:560)
W/System.err:     at androidx.navigation.NavController$popBackStackInternal$2.invoke(NavController.kt:557)
W/System.err:     at androidx.navigation.NavController$NavControllerNavigatorState.pop(NavController.kt:324)
W/System.err:     at androidx.navigation.fragment.FragmentNavigator.popBackStack(FragmentNavigator.kt:103)
W/System.err:     at androidx.navigation.NavController.popBackStackInternal(NavController.kt:274)
W/System.err:     at androidx.navigation.NavController.popBackStackInternal(NavController.kt:557)
W/System.err:     at androidx.navigation.NavController.popBackStack(NavController.kt:472)
W/System.err:     at androidx.navigation.NavController.popBackStack(NavController.kt:449)
W/System.err:     at androidx.navigation.NavController.popBackStack(NavController.kt:434)
W/System.err:     at androidx.navigation.NavController$onBackPressedCallback$1.handleOnBackPressed(NavController.kt:191)
W/System.err:     at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:192)
W/System.err:     at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:657)
W/System.err:     at org.kiwix.kiwixmobile.core.main.CoreMainActivity.onBackPressed(CoreMainActivity.kt:244)
W/System.err:     at org.kiwix.kiwixmobile.language.viewmodel.SaveLanguagesAndFinish.invokeWith$lambda-1(SaveLanguagesAndFinish.kt:36)
W/System.err:     at org.kiwix.kiwixmobile.language.viewmodel.SaveLanguagesAndFinish.$r8$lambda$eVDOCRbgnNlpnMjQBZ0akm2A8bs(Unknown Source:0)
W/System.err:     at org.kiwix.kiwixmobile.language.viewmodel.SaveLanguagesAndFinish$$ExternalSyntheticLambda1.accept(Unknown Source:4)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
W/System.err:     at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:50)
W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:14935)
W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:14882)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
```

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3208 

**What is the issue**
The main culprit is ```activity.onBackPressed()``` in ```SaveLanguagesAndFinish.kt``` for this bug beacuse it's not called from ```main thread```. That's the reason our activity did not recognised this is ```OnlineFragment``` after saving language.

```
Flowable.fromCallable { languageDao.insert(languages) }
      .subscribeOn(Schedulers.io())
      .subscribe({
        activity.onBackPressed()
      }, Throwable::printStackTrace)
```

**What i do for fixing this issue**

* I have tested with ```AndroidSchedulers.mainThread()``` and it's works as expected (Bottom Navigation is visible after saving language).

### CODE REVIEW

**Review by gouri-panda — COMMENTED** [review]
@MohitMaliDeveloper You should try Rxjava's `ObserveOn` method and pass the main thread.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper You should try Rxjava's `ObserveOn` method and pass the main thread.

hi @gouri-panda ,
done, now you can re-review this PR.

File: app/src/main/java/org/kiwix/kiwixmobile/language/viewmodel/SaveLanguagesAndFinish.kt [hunk 1]
```diff
@@ -33,7 +33,7 @@ data class SaveLanguagesAndFinish(
 
   override fun invokeWith(activity: AppCompatActivity) {
     Flowable.fromCallable { languageDao.insert(languages) }
-      .subscribeOn(Schedulers.io())
+      .subscribeOn(AndroidSchedulers.mainThread())
```
Comment (gouri-panda) [inline app/src/main/java/org/kiwix/kiwixmobile/language/viewmodel/SaveLanguagesAndFinish.kt:36]: @MohitMaliFtechiz You should subscribe to the io thread as it is doing the database operations and you observe that on the main thread for the UI. 
```
 .subscribeOn(Schedulers.io())
 .observeOn(AndroidSchedulers.mainThread())
```

Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/language/viewmodel/SaveLanguagesAndFinish.kt]: @gouri-panda ,
done

**Review by gouri-panda — APPROVED** [review]
