### PR TITLE
Fix UI is not immediately translated (after changing UI language)

### LINKED ISSUE #3088: UI is not immediatly translated (after changing UI language)
With 3.6.0, after changing le UI language in the settings, the UI is not immediatly updated in to the newly chosen language. Only part of tge UI is updated. See for example what I see after changing (from English) to French.

Screenshot_20220924-152318

You can see part of the UI is still in English, same for the left collapsed sidebar if I woyld request it to be displayed.

Sounds like a regression to me.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3088 

The issue is when  we change language UI is not refreshing, so i have implemented ```onConfigurationChanged()``` and refresh UI component.

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt [hunk 1]
```diff
@@ -87,6 +88,24 @@ class KiwixMainActivity : CoreMainActivity() {
...
+      findItem(R.id.libraryFragment)?.title = resources.getString(R.string.library)
+      findItem(R.id.downloadsFragment)?.title = resources.getString(R.string.download)
+    }
+    drawer_nav_view?.menu?.apply {
+      findItem(R.id.menu_bookmarks_list)?.title = resources.getString(R.string.bookmarks)
+      findItem(R.id.menu_history)?.title = resources.getString(R.string.history)
+      findItem(R.id.menu_notes)?.title = resources.getString(R.string.pref_notes)
+      findItem(R.id.menu_host_books)?.title = resources.getString(R.string.menu_wifi_hotspot)
+      findItem(R.id.menu_settings)?.title = resources.getString(R.string.menu_settings)
+      findItem(R.id.menu_help)?.title = resources.getString(R.string.menu_help)
```
Comment (gouri-panda) [inline app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:104]: Instead of this, I'm sure android provided APIs to do this automatically. IMO manually updating each view isn't ideal in this case.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt [hunk 2]
```diff
@@ -185,28 +186,29 @@ class LanguageUtils(private val context: Context) {
...
         else
           Locale(language)
       Locale.setDefault(locale)
       val config = Configuration()
       config.setLocale(locale)
       config.setLayoutDirection(locale)
-      context.resources
-        .updateConfiguration(config, context.resources.displayMetrics)
+      activity.resources
+        .updateConfiguration(config, activity.resources.displayMetrics)
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt:210]: This is the same `updateConfiguration` we are accessing.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt [hunk 3]
```diff
@@ -185,28 +186,29 @@ class LanguageUtils(private val context: Context) {
...
     }
 
     @SuppressLint("AppBundleLocaleChanges")
     @JvmStatic
-    fun handleLocaleChange(context: Context, language: String) {
+    fun handleLocaleChange(activity: Activity, language: String) {
       val locale =
         if (language == Locale.ROOT.toString())
-          ConfigurationCompat.getLocales(context.applicationContext.resources.configuration)[0]
+          ConfigurationCompat.getLocales(activity.applicationContext.resources.configuration)[0]
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt:202]: It's same here also.

**Review by gouri-panda — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt (hunk 2 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt:210]: hi @gouri-panda ,

yes this is same but i have added a method which is activity method ```activity.onConfigurationChanged(config)``` and we can't access it with ```context```.

File: app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt (hunk 1 above)
Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:104]: hi @gouri-panda ,

Another way is to recreate the activity since bottom navigation bar is attached to activity not fragment and if i am going to recreate it then we will lose the state, I am not getting any better solution , let me know if you have any ?

Comment (gouri-panda) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:104]: @MohitMaliDeveloper Which state are you talking about? We are storing states in the ViewModel. How this is gonna lose?

Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:104]: hi @gouri-panda ,
i'm taking about activity ```navController``` state, if we recreate the activity then it will start from Splash Screen.

**Comment by kelson42** [comment]
@gouri-panda what is the status here? can we merge this?

**Comment by gouri-panda** [comment]
>@gouri-panda what is the status here? can we merge this?

@kelson42 I think they're still good options to solve this. But this solution works for the time if you want to merge now.

**Comment by kelson42** [comment]
@MohitMaliFtechiz @MohitMaliFtechiz OK merging as it is. I have no opinion on the details how to fix it.
