### PR TITLE
Closes opened table drawer on first back press

### LINKED ISSUE #1051: App exits on pressing back button when Navigation Drawer is open
**Describe the bug**
In Zim files, when Navigation Drawer is open, and the back button is pressed, app exits.

**Expected behavior**
Instead of exiting, drawer should close if back button is pressed once.

**Steps to reproduce the behavior:**
1. Open any Zim file.
2. Swipe left to open the drawer.
3. Press the back button. App exits.

**Screenshots**
onbackpressed

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Android 7.1 Nougat

### PR DESCRIPTION
**Pull request by sonusourav**
Fixes #1051 

Changes: 
1. Added below line in onCreate in MainActivity which will block its descendants from receiving focus.
     *drawerLayout.setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS);*

Screenshots/GIF for the change: 
closenavdrawer

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java [hunk 1]
```diff
@@ -364,6 +364,7 @@ public void onCreate(Bundle savedInstanceState) {
     searchFiles();
     tabRecyclerView.setAdapter(tabsAdapter);
     new ItemTouchHelper(tabCallback).attachToRecyclerView(tabRecyclerView);
+    drawerLayout.setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS);
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: Is it possible to move this to xml?

Comment (sonusourav) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: @abdulwd Yes, that can be done. Just wanted to know what difference will it make?

**Comment by sonusourav** [comment]
@abdulwd Could you please review this?
