### PR TITLE
#1520 Catch IllegalArgumentException

### LINKED ISSUE #1520: Crash Report 3.0.3: IllegalArgmentException FileUtils.contentQuery
**Describe the bug**
```
Caused by: java.lang.IllegalArgumentException: 

 
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:165)

 
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:135)

 
  at android.content.ContentProviderProxy.query (ContentProviderProxy.java:418)

 
  at android.content.ContentResolver.query (ContentResolver.java:816)

 
  at android.content.ContentResolver.query (ContentResolver.java:766)

 
  at android.content.ContentResolver.query (ContentResolver.java:717)

 
  at org.kiwix.kiwixmobile.utils.files.FileUtils.contentQuery (FileUtils.java:189)

 
  at org.kiwix.kiwixmobile.utils.files.FileUtils.getLocalFilePathByUri (FileUtils.java:165)

 
  at org.kiwix.kiwixmobile.main.MainActivity.manageExternalLaunchAndRestoringViewState (MainActivity.java:1891)

 
  at org.kiwix.kiwixmobile.main.MainActivity.onCreate (MainActivity.java:383)
```

**Expected behavior**
No crash

**Environment**
- Version of Kiwix Android : 3.0.3
- Device : Huawei P20 (HWEML)
- OS version : Android 9

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1520

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.kt [hunk 1]
```diff
@@ -160,19 +162,12 @@ object FileUtils {
...
-            try {
-              DocumentsContract.getDocumentId(uri).toLong()
-            } catch (ignore: NumberFormatException) {
-              0L
-            }
-          )
-        )
+      } else if ("com.android.providers.downloads.documents" == uri.authority)
+        return try {
+          documentProviderContentQuery(ctx, uri)
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.kt]: Can you replace `ctx` with `context`?
