### PR TITLE
Fixed: [Bug] Diagnostic Report not doing anything.

### LINKED ISSUE #3751: [Bug] Diagnostic Report not doing anything
**Describe the bug**

We have a option to share the diagnostic report from the help section from the Drawer. In some combinations of the selected checkboxes, we are not generating a text file(.txt), instead just generating just a string, and then it is not sharable to any source, means sharing is failed.

**Expected behavior**

It should share the string value also, or we can modify the selection combination to always generate the .txt files.

**Steps to reproduce the behavior:**
1. Opent the drawer and go to Help
2. Send diagnostic report
3. Unselect 2nd and 3rd option
4. You'll see we are sharing the string value and not a txt file
5. It will not share the thing and fail.

**Screenshots**

https://github.com/kiwix/kiwix-android/assets/85388413/e8fad77b-140e-4581-95c7-2c7f0e662148

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT
- OS version : 13

**Logs**

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3751 

* Changed intent type from `vnd.android.cursor.dir/email` to `text/plain` to ensure compatibility with all applications.
* Now attaching a log file containing all details. WhatsApp has a limitation on message sharing, so if details are lengthy, they might get cut off. We ensure complete details by providing the log file attachment.
* Improved `writeLogFile` method. Now we are deleting the directory from the storage if exist which contains the previously generated logs files since we were deleting the existing file if any are present in the storage but our fileName contains the `currentTimeMillis` so this condition will never be true, and all the logs files are stored in that directory, which takes the memory in user device, so now we are removing the previously saved log files and then generating the new one.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileLogger.kt [hunk 1]
```diff
@@ -31,26 +31,25 @@ import javax.inject.Singleton
...
+  fun writeLogFile(context: Context, shouldWriteDeviceLogs: Boolean = true): File {
     // Create a new folder in private storage with name: logs
     val logDir = File(context.filesDir, "logs")
     val logFile = File(logDir, fileName)
 
-    Log.d("KIWIX", "Writing all logs into [" + logDir.path + "]")
+    Log.d(TAG, "Writing all logs into [" + logDir.path + "]")
 
-    if (!logDir.exists()) {
+    if (logDir.exists()) {
```
Comment (Sagar0-0) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileLogger.kt:41]: Aren't we missing on the `logFile.isFile` check here?

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileLogger.kt:41]: @Sagar0-0 Thanks for reviewing. Yes, of course, We have removed that check from here because we are deleting all the log files from this folder and then creating the new file on which we are saving the current logs. Since our `fileName`  contains the `currentMiliSeconds` in it, so two file names never be gonna same so that check is never gonna true.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Any feedback here?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have made the changes in this PR which fixes the sharing on other applications like WhatsApp if the sharing `logs` option is not selected, This change does not affect the sharing on Gmail which is the main purpose of this functionality. Also, improved the previously stored file-deleting process in this PR because the previous approach was not deleting the previously stored log file and taking the memory in storage.

**Comment by kelson42** [comment]
@MohitMaliFtechiz What about the question of [Sagar0-0](https://github.com/Sagar0-0)?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have answered his question here https://github.com/kiwix/kiwix-android/pull/3752#discussion_r1524928605

**Comment by kelson42** [comment]
@MohitMaliDeveloper Very strange, you answer has never been visible for me until now! LGTM
