### PR TITLE
Hotfix: Add "no zim open" check for Add Note Dialog in case of fresh install

### LINKED ISSUE #1302: App crashes on clicking Clear All Notes
**Describe the bug**

On a fresh installation when I go to the menu and select **Clear All Notes** the app crashes.

**Steps to reproduce the behavior:**
1. Menu -> Clear All Notes

**Environment**
- Version of Kiwix Android : develop branch
- Device : Emulator Pixel 2
- OS version : API 29

**Logs**

```
2019-07-21 20:27:09.569 22494-22494/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 22494
    java.lang.RuntimeException: Unable to resume activity {org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.main.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4190)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4222)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
        at org.kiwix.kiwixmobile.main.AddNoteDialog.getTextAfterLastSlashWithoutExtension(AddNoteDialog.java:185)
        at org.kiwix.kiwixmobile.main.AddNoteDialog.getZimNoteDirectoryName(AddNoteDialog.java:164)
        at org.kiwix.kiwixmobile.main.AddNoteDialog.onCreate(AddNoteDialog.java:95)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2414)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:391)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:517)
        at org.kiwix.kiwixmobile.main.MainActivity.onResume(MainActivity.java:1535)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
        at android.app.Activity.performResume(Activity.java:7920)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4180)
```

### PR DESCRIPTION
**Pull request by Aditya-Sood**
Fixes #1302 

Changes: Added a check in `onCreate()` of Add Note Dialog for fresh installs (with no zim file opened previously)

### CODE REVIEW

**Comment by kelson42** [comment]
@Aditya-Sood Why we have a dialog here? There is just nothing to do and it does nothing.

**Comment by Aditya-Sood** [comment]
@kelson42 not sure I follow
The notekeeper is a full screen dialog fragment on top of the MainActivity - Is that what you're referring to?

**Comment by kelson42** [comment]
@Aditya-Sood Forget my remark, I think I understand now better what you have done.

File: app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java [hunk 1]
```diff
@@ -70,36 +70,51 @@
...
   private String zimFileTitle;
   private String articleTitle;
-  private String zimNoteDirectoryName;  // Corresponds to "ZimFileName" of "{External Storage}/Kiwix/Notes/ZimFileName/ArticleUrl.txt"
-  private String articleNotefileName;   // Corresponds to "ArticleUrl" of "{External Storage}/Kiwix/Notes/ZimFileName/ArticleUrl.txt"
+  // Corresponds to "ZimFileName" of "{External Storage}/Kiwix/Notes/ZimFileName/ArticleUrl.txt"
+  private String zimNoteDirectoryName;
+  // Corresponds to "ArticleUrl" of "{External Storage}/Kiwix/Notes/ZimFileName/ArticleUrl.txt"
+  private String articleNotefileName;
   private boolean noteFileExists = false;
-  private boolean noteEdited = false;   // Keeps track of state of the note (whether edited since last save)
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java]: why has the visibility of so many things changed to package instead of private?

File: app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java [hunk 2]
```diff
@@ -70,36 +70,51 @@
...
-    articleNotefileName = getArticleNotefileName();
+      zimNoteDirectoryName = getZimNoteDirectoryName();
+      articleNotefileName = getArticleNotefileName();
 
-    ZIM_NOTES_DIRECTORY = NOTES_DIRECTORY + zimNoteDirectoryName + "/";
+      ZIM_NOTES_DIRECTORY = NOTES_DIRECTORY + zimNoteDirectoryName + "/";
+    } else {
+      showToast(R.string.error_filenotfound, Toast.LENGTH_LONG);
+      closeKeyboard();
+      getFragmentManager().beginTransaction().remove(AddNoteDialog.this).commit();
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java]: the method you want is `dismiss` no need for a fragment transaction I think

File: app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java (hunk 1 above)
Comment (Aditya-Sood) [reply app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java]: They were being accessed from clickListeners of confirmation-dialog, so keeping them private caused a synthetic accessor warning
Should I revert?

File: app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java (hunk 2 above)
Comment (Aditya-Sood) [reply app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java]: This app crash occurs only if you tap 'Clear All Notes' for the very first time, that too because for some reason 'Add Note Dialog' is called (The code I wrote doesn't do that)

Probably due to this edge case nature of the crash, dismiss() didn't close the dialog - it continued with setting up the dialog

Worked with transaction, so I used it

File: app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java (hunk 1 above)
Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java]: hmmm I am considering ignoring SyntheticAccessor because with the addition of R8 our method count in release is under 30K. Continue as you are and I will start a discussion elsewhere

File: app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java (hunk 2 above)
Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java]: transactions are asynchronous I guess - unless you use `commitNow` - so it gives it enough time to be added? Odd
