### PR TITLE
Search fix

### LINKED ISSUE #2924: Search Fragment breaks on 3.6.0
**Describe the bug**
Cannot able to search , its keep showing the search screen even after click.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2924

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt [hunk 1]
```diff
@@ -140,7 +140,7 @@ class SearchViewModel @Inject constructor(
 
   private fun saveSearchAndOpenItem(searchListItem: SearchListItem, openInNewTab: Boolean) {
     _effects.offer(SaveSearchToRecents(recentSearchDao, searchListItem, zimReaderContainer.id))
-    _effects.offer(OpenSearchItem(searchListItem, openInNewTab))
+    _effects.sendBlocking(OpenSearchItem(searchListItem, openInNewTab))
```
[the remark this answers is not in the document]
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt:143]: Its necessary because we have updated the navigation lib after that offer returning false due to which search functionality breaks so its being rectify by sendBlocking. So basically its due to lib update.

File: core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt [hunk 2]
```diff
@@ -32,12 +32,12 @@ data class OpenSearchItem(
   private val openInNewTab: Boolean = false
 ) : SideEffect<Unit> {
   override fun invokeWith(activity: AppCompatActivity) {
-    activity.setNavigationResult(
+    val readerFragmentResId = (activity as CoreMainActivity).readerFragmentResId
+    activity.navigate(readerFragmentResId)
+    activity.setNavigationResultOnCurrent(
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt:37]: @MohitMaliFtechiz It's the same process that we were using previously, instead of previous we are now setting `currentBackStackEntry`. I think this problem will happen again. Am i missing something?

File: core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt (hunk 1 above)
[the remark this answers is not in the document]
Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt:143]: >the navigation lib after that offer returning false due to which search functionality breaks so its being rectify by sendBlocking.

Maybe it's the real bug we're encountering. We don't have to change the navigation order, which i talked in previous comment.

File: .github/workflows/coverage.yml [hunk 3]
```diff
@@ -37,6 +37,8 @@ jobs:
           api-level: ${{ matrix.api-level }}
           arch: x86_64
           ndk: 21.4.7075529
+          sdcard-path-or-size: '1000M'
+          disable-animations: false
```
Comment (gouri-panda) [inline .github/workflows/coverage.yml:41]: Is it necessary here?

Comment (MohitMaliFtechiz) [reply .github/workflows/coverage.yml:41]: Test on android 21 , search fragment is always failing on CI while working fine with locally by enabling the animation and placing this sdcard config make CI to work so its required for test.

File: core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt (hunk 1 above)
[the remark this answers is not in the document]
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt:143]: hi @gouri-panda , Navigation order is being changed to fix this issue **https://github.com/kiwix/kiwix-android/issues/2886**

File: core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt (hunk 2 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt:37]: hi @gouri-panda ,  Please explain  more on this while the test requirement was to start new Reader fragment  after searching the text from search fragment . Since its new reader fragment so we set all object of Bundle on it.

Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt:37]: I was saying that in the previous we set `previousNavBackStackEntry` when we first navigate and then set the value. Now we are setting `currentNavBackStackEntry` when we first set the value and then we navigate, which is basically the same. So I think the change is unnecessary.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt:37]: Hi @gouri-panda ,

It should be same but i tried previous one and that was not working , search is not working with that code, so i have change the order.

**Review by gouri-panda — APPROVED** [review]
