### PR TITLE
Properly check availability of email app

### LINKED ISSUE #3247: No check for emailing app
**Describe the bug**
There is no check for email applications like there is one already present for the browser and displays a toast if no browser is installed

**Expected behavior**
A relevant toast/snackbar is shown in case there is no emailing application

**Steps to reproduce the behavior:**
1. Disable the emailing app
2. try sending feedback

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : Emulator
- OS version : 12

**Logs**

### PR DESCRIPTION
**Pull request by criticalAY**
Fixes #3247

Placed a check for email app and show a toast accordingly

**Screenshots** 
Screenshot_58

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt [hunk 1]
```diff
@@ -88,16 +89,21 @@ abstract class HelpFragment : BaseFragment() {
...
+      data = (
+        "mailto:${Uri.encode(CONTACT_EMAIL_ADDRESS)}" +
+          "?subject=" +
+          Uri.encode("Feedback in ${getCurrentLocale(requireActivity()).displayLanguage}")
+        ).toUri()
+    }
+    val packageManager = requireActivity().packageManager
+    val activities = packageManager.queryIntentActivities(emailIntent, 0)
+    if (activities.isNotEmpty()) {
+      val chooserIntent = Intent.createChooser(emailIntent, "Send Feedback via Email")
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt:102]: Since ```chooserIntent``` is used only once, it is recommended to use it as an inline variable instead of declaring it separately in order to avoid writing an extra line of code, like we previously using.

File: core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt [hunk 2]
```diff
@@ -88,16 +89,21 @@ abstract class HelpFragment : BaseFragment() {
...
-    startActivity(Intent.createChooser(intent, "Send Feedback via Email"))
+    val emailIntent = Intent(Intent.ACTION_SENDTO).apply {
+      data = (
+        "mailto:${Uri.encode(CONTACT_EMAIL_ADDRESS)}" +
+          "?subject=" +
+          Uri.encode("Feedback in ${getCurrentLocale(requireActivity()).displayLanguage}")
+        ).toUri()
+    }
+    val packageManager = requireActivity().packageManager
+    val activities = packageManager.queryIntentActivities(emailIntent, 0)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt:100]: @criticalAY , ```queryIntentActivities(intent,int)``` is deprecated in android 13. Please use ```queryIntentActivities(intent,ResolveInfoFlags)``` to support android 13.

like 

```
 val activities = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
      packageManager.queryIntentActivities(
        emailIntent,
        PackageManager.ResolveInfoFlags.of(MATCH_DEFAULT_ONLY.toLong())
      )
    } else {
      packageManager.queryIntentActivities(
        emailIntent,
        MATCH_DEFAULT_ONLY
      )
    }
```

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@criticalAY , Thanks, Just small changes, Then we are good to go.

**Comment by criticalAY** [comment]
@MohitMaliFtechiz I also raised a ticket for the same this is not the right way to handle deprecation. I will come up with a follow-up to handle deprecation properly. For now, I will add the deprecation annotation 
The proper way would be to add a compat file and handle the deprecation there as if we move further we can simply use the new method API just by deleting the deprecated method and making no change to the code. Like here if we surpass the deprecation we will have to make changes to the code itself and from what I am suggesting we will have to make change to only one file and we will be good to go.

**Comment by MohitMaliFtechiz** [comment]
@criticalAY , We should not implement deprecated methods here, Placing deprecated code in this PR and then fixing it in another PR is not an ideal approach. Instead, we should fix this method here.

**Comment by criticalAY** [comment]
@kelson42 @MohitMaliFtechiz I have introduced a proper way that should be used to handle deprecation this way we won't have to handle deprecation at every single place and can be updated in compat files and used everywhere with ease. Plus I have introduced some other files which will be handy handling other deprecation. 
I have used this idea from AnkiDroid and it is more effective they have this system so the codebase can support even the Old API along with new one. Please take your time to go through it. Thanks!

**Comment by criticalAY** [comment]
There are a lot of places that uses "bad form" to handle the deprecation as it is not ideal to declare required api tag and placing a condition here and there

**Comment by criticalAY** [comment]
this idea is also proposed in a issue tracker of google and they are working on it https://issuetracker.google.com/issues/243986223

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV33.kt [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+const val API_33 = 33
+
+@TargetApi(API_33)
+open class CompatV33 : Compat {
+  override fun queryIntentActivities(
+    packageManager: PackageManager,
+    intent: Intent,
+    flags: ResolveInfoFlagsCompat
+  ): List<ResolveInfo> {
+    return packageManager.queryIntentActivities(
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV33.kt:35]: Please use an expression body instead of a return statement.

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+ * The old API is currently better as it means .toLong() isn't needed on constants provided
+ * to the API.
+ * For future: Can Kotlin can accept either the int or long in a `@LongDef`
+ */
+
+/**
+ * Flags class that wraps around the bitmask flags used in methods that retrieve package or
+ * application info.
+ */
+open class Flags protected constructor(val value: Long)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt:41]: this too

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt [hunk 5]
```diff
@@ -0,0 +1,153 @@
...
+
+/**
+ * Specific flags used for retrieving package info. Example:
+ * `PackageManager.getPackageInfo(packageName, PackageInfoFlags.of(0)`
+ */
+class PackageInfoFlagsCompat private constructor(@PackageInfoFlagsBits value: Long) : Flags(value) {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt:47]: What is the purpose of this class here? It appears to be unused.

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt [hunk 6]
```diff
@@ -0,0 +1,153 @@
...
+
+    // not handled: values with @SystemApi
+    // PackageManager.MATCH_FACTORY_ONLY,
+    // PackageManager.MATCH_DEBUG_TRIAGED_MISSING,
+    // PackageManager.MATCH_INSTANT,
+    // PackageManager.MATCH_HIDDEN_UNTIL_INSTALLED_COMPONENTS,
+  ]
+)
+@Retention(AnnotationRetention.SOURCE)
+annotation class PackageInfoFlagsBits
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt:153]: this too.

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt [hunk 7]
```diff
@@ -0,0 +1,164 @@
...
+    MATCH_UNINSTALLED_PACKAGES.toLong()
+    // PackageManager.MATCH_INSTANT, // @SystemApi
+    // PackageManager.MATCH_DEBUG_TRIAGED_MISSING, // deprecated
+    // PackageManager.GET_DISABLED_COMPONENTS, // deprecated
+    // PackageManager.GET_DISABLED_UNTIL_USED_COMPONENTS, // deprecated
+    // PackageManager.GET_UNINSTALLED_PACKAGES.toLong() // deprecated
+  ]
+)
+@Retention(AnnotationRetention.SOURCE)
+annotation class ResolveInfoFlagsBitsCompat
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt:164]: Please create this class in a separate file for better code quality. It is essential to keep our code clean and organised, and we should avoid putting multiple classes in a single file, including the signal class.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt (hunk 7 above)
Comment (criticalAY) [reply core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt:164]: ok

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt (hunk 5 above)
Comment (criticalAY) [reply core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt:45]: that was for `getPackageInfo` I have added and fixed this deprecation as well

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt:45]: @criticalAY, This fix is not part of this ticket. Please only include a fix for this ticket here, and include other parts in a separate PR. We should create a dedicated ticket for a particular deprecation and fix it separately. It'll be easy to track these issues this way.

**Comment by MohitMaliFtechiz** [comment]
@criticalAY, This fix is not part of this ticket. Please only include a fix for this ticket here, and include other parts in a separate PR. We should create a dedicated ticket for a particular deprecation and fix it separately. It'll be easy to track these issues this way.

**Comment by criticalAY** [comment]
@MohitMaliFtechiz I have removed the unwanted code and I will raise a new ticket once we get this PR in

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV33.kt (hunk 3 above)
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV33.kt:35]: Please use an expression body instead of a return statement.

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt [hunk 8]
```diff
@@ -0,0 +1,139 @@
...
+ * The old API is currently better as it means .toLong() isn't needed on constants provided
+ * to the API.
+ * For future: Can Kotlin can accept either the int or long in a `@LongDef`
+ */
+
+/**
+ * Flags class that wraps around the bitmask flags used in methods that retrieve package or
+ * application info.
+ */
+open class Flags protected constructor(val value: Long)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt:41]: Please make it in separate file.

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt [hunk 9]
```diff
@@ -0,0 +1,139 @@
...
+
+    // not handled: values with @SystemApi
+    // PackageManager.MATCH_FACTORY_ONLY,
+    // PackageManager.MATCH_DEBUG_TRIAGED_MISSING,
+    // PackageManager.MATCH_INSTANT,
+    // PackageManager.MATCH_HIDDEN_UNTIL_INSTALLED_COMPONENTS,
+  ]
+)
+@Retention(AnnotationRetention.SOURCE)
+annotation class PackageInfoFlagsBits
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt:139]: this class is unused here, please remove it.

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt (hunk 7 above)
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt:164]: this class too.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@criticalAY , I you revert the code as suggested in previous review. please do that changes.

**Comment by criticalAY** [comment]
@MohitMaliFtechiz done!

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt (hunk 7 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt:164]: @criticalAY , you forgot to make this class in a separate file.

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+ * along with this program. If not, see <http://www.gnu.org/licenses/>.
+ *
+ */
+
+package org.kiwix.kiwixmobile.core.compat
+
+import android.content.pm.ApplicationInfo
+import android.content.pm.PackageInfo
+import android.content.pm.PackageManager
+import androidx.annotation.LongDef
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/compat/PackageManagerCompat.kt:24]: please remove unused imports.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt (hunk 7 above)
Comment (criticalAY) [reply core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt:164]: there is an error if we don't dont declare them in same file

**Comment by criticalAY** [comment]
removed unused imports

File: core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt (hunk 7 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt:164]: we should fix this.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/compat/ResolveInfoCompat.kt:164]: > i am facing a top level declaration error while committing the code it's not shown in Android studio though

I see now that the class name is ```ResolveInfoFlagsCompat``` and the file name is ```ResolveInfoCompat```. This is why the error is occurring. To resolve it, you can either rename the file or rename the class. Either way, this should fix the issue.

**Comment by kelson42** [comment]
@criticalAY IMO this check should alos apply if there is an email address in a ZIM content, does it?

**Comment by criticalAY** [comment]
I'll look into it once I am back from my trip

**Comment by criticalAY** [comment]
@MohitMaliFtechiz @kelson42 I am back from my trip and sorry for the delay but I have made the requested changes now

**Review by MohitMaliFtechiz — APPROVED** [review]
@criticalAY , Thanks
