### PR TITLE
#1058 Revamp the menu of the History Activity

### LINKED ISSUE #1058: History is cleared even when no history is present
**Describe the bug**
In history activity, even when no history is present if the user selects clear no history, the Toast says *All history cleared*.

**Expected behavior**
The Toast should be **No history present**.

**Steps to reproduce the behavior:**
1. Open history and select Clear History from the overflow menu.
2. Once again, select Clear history.
3. Toast says **All history cleared**.

**Screenshots**
clearhistory

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Android Nougat 7.1

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #1058 

Made the following changes in the menu of the history section:
- Removed the menus
- Created an icon in the top bar to enable/disable the display of all (versus current) book/tab history
- Replace the 3 dots menu with a simple trash icon. The click on trash deletes what is displayed.

**Screenshots** 
sc
sc1
sc2
sc3

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java [hunk 1]
```diff
@@ -203,8 +203,13 @@ public boolean onOptionsItemSelected(MenuItem item) {
       onBackPressed();
       return true;
     } else if (itemId == R.id.menu_history_toggle) {
-      item.setChecked(!item.isChecked());
-      sharedPreferenceUtil.setShowHistoryCurrentBook(item.isChecked());
+      if (!sharedPreferenceUtil.getShowHistoryCurrentBook()) {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: the deleted code was more concise, I would revert to it and use the toast extension for showing a toast, using a ternary to choose the stringId eg
```
ContextExtensionsKt.toast(
this, 
item.getChecked() ? R.string.history_current_book : R.string.history_all_books,
 Toast.LENGTH_LONG);
```

That is if we keep this implementation, I am not wild on the triangle/toasts as it feels quite confusing. I'd prefer if we just showed this in the ui with a checkbox/toggle, we can keep it in or below the toolbar

File: core/src/main/res/drawable/action_delete.xml [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
+  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+  ~ GNU General Public License for more details.
+  ~
+  ~ You should have received a copy of the GNU General Public License
+  ~ along with this program. If not, see <http://www.gnu.org/licenses/>.
+  ~
+  -->
+
+<vector android:height="24dp" android:tint="#FFFFFF"
```
Comment (macgills) [inline core/src/main/res/drawable/action_delete.xml]: there is already a delete icon `ic_delete_white_24dp`

File: core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java (hunk 1 above)
Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: @macgills I made the changes according to the guidelines I saw in the issue. 
I also feel that keeping the History option should be with a checkbox. So maybe we could keep the trash icon outside the menu to make the menu more compact and leave the History option in the menu itself?
Please let me know your thoughts on this.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: I think we don't need to use the `menu` to achieve this. This actionBar is infact a toolbar and you can put arbitrary views in a toolbar. I am picturing it below the menuItems for now.

The current text is a bit annoying `History From Current Book`, by default we only show the current book's history. I wouldn't be surprised if the vast majority of our users don't know this option to see all history exists and I think that better explains what it is.
"View All History" or the more verbose "View All Books History" I think would be good options for the name of this checkbox/toggle. It is difficult to convey what it does concisely so I am open to suggestions. I am personally leaning more towards toggle but follow your heart.

Trash/Search icon should definitely remain in the menu

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: I will update the pr with a better UI by tomorrow.
Thanks a lot for the suggestions :)

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: @macgills I am changing the title of the option so that it's described better. I think the existing checkbox is doing a good job as we intend on keeping this item in the menu itself. 
Regarding the clear history option, I'm making it in such a way that it will be visible only when historyList is not empty. If the historyList is empty, the option to clear history will also be made invisible.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: I have concern about it still being in the menu because of how hidden it is in the overflow, the sheer size of the text+checkbox make it difficult to fit in the actionBar with any extra icons present so constantly expanded also doesn't seem great. That is what lead me to placing in the toolbar, if that poses a challenge then above the list would also be fine I think

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: @macgills I am not very clear as to how to put the option in the toolbar. I am not able to figure out how to place this option under the menu items.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: image
 place your cursor on `<include layout="@layout/layout_standard_app_bar" />`
and press `ctrl+alt+n`, select `inline this usage`

This will give you the appbar that contains the toolbar, we don't actually need to put the view in the toolbar, apologies for misleading you.

Obviously there are some styling issues with this solution, it looks like [this answer](https://stackoverflow.com/a/58749611/12225251) is a good starting point for making the background themed dark or seeing as how this is the first time we are styling an AppBar I'll allow in file styling

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: Thanks for help @macgills :) 
I'll just update the pr as per these guidelines.

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java]: I'll make the same changes in the bookmarks section too since it the same feature.

**Comment by yashk2000** [comment]
@macgills I have made the changes. Please review.

File: core/src/main/res/layout/activity_history.xml [hunk 3]
```diff
@@ -5,7 +5,23 @@
...
+  <com.google.android.material.appbar.AppBarLayout xmlns:tools="http://schemas.android.com/tools"
+    android:id="@+id/app_bar"
+    android:layout_width="match_parent"
+    android:layout_height="wrap_content"
+    app:layout_constraintTop_toTopOf="parent"
+    tools:showIn="@layout/activity_help">
+
+    <include layout="@layout/layout_toolbar" />
+
+    <Switch
```
Comment (macgills) [inline core/src/main/res/layout/activity_history.xml]: this might look better aligned right?
There needs to be padding around this view
The AppBar backgroundColor should be the same as the Toolbar ie black

Comment (yashk2000) [reply core/src/main/res/layout/activity_history.xml]: @macgills done.

Comment (macgills) [reply core/src/main/res/layout/activity_history.xml]: I meant move it to the right of the screen, the switch is next to invisible on the dark background and it needs more padding around the view, the bottom of the appbar is too close to the switch.
You should try styling the switch with a theme, see if `app:theme="@style/ThemeOverlay.MaterialComponents.Dark` works

Comment (yashk2000) [reply core/src/main/res/layout/activity_history.xml]: On it.

Comment (macgills) [reply core/src/main/res/layout/activity_history.xml]: Also the trash icon is not visible

Comment (macgills) [reply core/src/main/res/layout/activity_history.xml]: There are also lint errors
```
  /home/runner/work/kiwix-android/kiwix-android/core/src/main/res/layout/activity_history.xml:23: Error: To support older versions than API 17 (project specifies 15) you should also add android:paddingLeft="@dimen/switch_text_padding" [RtlCompat]
212
        android:paddingStart="@dimen/switch_text_padding"
213
        ~~~~~~~~~~~~~~~~~~~~
214
  /home/runner/work/kiwix-android/kiwix-android/core/src/main/res/layout/activity_history.xml:23: Error: When you define paddingStart you should probably also define paddingEnd for right-to-left symmetry [RtlSymmetry]
215
        android:paddingStart="@dimen/switch_text_padding"
216
        ~~~~~~~~~~~~~~~~~~~~
```
when committing do not bypass githooks, they are there to let you know a PR will fail at this step.

Comment (yashk2000) [reply core/src/main/res/layout/activity_history.xml]: @macgills Is it fine now?
sc

Comment (macgills) [reply core/src/main/res/layout/activity_history.xml]: there shouldn't be that much space between the text of the switch and the actual switch, use `android:layout_gravity="end"` and that should produce the result I am looking for

Comment (macgills) [reply core/src/main/res/layout/activity_history.xml]: But excellent, it looks like the dark theme worked there, you can probably remove the textColor attribute now as the ThemeOverlay should be contributing it

Comment (yashk2000) [reply core/src/main/res/layout/activity_history.xml]: Ok. 
I thought we just wanted the switch part to go to the end. Apologies for interpreting it in the wrong way. I'll fix it right now.

Comment (yashk2000) [reply core/src/main/res/layout/activity_history.xml]: @macgills is it fine now?
sc

Comment (macgills) [reply core/src/main/res/layout/activity_history.xml]: The search/delete icons aren't present in that image? But it is looking pretty good. Touch more padding on the bottom and to the right.
Also whenever we show txt we should use `android:textAppearance=?textAppearance*` where `*` should be one of the following
```
<!--Material type attributes-->
    <item name="textAppearanceHeadline1">@style/TextAppearance.KiwixTheme.Headline1</item>
    <item name="textAppearanceHeadline2">@style/TextAppearance.KiwixTheme.Headline2</item>
    <item name="textAppearanceHeadline3">@style/TextAppearance.KiwixTheme.Headline3</item>
    <item name="textAppearanceHeadline4">@style/TextAppearance.KiwixTheme.Headline4</item>
    <item name="textAppearanceHeadline5">@style/TextAppearance.KiwixTheme.Headline5</item>
    <item name="textAppearanceHeadline6">@style/TextAppearance.KiwixTheme.Headline6</item>
    <item name="textAppearanceSubtitle1">@style/TextAppearance.KiwixTheme.Subtitle1</item>
    <item name="textAppearanceSubtitle2">@style/TextAppearance.KiwixTheme.Subtitle2</item>
    <item name="textAppearanceBody1">@style/TextAppearance.KiwixTheme.Body1</item>
    <item name="textAppearanceBody2">@style/TextAppearance.KiwixTheme.Body2</item>
    <item name="textAppearanceButton">@style/TextAppearance.KiwixTheme.Button</item>
    <item name="textAppearanceCaption">@style/TextAppearance.KiwixTheme.Caption</item>
    <item name="textAppearanceOverline">@style/TextAppearance.KiwixTheme.Overline</item>
```
more info [here](https://material.io/design/typography/the-type-system.html#type-scale)

Comment (yashk2000) [reply core/src/main/res/layout/activity_history.xml]: @macgills Since there is no history in the screenshot I took, the search and delete icons are not visible. When history is there, the icons will be present.
I'll make changes to the text appearance.

Comment (yashk2000) [reply core/src/main/res/layout/activity_history.xml]: @macgills made the changes. 
Also putting in a screenshot of how it looks when history is present.
sc

Comment (macgills) [reply core/src/main/res/layout/activity_history.xml]: We want to get rid of the overflow menu when we have enough space, in the menu.xml use `IfRoom` for the delete icon instead of never, also supply the trash icon

Comment (yashk2000) [reply core/src/main/res/layout/activity_history.xml]: @macgills done :rocket:

Comment (macgills) [reply core/src/main/res/layout/activity_history.xml]: Thanks for all the hard work

**Comment by yashk2000** [comment]
@macgills thanks for reviewing and helping throughout :grin:
