### PR TITLE
Fixed bottom view lost issue

### LINKED ISSUE #3407: BottomNavigationView does not reappear
**Describe the bug**

There is a scenario where the bottom navigation view completely disappears / never re enter's again / not available for the user.

**Expected behavior**

The bottom navigation view shouldn't disappear and should be available to the user for navigation always.

**Steps to reproduce the behavior:**
1. Navigate to library screen
2. Have at most items/books where the scrolling behaviour of the bottom view is just enabled (5 items in my case).
3. Delete an item when the bottom navigation view is scrolled away
4. Bottom navigation view is lost ;( , hence user cannot navigate.

**Reason**
If we delete an item when the bottom view is scrolled away and the scrolling of the recycler view is disabled/stopped due to less no of items ,the bottom view cannot come back / re enter

**Screen Recording**

https://github.com/kiwix/kiwix-android/assets/111702455/1e378d17-c750-4617-ac25-2de43522f2ad

**Environment**
- Version of Kiwix Android : 3.7.1 develop version
- Device : Realme 3i
- OS version : 10

### PR DESCRIPTION
**Pull request by shashank-0-0**
Fixes #3407 

**Issue**
Scenario / workflow  where bottom view is lost 

**Approach**
The bottom view animated back to it's original position when the user proceeds to delete item/s i.e. when the delete action is detected.

* Observed for the "RequestDeleteMultiSelection" action.

* Set the translationY of the bottom view to 0F which resets the vertical translation of the view to it's original position . Also animated it to a duration of 225L which is the default behaviour of the *HideBottomViewOnScrollBehaviour* of the material bottom view ,making sure consistent reappearing behaviour. 
Screenshot (513)

**Result** 

https://github.com/kiwix/kiwix-android/assets/111702455/07de4e83-4755-4bea-8efd-831d758c9983

@kelson42 This is ready to be reviewed

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt [hunk 1]
```diff
@@ -334,6 +336,23 @@ class LocalLibraryFragment : BaseFragment() {
       }, Throwable::printStackTrace
     )
 
+  private fun fileSelectActions() = zimManageViewModel.fileSelectActions
+    .observeOn(AndroidSchedulers.mainThread())
+    .filter { it === FileSelectActions.RequestDeleteMultiSelection }
```
Comment (MohitMaliFtechiz) [inline app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt:341]: * Why we are using `===`? 
* Please directly import `RequestDeleteMultiSelection` to maintain the code flow like we are importing for other actions as shown in the below code snippet.

```
private val bookDelegate: BookOnDiskDelegate.BookDelegate by lazy {
    BookOnDiskDelegate.BookDelegate(
      sharedPreferenceUtil,
      { offerAction(RequestNavigateTo(it)) },
      { offerAction(RequestMultiSelection(it)) },
      { offerAction(RequestSelect(it)) }
    )
  }
  ```

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@shashank-0-0 Thanks for fixing the issue, just need some small changes then we are good to go.

**Comment by MohitMaliFtechiz** [comment]
Please rebase the PR as well.

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt (hunk 1 above)
Comment (shashank-0-0) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt:341]: > * Why we are using `===`?

@MohitMaliFtechiz I thought it would be efficient to use referential equality for comparison than using '==' since RequestDeleteMultiSelection is an object instance.
Is it correct?

Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt:341]: Okay, Please fix the other part of the request changes.

**Review by MohitMaliFtechiz — APPROVED** [review]
@shashank-0-0  Thanks :tada: :tada: LGTM.
