### PR TITLE
1885 fixes search from widget and text selection from entering infinite activity restarting loop

### LINKED ISSUE #1885: When using kiwix search from selected text, no button works in the search activity.
**Describe the bug**

When selecting text from a zim file, a sub menu appears. By clicking on 'Search Kiwix' in this submenu the search activity is started. This opened search activity is impossible to exit without restarting the application entirely. 

**Expected behavior**

I don't actually know what the 'Search Kiwix' sub-menu button should do. Perhaps it should open the search activity with the selected text inserted into the search field? Or maybe it should be completely removed. 

**Steps to reproduce the behavior:**
1. Open a zim file.
2. Select arbritary text.
3. Choose the 'Search Kiwix' option from the expandable '...'.
4. Try exiting this view by using any of the back buttons or the search button. 

**Screenshots**

https://imgur.com/a/JAMamPO

**Environment**
- Version of Kiwix Android : 3.2.1 Build 6230201
- Device : Tested on OnePlus 5 (Physical) and Pixel 2 (Virtual)
- OS version : 9.0.10 OxygenOS for OnePlus 5 and Android 10.0 for the Pixel 2

**Logs**

https://pastebin.com/XziRrPmh

### PR DESCRIPTION
**Pull request by Frans-Lukas**
Fixes #1885 

The 'Search Kiwix' menu item from the text-selection menu now enters the Search Activity correctly. This also fixes the Search Widget from entering an infinite loop if the app is closed when the widget is called. This fix was done by moving the intent handling from onResume to onCreate and the onNewIntent method. 

We should discuss the use of the Search Widget as I am unsure of its intended purpose. Currently the search widget opens the app without going to the search activity if the app is currently closed. If the app is open in the background, the search widget opens the search activity with the currently opened book/zim file.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 1]
```diff
@@ -50,6 +50,7 @@
 import android.widget.ImageView;
 import android.widget.LinearLayout;
 import android.widget.Toast;
+
```
Comment (yashk2000) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Could you please remove these extra blank lines that have been inserted? There's no need for them.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 2]
```diff
@@ -255,21 +263,21 @@ public void onFinish() {
   private ItemTouchHelper.Callback tabCallback = new ItemTouchHelper.Callback() {
     @Override
     public int getMovementFlags(@NonNull RecyclerView recyclerView,
-      @NonNull RecyclerView.ViewHolder viewHolder) {
+                                @NonNull RecyclerView.ViewHolder viewHolder) {
```
Comment (yashk2000) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: I think these extra indentation changes can be removed too. They aren't needed and are not related to the issue that is being fixed.

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Agreed, will undo!

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 3]
```diff
@@ -400,8 +400,15 @@ public void onSwipeRight() {
     searchFiles();
     tabRecyclerView.setAdapter(tabsAdapter);
     new ItemTouchHelper(tabCallback).attachToRecyclerView(tabRecyclerView);
+
+    // Only check intent on first start of activity. Otherwise the intents will enter infinite loops
+    // when "Don't keep activities" is on.
+    if (savedInstanceState == null) {
+      handleIntentActions(getIntent());
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: I feel like this could be a source of errors. Turn on "Don't keep activities", open a book, go to library, press device home button, use search shortcut

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 4]
```diff
@@ -1114,7 +1111,7 @@ private boolean hasPermission(String permission) {
   private void requestExternalStoragePermission() {
     ActivityCompat.requestPermissions(
       this,
-      new String[] { Manifest.permission.READ_EXTERNAL_STORAGE },
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: These spaces should not have changed, have you tried reformatting the file with `ctrl+alt+l`?

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: That is what I did originally, which I tried to undo in my last commit. Will fix!

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java (hunk 3 above)
Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: (While having "Don't keep activities" active) By opening a book, going back to the library, pressing the device home button and using the search widget shortcut the app opens into the search activity with the opened book. I agree that it could be a source of bugs, but I can't find any of them yet. When `savedInstanceState != null`, the activity is guaranteed to have been re-initialized from a previously saved state. [[1](https://developer.android.com/reference/android/app/Activity#onRestoreInstanceState(android.os.Bundle))] When `savedInstaceState == null`, I can't find any guarantee for the activity to be freshly started.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java (hunk 4 above)
Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Move it back to one line, press `ctrl+alt+l` again and see if it is being a moody git.

My formatter doesn't make any noise about it so make sure you have no changes to the codestyle file under the `idea` folder

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java (hunk 3 above)
Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Ah well that wasn't what I was expecting, that is a good outcome. 

This is a fair sight better than it was so I'll take it

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java (hunk 4 above)
Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: I meant what @yashk2000 mentioned. That all formatting should be undone because it is not relevant to the issue. I tried removing the formatting done in #1885 Some refactoring for easier overview of handleIntentActions method with the latest commit. `ctrl + alt + l` is working but I undid it because it was requested.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: We all share the same formatter, your formatter shouldn't be changing things if mine isn't.

Currently there are spaces around the `{ }` and I don't want that to change.

All files in the project are correctly formatted so if you run the formatter and some line you haven't touched changes its formatting then this points to an issue on your end

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: I have `format,optimise,indent,save all` all bound to a macro bound to `ctrl+s` and I hit that probably every 20 seconds out of insane habit

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: ah, ok. I'll look into it. Thanks for clarifying. Binding those to ctrl+s seems nice!

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Alright, I had to manually set the style to SquareAndroid.. Now it should be correct!

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: The project style is imported automatically, it is in git in our repo under the `idea` folder. This is quite confusing

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: @macgills Might be with how I imported the project. I believe I imported the Core module only, which works but it might have missed things such as the stylings.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: hmm maybe re-import the whole thing but as long as your codestyle doesn't conflict it should be okay
