### PR TITLE
#3668 Ripple in Tabs Icon

### LINKED ISSUE #3668: Tabs Icon Ripple and Title
**Describe the bug**

The tab icon in the Reader is not having a ripple effect and a title which is bad for accessibility.

**Expected behavior**

Add Ripple and title/desciption

**Steps to reproduce the behavior:**
1. Open the reader
2. See in the topbar
-->

**Screenshots**

photo_6131796836109891986_y

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT NEO 3T
- OS version : 13

**Logs**

### PR DESCRIPTION
**Pull request by Sagar0-0**
Fixes #3668 

Added background for ripple

**Screenshots** 
photo_6183602761699014675_y

### CODE REVIEW

**Comment by Sagar0-0** [comment]
@kelson42 @MohitMaliFtechiz I am not able to add a reviewer to this PR, so asking for it here.

**Review by MohitMaliFtechiz — APPROVED** [review]
Thanks :tada:

**Review by gouri-panda — COMMENTED** [review]
@Sagar0-0 Thanks 🎉 But  I can't think why I can't  access the PR.  But I think it's only affect in the tab switcher not the entire tab bar.
Screenshot 2024-02-01 at 19 53 00

**Comment by Sagar0-0** [comment]
Can you explain me further regarding the expected behaviour and how it is different from current implementation?

**Comment by MohitMaliFtechiz** [comment]
>  But I can't think why I can't access the PR.

@gouri-panda It is a fork. You can do one thing, clone the Sagar's repo, and then you can access this PR.

> But I think it's only affect in the tab switcher not the entire tab bar which the ticket was created for.
Can you explain me further regarding the expected behaviour and how it is different from current implementation?



@Sagar0-0, @gouri-panda pointing to fix the full tab behavior, however, this ticket is only for the `tab icon` in toolbar. But @gouri-panda is right, we should fix the whole behavior of the tab in this PR. @Sagar0-0 Please add the title on the close all tab button, and add the ripple effect and title to the `close image` of the `recycler view` item.

**Comment by Sagar0-0** [comment]
On it

**Comment by Sagar0-0** [comment]
`setHomeActionContentDescription("Add")` is not working, got any idea why?

**Comment by Sagar0-0** [comment]
LGTM
photo_6188071962933312341_y
photo_6188071962933312340_y
photo_6188071962933312339_y

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.kt [hunk 1]
```diff
@@ -65,6 +68,14 @@ class TabsAdapter internal constructor(
       .apply {
         id = R.id.tabsAdapterCloseImageView
         setImageDrawableCompat(R.drawable.ic_clear_white_24dp)
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
+          TooltipCompat.setTooltipText(this, "Close Tab")
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.kt:72]: Please don't hardcode the string in the code, move this to the string file and use this from there.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt [hunk 2]
```diff
@@ -98,7 +100,14 @@ class MainMenu(
       else
         MenuItem.SHOW_AS_ACTION_NEVER
     )
-    tabSwitcher?.actionView?.setOnClickListener { menuClickListener.onTabMenuClicked() }
+    tabSwitcher?.actionView?.apply {
+      setOnClickListener { menuClickListener.onTabMenuClicked() }
+      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt:105]: We are using this code in multiple places, we should make an extension function for this and use that everywhere.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt [hunk 3]
```diff
@@ -764,9 +765,16 @@ abstract class CoreReaderFragment :
...
     toolbar?.let(::setUpDrawerToggle)
     setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED)
-    closeAllTabsButton?.setImageDrawable(
-      ContextCompat.getDrawable(requireActivity(), R.drawable.ic_close_black_24dp)
-    )
+    closeAllTabsButton?.apply {
+      setImageDrawable(
+        ContextCompat.getDrawable(requireActivity(), R.drawable.ic_close_black_24dp)
+      )
+      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:772]: The title is not showing when I am long clicking on the `close All tabs` button. You should set this in `showTabSwitcher()` method instead of `hideTabSwitcher()`.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt (hunk 3 above)
Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:772]: >The title is not showing when I am long clicking on the close All tabs button.
 
@Sagar0-0 Me too! Please be carefull. Please let us know if you don't understand any part of the code.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt (hunk 2 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt:105]: Please elaborate more about the location, which class, and param.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt (hunk 3 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:772]: Which API level you're testing on? I can see the title PFA SS, I tested on 33.

Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:772]: For other changes can you see the titles?

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt (hunk 2 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt:105]: You should create the extension function in the `ViewExtension` class with the string param.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt (hunk 3 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:772]: @Sagar0-0 I have tested it on three different devices. 
1. API level 32.
2. API level 34.
3. API level 31.

On these devices title is not showing for this. However, if you put this in `showTabSwitcher` then it will work because this is the right place where you should put this code.

> For other changes can you see the titles?

yes we can see the title for other changes.

> Which API level you're testing on? I can see the title PFA SS, I tested on 33.

I don't know how you can see the title, but you are putting the code in the wrong place. 
`hideTabSwitcher` is used when we close the tabs, and `showTabSwitcher` is used when we are showing the tabs.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.kt (hunk 1 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.kt:72]: How to add, its showing this error : "close_tab" is translated here but not found in default locale

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt (hunk 2 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt:105]: setContentDescription is already a view function, so I am adding setToolTip

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.kt (hunk 1 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.kt:72]: Fixed it by Clean > Invalidate n Restart

**Comment by gouri-panda** [comment]
@Sagar0-0 Please don't mark conservation as resolved yourself. Only those who created should close these.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt [hunk 4]
```diff
@@ -764,9 +766,11 @@ abstract class CoreReaderFragment :
     }
     toolbar?.let(::setUpDrawerToggle)
     setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED)
-    closeAllTabsButton?.setImageDrawable(
-      ContextCompat.getDrawable(requireActivity(), R.drawable.ic_close_black_24dp)
-    )
+    closeAllTabsButton?.apply {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:769]: Revert this change as it is not relevant to this fix.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt [hunk 5]
```diff
@@ -929,22 +933,27 @@ abstract class CoreReaderFragment :
         hideTabSwitcher()
         return FragmentActivityExtensions.Super.ShouldNotCall
       }
+
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:936]: Why have you added these spaces that are not relevant to this PR? Please revert these changes.

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt [hunk 6]
```diff
@@ -69,3 +71,11 @@ fun View.snack(
     })
   }.show()
 }
+
+fun View.setToolTip(description: String) {
+  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
+    TooltipCompat.setTooltipText(this, description)
+  } else {
+    contentDescription = description
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:79]: @Sagar0-0 This code is not working with API level 24. It does not show any title while long clicking on the close all tabs button. However, `TooltipCompat.setTooltipText(this, description)` this method automatically handles the for both above and below API level 26. You should use this method it will handle the backward compatibility.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt (hunk 5 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:936]: It was showing a lint error to me, should I keep it?

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:936]: Okay, I got it, it is showing a white space error, Keep these changes it would lead to lint failure in future in updated gradle version.

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt (hunk 6 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt]: Resolved

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt [hunk 7]
```diff
@@ -69,3 +70,7 @@ fun View.snack(
     })
   }.show()
 }
+
+fun View.setToolTip(description: String) {
+  TooltipCompat.setTooltipText(this, description)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:75]: @Sagar0-0 Since it is a single-line code, and we can directly use it. So we don't need to make the extension for this.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
Just a small change needed, then we are good to merge.

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt (hunk 7 above)
Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:75]: Yes, I agree, we don't NEED it. But, IMO with this function present, we can avoid the same mistakes for future contributors, like using contentDescription or using toolTip field which is not backward compatible. This function can give a consistent approach to others for exactly what they need to do. What are your thoughts on this?

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:75]: This function does not have any clue that `contentDescripton` is not working as expected, and devs can know about this through git history or by checking the implementation of these views that how we achieved this when they will try to implement this. Please put the necessary comments while using this method.

Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:75]: > Please put the necessary comments while using this method.
1. Are we expected to use comments in all places where ever we are using this function?
2. And will it solve the issue you mentioned?
3. Is there any better alternative to using this extension function, like overriding the contentDescription or toolTip field of views?

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:75]: We should not make an extension for this since we are not adding something extra to the extension function we are just simply calling this function which is just a single line code, so it does not make sense to create an extension function for this. `contentDescripton` works in most of the cases except here I have not researched why it is not working here but might be there is some backward compatibility issue while setting this on toolbar's views etc (Have you researched about it?). So you should add comments where you use this function.

Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:75]: I am getting some unexpected build failure and am not able to commit, I tried to clean project and Invalidate the cache, previously also I faced this issue, is there any general solution?

Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:75]: There is one generated file in build package that can not be deleted because it is being used by the Java(TM) Platoform SE binary.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:75]: What error you are facing? can you please provide the log so that I can assist you?

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt:75]: > There is one generated file in build package that can not be deleted because it is being used by the Java(TM) Platoform SE binary.

If you run the `./gradlew clean` command whole build folder will be delete.

Comment (Sagar0-0) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt]: Today, it was deleted on its own, It was a cache issue only which was causing the commit to fail. Please check now and let me know if any other changes are required.

**Review by MohitMaliFtechiz — APPROVED** [review]
@Sagar0-0 Thanks :tada:, @kelson42 LGTM.
