### PR TITLE
Fixes of test failing on android 13(API level 33) with google_apis(System image) emulator

### LINKED ISSUE #3189: Test failing on android 13(API level 33) with google_apis(System image) emulator
**Describe the bug**
Test failing on ```android 13(API level 33)``` with ```google_apis(System image)``` emulator on CI.

**Steps to reproduce the behaviour:**
* Remove this condition from test cases and make a PR.
```
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
}
```

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : on CI
- OS version : Android 13

For now ```default_apis(System image)``` is not available for android 13. Since ```google_apis``` is heavy compare to ```default_apis``` because it contains extra things to run google services.

**What i have tried for solve this problem**
* Removed deprecated ```ActivityTestRule```([More Information about deprecation](https://developer.android.com/reference/androidx/test/rule/ActivityTestRule)) and added ```ActivityScenarioRule``` for test cases.
* Upgraded test dependencies to stable android 13 emulator.

| Dependency | From | To |
| :---         |     :---:      |     :---:      |
|  androidx.test:rules  |   1.4.0   | 1.5.0  |
|  androidx.test:runner  |   1.4.0   | 1.5.1  |
|  androidx.test:core  |   1.5.0-alpha02   | 1.5.0  |
|  androidx.test:rules  |   1.5.0-alpha02   | 1.5.0  |
|  androidx.test.espresso:espresso-web  |   3.4.0   | 3.5.0  |
|  androidx.test.espresso:espresso-intents  |   3.4.0   | 3.5.0  |
|  androidx.test.espresso:espresso-core  |   3.4.0   | 3.5.0  |
|  androidx.test.espresso:espresso-contrib  |   3.4.0   | 3.5.0  |
|  org.junit.jupiter:junit-jupiter  |   5.7.0   | 5.9.1  |
|  androidx.test.ext:junit  |   1.1.2   | 1.1.4  |

* Since ```google_apis``` heavy i have increased ram size to 8GB.
* I have tried to run all ```target(Api levels)``` with ```google_apis``` only ```android 21``` is working fine. Api level 33(android 13), 30(android 11) both are failing with ```google_apis``` in CI.

**Note**
All test cases are passed in local emulator(android 13).

All these changes are here https://github.com/kiwix/kiwix-android/pull/3182

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3189 

* Fixed the `DownloadTest` which is failing on `Android 13` due to the `NotificationPermission` permission dialog being visible on the window so we have placed a condition if the test cases are running then it will not ask for `Notification permission`.
* `NetworkTest` is broken for now and we have ignored but somehow it is giving an error on this test in `Android 13`. so we have placed a fix here for this error.
```
04-28 08:50:12.166  5954  6406 E TestRunner: failed: initializationError(org.kiwix.kiwixmobile.NetworkTest)
04-28 08:50:12.166  5954  6406 E TestRunner: ----- begin exception -----
04-28 08:50:12.172  6071  6104 I FontLog : Received query Noto Color Emoji Compat, URI content://com.google.android.gms.fonts [CONTEXT service_id=132 ]
04-28 08:50:12.174  6071  6104 I FontLog : Query [Noto Color Emoji Compat] resolved to {Noto Color Emoji Compat, wdth 100.0, wght 400, ital 0.0, bestEffort false} [CONTEXT service_id=132 ]
04-28 08:50:12.183  5954  6406 E TestRunner: java.lang.RuntimeException: Failed to instantiate test runner class androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner
04-28 08:50:12.183  5954  6406 E TestRunner: 
04-28 08:50:12.183  5954  6406 E TestRunner: 
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.throwInitializationError(AndroidJUnit4.java:129)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.loadRunner(AndroidJUnit4.java:121)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.loadRunner(AndroidJUnit4.java:82)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.<init>(AndroidJUnit4.java:56)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.internal.runner.junit4.AndroidAnnotatedBuilder.runnerForClass(AndroidAnnotatedBuilder.java:63)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:149)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.internal.runner.AndroidLogOnlyBuilder.runnerForClass(AndroidLogOnlyBuilder.java:93)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.internal.runner.ScanningTestLoader.doCreateRunner(ScanningTestLoader.java:50)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:64)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:835)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:650)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:418)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2361)
04-28 08:50:12.183  5954  6406 E TestRunner: Caused by: java.lang.reflect.InvocationTargetException
04-28 08:50:12.183  5954  6406 E TestRunner: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.loadRunner(AndroidJUnit4.java:112)
04-28 08:50:12.183  5954  6406 E TestRunner: 	... 17 more
04-28 08:50:12.183  5954  6406 E TestRunner: Caused by: org.junit.runners.model.InvalidTestClassError: Invalid test class 'org.kiwix.kiwixmobile.NetworkTest':
04-28 08:50:12.183  5954  6406 E TestRunner:   1. The @Rule 'mActivityTestRule' must be public.
04-28 08:50:12.183  5954  6406 E TestRunner:   2. The @Rule 'readPermissionRule' must be public.
04-28 08:50:12.183  5954  6406 E TestRunner:   3. The @Rule 'writePermissionRule' must be public.
04-28 08:50:12.183  5954  6406 E TestRunner: 	at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:92)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:74)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner.<init>(AndroidJUnit4ClassRunner.java:43)
04-28 08:50:12.183  5954  6406 E TestRunner: 	at androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner.<init>(AndroidJUnit4ClassRunner.java:48)
04-28 08:50:12.183  5954  6406 E TestRunner: 	... 20 more
04-28 08:50:12.185  5954  6406 E TestRunner: ----- end exception -----
```

* For the `KiwixSplashActivityTest` in `Android 13` we can not directly use the `BaristaSleepInteractions.sleep(TestUtils.TEST_PAUSE_MS.toLong())` on the main thread so we have moved it from main thread.
* For the `KiwixSplashActivity` `testNormalRun()` which is failing due to `Wanted to match 1 intent. Actually matched 0 intents)`
* Since `google_apis` emulators are heavy, we have increased the heap size and sd card size to 4GB for the Android 13 emulator.
* Increased delay in some test cases for better test performance.
* Sometimes some system dialog is visible on the window for this reason `espresso` and `UiObject` are unable to find views on the window so we have placed a check in test cases if any system dialog is visible on the window then first it will close it and after that run the test cases.
* We have upgraded some test dependencies to support the latest API.
   * Upgraded `espresso-contrib` dependency from `3.3.0` to `3.5.1`.
   * Upgraded `espresso-core` dependency from `3.5.0` to `3.5.1`.
   * Upgraded `espresso-intents` dependency from `3.5.0` to `3.5.1`.
   * Upgraded `espresso-web` dependency from `3.5.0` to `3.5.1`.
   * Upgraded `barista` dependency from `4.0.0` to `4.3.0`.
   * Upgraded `mockk` dependency from `1.13.4` to `1.13.5`.
   * Upgraded `uiautomator` dependency from `2.2.0` to `2.3.0-alpha03`.

### CODE REVIEW

File: app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt [hunk 1]
```diff
@@ -71,34 +77,32 @@ class DownloadTest : BaseActivityTest() {
 
   @Test
   fun downloadTest() {
-    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
-      ActivityScenario.launch(KiwixMainActivity::class.java)
```
Comment (gouri-panda) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt:75]: Finally, we are removing this :)

**Review by gouri-panda — APPROVED** [review]
@MohitMaliDeveloper I've tested all the code with the physical device & simulator. It works fine. Hopefully, all the flaky tests will be fine in ci from now :)
