### PR TITLE
Fixes date issues with history

### LINKED ISSUE #1062: Date issues in History with orientation change
**Describe the bug**
The date format in History screen changes with a change in orientation.  (March 5, 2019 --> 05-March 2019). Even multiple headings of the same date are formed on orientation change. 

**Expected behavior**
1. Date format should not change with orientation.
2. Multiple heading should not be formed.
3. (Optional) If a page is visited multiple times, history should be written for each time. (Similar to Google Chrome)

**Steps to reproduce the behavior:**
1. Open any one page of Zim file.
2. Open history and observe date format.
3. Go back and once again open the same page of Zim file but in other orientation.
4. Observe the difference.

P.S. Took me 2 hours just to figure out the reproduction steps after I observed the bug.

**Screenshots**
dateinhistory

Mutiple headings:

history

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Android 7.1

### PR DESCRIPTION
**Pull request by sonusourav**
Fixes #1062 

Changes:
1. Added `SimpleDateFormat` to have a uniform date format.
2. Handled screen orientation by adding `onSavedInstanceState` and `onRestoreInstanceState` in history activity.

Screenshots/GIF for the change: 
dateformat

### CODE REVIEW

**Comment by sonusourav** [comment]
@abdulwd @mhutti1 @siddharth2010  Please review.

File: app/src/main/java/org/kiwix/kiwixmobile/history/HistoryAdapter.java [hunk 1]
```diff
@@ -60,7 +63,9 @@ public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int positi
       item.itemView.setOnLongClickListener(v ->
           itemClickListener.onItemLongClick(item.favicon, history));
     } else {
-      ((Category) holder).date.setText(historyList.get(position + 1).getDate());
+      SimpleDateFormat format = new SimpleDateFormat("d MMM yyyy", Locale.US);
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/history/HistoryAdapter.java]: Firstly, the date must be formatted using the current locale. Secondly, you should format the date before inserting it in the DB so you don't have to format it after retrieving it from the DB. https://github.com/kiwix/kiwix-android/blob/fe668abde73159961f4468d72966ba6871c7bde0/app/src/main/java/org/kiwix/kiwixmobile/data/local/dao/HistoryDao.java#L29

Comment (sonusourav) [reply app/src/main/java/org/kiwix/kiwixmobile/history/HistoryAdapter.java]: @abdulwd I have done the changes. Please review this.

File: app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java [hunk 2]
```diff
@@ -111,15 +116,34 @@ protected void onCreate(Bundle savedInstanceState) {
...
     super.onResume();
     presenter.loadHistory(sharedPreferenceUtil.getShowHistoryCurrentBook());
+    if (listState != null) {
+      layoutManager.onRestoreInstanceState(listState);
+    }
+  }
+
+  protected void onSaveInstanceState(Bundle state) {
+    super.onSaveInstanceState(state);
+    // Save list state
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java]: It's good to have a well commented and well-documented code but it is not desirable to have comments on everything we do. In this case, the functionality is obvious from the name of the method. You should probably remove these comments.

Comment (sonusourav) [reply app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java]: @abdulwd  Comments removed.

File: app/src/main/java/org/kiwix/kiwixmobile/data/local/dao/HistoryDao.java [hunk 3]
```diff
@@ -24,8 +24,7 @@
   }
 
   public void saveHistory(History history) {
-    DateFormat dateFormat =
-        DateFormat.getDateInstance(DateFormat.MEDIUM, getCurrentLocale(context));
+    SimpleDateFormat dateFormat = new SimpleDateFormat("d MMM yyyy", getCurrentLocale(context));
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/data/local/dao/HistoryDao.java]: If you check the documentation of this constructor [here](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#SimpleDateFormat(java.lang.String,%20java.util.Locale)), you will find **Note: This constructor may not support all locales. For full coverage, use the factory methods in the DateFormat class.** You should follow this recommendation.

Comment (sonusourav) [reply app/src/main/java/org/kiwix/kiwixmobile/data/local/dao/HistoryDao.java]: @abdulwd I checked the reference material. Thanks for it.  Could you please review this?

Comment (sonusourav) [reply app/src/main/java/org/kiwix/kiwixmobile/data/local/dao/HistoryDao.java]: @abdulwd  I have made some changes. Could you please review?

**Comment by sonusourav** [comment]
@abdulwd  Could you please review this one?
And since yesterday, travis build is failing. Do you have any idea?

File: app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java [hunk 4]
```diff
@@ -111,15 +116,32 @@ protected void onCreate(Bundle savedInstanceState) {
...
   @Override
   protected void onResume() {
     super.onResume();
     presenter.loadHistory(sharedPreferenceUtil.getShowHistoryCurrentBook());
+    if (listState != null) {
+      layoutManager.onRestoreInstanceState(listState);
+    }
+  }
+
+  protected void onSaveInstanceState(Bundle state) {
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java]: Use the `@Override` annotation for overridden methods.

File: app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java [hunk 5]
```diff
@@ -111,15 +116,32 @@ protected void onCreate(Bundle savedInstanceState) {
       actionBar.setTitle(R.string.history);
     }
 
-
     historyAdapter = new HistoryAdapter(historyList, deleteList, this);
     recyclerView.setAdapter(historyAdapter);
+    layoutManager = new LinearLayoutManager(this, RecyclerView.VERTICAL, false);
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java]: We already have defined the layout manager in the XML. Instead of creating a new object, you can get it using `recyclerView.getLayoutManager()`.

File: app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java [hunk 6]
```diff
@@ -111,15 +116,32 @@ protected void onCreate(Bundle savedInstanceState) {
...
+    recyclerView.setLayoutManager(layoutManager);
   }
 
   @Override
   protected void onResume() {
     super.onResume();
     presenter.loadHistory(sharedPreferenceUtil.getShowHistoryCurrentBook());
+    if (listState != null) {
+      layoutManager.onRestoreInstanceState(listState);
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java]: I think we can move this line to `onRestoreInstanceState(Bundle state)` of this activity. In that case, `listState` can be removed. Correct me if I'm wrong.

**Comment by abdulwd** [comment]
@sonusourav The build is failing on some PRs because of no response from Testdroid.

File: app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java (hunk 5 above)
Comment (sonusourav) [reply app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java]: > 
> 
> We already have defined the layout manager in the XML. Instead of creating a new object, you can get it using `recyclerView.getLayoutManager()`.

@abdulwd  I forgot to see, from next time I will take care. Thanks for pointing it out.

File: app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java (hunk 6 above)
Comment (sonusourav) [reply app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java]: @abdulwd  I checked the documentation and I think `listState` should be in `onResume()` only since `onResume` is called after `onRestoreInstanceState()`, which is not always called.
>>Most implementations will simply use onCreate(Bundle) to restore their state, but it is sometimes convenient to do it here after all of the initialization has been done or to allow subclasses to decide whether to use your default implementation. The default implementation of this method performs a restore of any view state that had previously been frozen by onSaveInstanceState(Bundle)

Here is the link https://developer.android.com/reference/android/app/Activity.html#onRestoreInstanceState(android.os.Bundle)

**Comment by sonusourav** [comment]
> 
> 
> @sonusourav The build is failing on some PRs because of no response from Testdroid.

Is their api down or is the problem in mine code?

**Comment by sonusourav** [comment]
> 
> 
> @sonusourav would you please elaborate a little more in the commit comment why this change is necesary? so one could read the commit history and understand what happened why whithout continuously searching for the accompanying ticket.

@soloturn  Thanks for your review. I have made the changes.
