### PR TITLE
Fix tabs orientation in tabs overview

### LINKED ISSUE #948: Changing screen orientations in tab overview
**Describe the bug**

Changing screen orientation in Tab view and opening new tabs makes the whole UI quite messy.

**Steps to reproduce the behavior:**
1. open tab view
2. change screen orientation
3. click on the '+' button on the top left
4. open tab view again

**Screenshots**

screenshot_20190209-193835
screenshot_20190209-193823

**Environment**
- Version of Kiwix Android : version 2.4 Build 55
- Device : Samsung S6
- OS version : Android 7.0

### PR DESCRIPTION
**Pull request by abdulwd**
Fix #948 Force redraw of RecyclerView children so that tabs are properly oriented on screen rotation.

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java [hunk 1]
```diff
@@ -1581,6 +1580,8 @@ void backToTop() {
   public void onConfigurationChanged(Configuration newConfig) {
     super.onConfigurationChanged(newConfig);
     toggleActionItemsConfig();
+    // Forcing redraw of RecyclerView children so that the tabs are properly oriented on rotation
+    tabRecyclerView.setAdapter(tabsAdapter);
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: `tabsAdapter.notifyDataSetChanged` doesn't work?

Comment (abdulwd) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: The layouts were not redrawn using this.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: `tabRecyclerView.invalidate()`?

Comment (abdulwd) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: Nope. I tried all of them. :laughing:

Comment (abdulwd) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: Then I found this solution on SO.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: Well it makes me unhappy but that is the day to day work of using android apis.

File: app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.java [hunk 2]
```diff
@@ -1,39 +1,49 @@
 package org.kiwix.kiwixmobile.utils;
 
 import android.graphics.Bitmap;
-import android.util.Log;
+import android.media.ThumbnailUtils;
 import android.view.View;
+import androidx.annotation.NonNull;
+import androidx.annotation.Nullable;
 
 public class ImageUtils {
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.java]: this class is a perfect chance to convert to kotlin, one function bunch of hideous java null checking malarkey

Comment (abdulwd) [reply app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.java]: Hmmm. I'll try to do that. But I just know a bit of Kotlin.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.java]: I've been doing it for years, here to offer help if you need it. `ctrl+shift+alt+k` to convert to kotlin if you didn't already know

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.java]: @abdulwd do you have availability to do this next week?

Comment (abdulwd) [reply app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.java]: I'm not sure. You can pick it up if you're free.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.java]: May more painful to rewrite than it had any right to be. Give it a review I guess?

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.java]: @abdulwd I'll probably just merge this tomorrow if you don't have any feedback

**Comment by macgills** [comment]
We can revert this if you have any outstanding comments @abdulwd

File: app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.kt [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+
+object ImageUtils {
+  @JvmStatic
+  fun getBitmapFromView(
+    viewToDrawFrom: View,
+    width: Int,
+    height: Int
+  ): Bitmap? {
+    val previousDrawingCacheState = viewToDrawFrom.isDrawingCacheEnabled
+    viewToDrawFrom.isDrawingCacheEnabled = true
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.kt]: Some of the functions like `isDrawingCacheEnabled` are deprecated. I don't what this to be reverted but I want to discuss some alternative approaches to this. Should we render the WebViews as bitmaps or is there any other way to render the tabs in the tabs overview screen? I tried to find some libraries which can give us Google Chrome-like tabs. I found this library https://github.com/michael-rapp/ChromeLikeTabSwitcher. Another approach is to display tabs in titles like in Firefox. Currently, we only show a single tab in the overview screen but using tiles we can show multiple tabs. What could be the best approach?

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.kt]: I don't see a reason why we can't just have the webviews in the TabsAdapter and have then just load their content when they are paged in. Bitmaps seem like a bit of overkill

Comment (abdulwd) [reply app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.kt]: @macgills We can have WebViews, then we have to capture touch events when the tabs overview screen is displayed so that the touch for selecting the WebView is not propagated to the WebView which may have a href and the user is navigated to another page when the tab overview screen is shown.

We also have to handle the resizing of the WebViews. IMO we should try this approach.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.kt]: It has my vote. Want to create a ticket?
