### PR TITLE
Feature/frans lukas/2338 fix memory leaks

### LINKED ISSUE #2338: Fix memory leaks
**Describe the bug**

I just managed to re-create one memory leak, but am sure I have found more earlier today. This leak is caused from the ToolbarScrollingWebView. 
118581256_601951067150124_1639918906429691021_n

### PR DESCRIPTION
**Pull request by Frans-Lukas**
Fixes #2338

Memory leaks present in ReaderFragment and OnlineLibraryFragment were fixed. 

One leak is reproducible by the following steps: 

1. Open app.
2. Open book and go to reader.
3. Go to history.
4. Go to OS home screen. That is, minimize Kiwix. 

This leaks either the `webViewList`, or the `actionBar` in CoreReaderFragment. 

Fixed by adding:

```
    webViewList.clear();
    actionBar = null;
```
to `onDestroyView()` in CoreReader.

Another memory leak from the `OnlineLibraryFragment`.

Reproduced by:
1. Open online library fragment.
2. Go to history.
3. Minimize kiwix.

libraryAdapter seems to be the villain here. 

Edit: Fixed by setting the `libraryList` `adapter` to null in `onDestroyView`.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java [hunk 1]
```diff
@@ -728,6 +728,8 @@ private void handleLocaleCheck() {
     tabCallback = null;
     hideBackToTopTimer.cancel();
     hideBackToTopTimer = null;
+    webViewList.clear();
+    actionBar = null;
```
Comment (rashiq) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:732]: do we need to set the actionbar to null?

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java [hunk 2]
```diff
@@ -1655,7 +1657,8 @@ protected void restoreTabs(@Nullable String zimArticles, @Nullable String zimPos
         }
       }
       selectTab(currentTab);
-      webViewList.get(currentTab).loadUrl(UpdateUtils.reformatProviderUrl(urls.getString(currentTab)));
+      webViewList.get(currentTab)
```
Comment (rashiq) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1660]: is this just formatting? 
(small nit: please stash formatting changes like this + the reordering of the imports so it's clearly visible what the actual changes are) :)

**Review by rashiq — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java (hunk 2 above)
Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1660]: Just formatting. When should formatting changes be done? As a separate ticket, only by the static analysis, or never? Assuming that the formatting is correct. I have bound formatting and import optimization to ctrl+s, which I spam whenever. This means I'd have to stash the changes whenever I am working on any file that is not formatted according to our code style.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java (hunk 1 above)
Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:732]: Yes, any view reference should be nulled before view destruction. I verified again, with the steps described above and got the following leak. If `actionbar` is set to null in `onDestroyView`, the leak is not reproducible. 
118593919_1190825684606355_9144095146963418603_n

**Comment by Frans-Lukas** [comment]
Also found that the `mainMenu` reference is leaking. Reproduced with:

1. Open reader.
2. Go to history.
3. Minimize Kiwix.

**Comment by Frans-Lukas** [comment]
The `tabRecyclerView` is also causing a leak. Same steps as above. Fixed by `tabRecyclerView.setAdapter(null);` in `onDestroyView()`.

**Review by macgills — APPROVED** [review]
