### PR TITLE
Fixed ZimManageViewModel Leaking

### LINKED ISSUE #2608: Leaking ZimMangerViewModel
**Expected behavior**
Shouldn't leak

**Steps to reproduce the behavior:**
    1. Open App
    2. Go to the library section
    3. Go back to the Read the section
    4. Open menu drawer
    5. Open history
    6. Click until the application closes
  

 **Environment**
    - Version of Kiwix Android: 3.4.3
    - Device: Realme
    - OS version: 10
   <details><summary>Logs</summary>

```
D/LeakCanary: ​
    ┬───
    │ GC Root: Java local variable
    │
    ├─ java.lang.Thread thread
    │    Leaking: UNKNOWN
    │    Retaining 33700 bytes in 292 objects
    │    Thread name: 'RxCachedThreadScheduler-32'
    │    ↓ Thread.<Java Local>
    │             ~~~~~~~~~~~~
    ├─ io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver instance
    │    Leaking: UNKNOWN
    │    Retaining 32132 bytes in 236 objects
    │    ↓ ObservableSubscribeOn$SubscribeOnObserver.downstream
    │                                                ~~~~~~~~~~
    ├─ io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver instance
    │    Leaking: UNKNOWN
    │    Retaining 32100 bytes in 234 objects
    │    ↓ ObservableSingleSingle$SingleElementObserver.downstream
    │                                                   ~~~~~~~~~~
    ├─ io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver instance
    │    Leaking: UNKNOWN
    │    Retaining 32075 bytes in 233 objects
    │    ↓ SingleToFlowable$SingleToFlowableObserver.downstream
    │                                                ~~~~~~~~~~
    ├─ io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber instance
    │    Leaking: UNKNOWN
    │    Retaining 32051 bytes in 232 objects
    │    ↓ FlowableRetryPredicate$RetrySubscriber.downstream
    │                                             ~~~~~~~~~~
    ├─ io.reactivex.internal.operators.flowable.FlowableSingleSingle$SingleElementSubscriber instance
    │    Leaking: UNKNOWN
    │    Retaining 31891 bytes in 225 objects
    │    ↓ FlowableSingleSingle$SingleElementSubscriber.downstream
    │                                                   ~~~~~~~~~~
    ├─ io.reactivex.internal.observers.ConsumerSingleObserver instance
    │    Leaking: UNKNOWN
    │    Retaining 31866 bytes in 224 objects
    │    ↓ ConsumerSingleObserver.onError
    │                             ~~~~~~~
    ├─ org.kiwix.kiwixmobile.zim_manager.ZimManageViewModel$requestsAndConnectivtyChangesToLibraryRequests$4$2 instance
    │    Leaking: UNKNOWN
    │    Retaining 31766 bytes in 219 objects
    │    Anonymous class implementing io.reactivex.functions.Consumer
    │    ↓ ZimManageViewModel$requestsAndConnectivtyChangesToLibraryRequests$4$2.this$0
    │                                                                            ~~~~~~
    ├─ org.kiwix.kiwixmobile.zim_manager.ZimManageViewModel$requestsAndConnectivtyChangesToLibraryRequests$4 instance
    │    Leaking: UNKNOWN
    │    Retaining 31754 bytes in 218 objects
    │    Anonymous class implementing io.reactivex.functions.Consumer
    │    ↓ ZimManageViewModel$requestsAndConnectivtyChangesToLibraryRequests$4.this$0
    │                                                                          ~~~~~~
    ╰→ org.kiwix.kiwixmobile.zim_manager.ZimManageViewModel instance
    ​     Leaking: YES (ObjectWatcher was watching this because org.kiwix.kiwixmobile.zim_manager.ZimManageViewModel
    ​     received ViewModel#onCleared() callback)
    ​     Retaining 31738 bytes in 217 objects
    ​     key = da2b76f1-90b5-4891-8dfd-2fd9710fb8a0
    ​     watchDurationMillis = 5345
    ​     retainedDurationMillis = 343
    ​     context instance of org.kiwix.kiwixmobile.KiwixApp
    
    METADATA
    
    Build.VERSION.SDK_INT: 29
    Build.MANUFACTURER: realme
    LeakCanary version: 2.5
    App process name: org.kiwix.kiwixmobile
    Stats: LruCache[maxSize=3000,hits=5705,misses=90043,hitRate=5%]
    RandomAccess[bytes=4413946,reads=90043,travel=35247447474,range=25242920,size=30422877]
    Analysis duration: 6052 ms
```
</deatils>

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2608

### CODE REVIEW

**Comment by gouri-panda** [comment]
Another reason why we should Refactor Rxjava to Kotlin's flow because it's so hard to find a bug in Rxjava.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt [hunk 1]
```diff
@@ -91,7 +91,7 @@ class ZimManageViewModel @Inject constructor(
   private val dataSource: DataSource,
   private val connectivityManager: ConnectivityManager,
   private val sharedPreferenceUtil: SharedPreferenceUtil
-) : ViewModel() {
+) : AndroidViewModel(context) {
```
Comment (s-ayush2903) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:94]: Passing context to viewModels is a crime! It is an open invitation to memory leaks! Also `AndroidViewModels` are never supposed to be used as they are quite tightly couple with android arch and ain't flexible.

**Review by s-ayush2903 — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt [hunk 2]
```diff
@@ -129,8 +129,13 @@ class ZimManageViewModel @Inject constructor(
...
 
   override fun onCleared() {
-    compositeDisposable.clear()
+    compositeDisposable?.clear()
     context.unregisterReceiver(connectivityBroadcastReceiver)
+    connectivityBroadcastReceiver.stopNetworkState()
+    requestFileSystemCheck.onComplete()
+    fileSelectActions.onComplete()
+    requestDownloadLibrary.onComplete()
+    compositeDisposable = null
```
Comment (gouri-panda) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:138]: > Even though we've added what looks like proper disposal in onCleared(), our retained Disposable instance is, itself, a leak because it's still transitively holding onto a reference to anything captured in the lambda!

The reason why I set `CompositeDisposable` to nullable. More info available on  [this](https://www.zacsweers.dev/disposables-can-cause-memory-leaks) article.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt [hunk 3]
```diff
@@ -222,6 +227,7 @@ class ZimManageViewModel @Inject constructor(
       connectivityBroadcastReceiver.networkStates.distinctUntilChanged().filter(
         CONNECTED::equals
       ),
+      // PublishProcessor.create(),
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:230]: Should be removed

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt (hunk 1 above)
Comment (s-ayush2903) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:94]: Also, it isn't recommended to use this `AndroidViewModel` as it is quite tightly coupled to android arch. reducing flexibility with our code that's why don't have it anywhere in the entire codebase of ours, so should be removed.

Comment (gouri-panda) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:94]: @s-ayush2903 I was just playing around with that I thought I removed that. On it :)

**Comment by s-ayush2903** [comment]
@gouri-panda Can you synchronize your branch with `kiwix/develop`

**Review by abdulwd — APPROVED** [review]

**Review by s-ayush2903 — CHANGES_REQUESTED** [review]
nit: Synchronize here as well to get the reports uploaded.

**Comment by gouri-panda** [comment]
@s-ayush2903 I think this is up to date with `kiwix-develop `.  I'm wondering why this is happening  🤔?

**Comment by gouri-panda** [comment]
@s-ayush2903 Something weird is going on underneath the hood. The Jobs are passing after a  couple of times retrying. We should fix them as soon as possible. Because it's eating our so many times.

**Comment by kelson42** [comment]
@s-ayush2903 Waiting to your feedback here to merge.

**Review by s-ayush2903 — APPROVED** [review]
Looks good to me!
