### PR TITLE
#1825: Fix search history to show Unique searches

### LINKED ISSUE #1825: Search history suggestions are duplicated instead of reordered
**Describe the bug**

Search history suggestions are duplicated instead of being moved to the top.

**Expected behavior**

To not see duplicate search suggestions.

**Steps to reproduce the behavior:**
1. Tap on the search icon
2. Type "wiki"
3. Tap on "wiki"
4. Repeat steps 1-3 for "kiwi"
5. Tap on the search icon
6. Tap on "wiki" (without typing anything)
7. Repeat steps 5-6 10 times

**Screenshots**

Expected behavior as in 3.1.3 ("wiki" is at the top, followed by "kiwi"):

Screenshot_20200226-215905

Actual behavior (5 copies of "wiki" and no "kiwi"):

Screenshot_20200226-220514

**Environment**
- Version of Kiwix Android : 3.2.0
- Device : OnePlus 7 Pro
- OS version : OxygenOS Beta 9

### PR DESCRIPTION
**Pull request by deborahlow97**
Fixes #1825 

### Context
- User's recent searches to be unique

### Approach
- Before saving a recent search, delete duplicates of that search title in the database.

### CODE REVIEW

**Comment by deborahlow97** [comment]
> Looks good.
> 
> I personally would have preferred the database to handle this by just specifying that duplicate entries should be `ignored/replace`. Unfortunately, it looks like this feature is not present currently in objectbox. [objectbox/objectbox-java#509](https://github.com/objectbox/objectbox-java/issues/509)

Hey, yup I did look up on that before doing this, sadly that feature isn't supported yet.

**Comment by yashk2000** [comment]
@deborahlow97 the build is failing on this pull request. Could you please look into why the build is failing?

**Comment by deborahlow97** [comment]
> @deborahlow97 the build is failing on this pull request. Could you please look into why the build is failing?

Hey, I managed to have the build and the failing task in the reported build passing on my machine, and I want to try reruning the build on Github actions but it seems that I do not have permissions to do that. Could you help me rerun my build? It may be a flaky build problem :/

**Comment by yashk2000** [comment]
I also don't have the permissions to re-run the build using GitHub action here. 

Instead, you can try making a minor change in your pr. Like maybe add an extra line under the change you made and push it. That should trigger the build again. Once it passes, you revert the change, push it again and then squash your changes.

**Comment by srv-twry** [comment]
I guess you could also use `git commit --amend` and just change the commit message a little bit. Something like `Fixes #1825 ...` and then do a force push. It will not only trigger a rebuild but also make your commit message follow the commit message guidelines :)

**Comment by deborahlow97** [comment]
> I guess you could also use `git commit --amend` and just change the commit message a little bit. Something like `Fixes #1825 ...` and then do a force push. It will not only trigger a rebuild but also make your commit message follow the commit message guidelines :)

Whoops just pushed already, but good idea!

**Comment by deborahlow97** [comment]
> I guess you could also use `git commit --amend` and just change the commit message a little bit. Something like `Fixes #1825 ...` and then do a force push. It will not only trigger a rebuild but also make your commit message follow the commit message guidelines :)

Hey, yea so it seems like the build passes, will remove the white line in the next commit

**Comment by yashk2000** [comment]
@deborahlow97 since the last two commits are not related to the change, you can squash them so that it just shows 2 commits like before.

File: core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewRecentSearchDao.kt [hunk 1]
```diff
@@ -40,6 +40,7 @@ class NewRecentSearchDao @Inject constructor(
   }
 
   fun saveSearch(title: String, id: String) {
+    deleteSearchString(title)
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewRecentSearchDao.kt]: I would have just changed `distinct` to `distinctBy{::searchTerm}` in `recentSearches(zimId: String?)`.

This is technically incorrect because we retrieve search results by the id of a book as well as a term but this would delete search terms across all books, were there duplicates. This is the fault of the delete function to be fair.
