### PR TITLE
Fixed version `3.8.1` from Google Play cannot find zim on SD card that are copied to app-specific directory.

### LINKED ISSUE #3579: version 3.8.1 from Google Play cannot find zim on SD card
**Describe the bug**

version 3.8.1 from Google Play cannot find zim on SD card - zim files download via this app stored on SD and can be find corrctly, zim files in folder "\SD card\Android\data\org.kiwix.kiwixmobile\files\Kiwix", whereas zim files downloaded by computer and copied to the same folder cannot be found. Tried same zim file, but only the file downloaded by the app can be found.
Same zim file works great on old version 3.6.0, and the old verson support zim files in any folder on SD card, whereas the new version 3.8.1 seems only support specific folder and only support app downloaded zim files.
**Expected behavior**

**Steps to reproduce the behavior:**
1. download zim file via a computer
2. copy the zim file to phone SD card
3. open the app on phone and go to tab "Library"
4. no zim file can be found by the app

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.8.1
- Device : Samsung Note 20 Ultra, Samsung Galaxy S10+, both use SD cards for zim storage
- OS version : Android 13 (One UI 5.1, Note 20 Ultra); Android 12 (One UI 4.1, Galaxy S10+)

**Logs**

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3579

We have limitations in scanning all directories on Android 11 and above in the Play Store variant. If a user copies the ZIM file to the app-specific directory on the SD card, the scanning of the app-specific directory on the SD card has not been added, resulting in the copied files not being displayed on the library screen. Therefore, we added the scanning of app-specific directory to fix the issue.

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda Looks good to you?

**Comment by gouri-panda** [comment]
@kelson42 I'm looking at the search issues that we're having. After that, I'll complete this 👍

File: core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt [hunk 1]
```diff
@@ -36,6 +36,14 @@ object StorageDeviceUtils {
       add(environmentDevices(context))
       addAll(externalMountPointDevices())
       addAll(externalFilesDirsDevices(context, false))
```
Comment (gouri-panda) [inline core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt:38]: @MohitMaliFtechiz Then we shouldn't need this anymore? right?

Comment (MohitMaliFtechiz) [reply core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt:38]: @gouri-panda We need this because it scans for the device's main directory when we pass `false` into it.

```
private fun generalisePath(path: String, writable: Boolean) =
    if (writable) path
    else path.substringBefore("/Android/data/")
```

**Comment by kelson42** [comment]
no time to wait more for a review
