### PR TITLE
#2105 Crash Report 3.3.1: java.lang.IllegalStateException BaseActivity.onCreate

### LINKED ISSUE #2105: Crash Report 3.3.1: java.lang.IllegalStateException BaseActivity.onCreate
```
Caused by: java.lang.IllegalStateException: 

 
  at org.kiwix.kiwixmobile.core.base.BaseActivity.onCreate (BaseActivity.java:43)

 
  at org.kiwix.kiwixmobile.core.splash.CoreSplashActivity.onCreate (CoreSplashActivity.java:30)
```

### PR DESCRIPTION
**Pull request by macgills**
Fixes #2105 

- convert CoreApp to kotlin
- move component/instance instantiation to onCreate

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+          detectLeakedClosableObjects()
+          detectLeakedSqlLiteObjects()
+          penaltyLog()
+          detectLeakedRegistrationObjects()
+        }.build()
+      )
+    }
+  }
+
+  private fun writeLogFile() {
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt:132]: Can it be moved to some util?

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt:132]: I think probably more suited to another ticket and maybe a rewrite? Honestly I don't think this feature has once been useful to me

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt:131]: ticket [here](https://github.com/kiwix/kiwix-android/issues/2143)
