### PR TITLE
Feature/frans lukas/2301 fix rate dialog

### LINKED ISSUE #2301: Broken rate dialog in 3.4
Screenshot_20200820-102032

### PR DESCRIPTION
**Pull request by Frans-Lukas**
Fixes #2301

Rate dialog now shows text instead of numbers as its message. Rate dialog counting is also done in the main activity instead of in the reader fragment. This means the dialog will be shown on the 10th start of the application, on start. 

**Screenshots** 
Screenshot_1597920486

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt [hunk 1]
```diff
@@ -218,4 +232,57 @@ abstract class CoreMainActivity : BaseActivity(), WebViewProvider {
   }
 
   abstract fun openPage(pageUrl: String, zimFilePath: String = "")
+
+  private fun checkForRateDialog() {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt:236]: ah of course, this feature is just a chunk of random code.

Can we get this in a class? `RateUsFeature`?

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt:236]: haha! good idea.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt:236]: It will need a DialogShower so it will need to be Activity scoped  I would think
