### PR TITLE
Solves issue #1715 of zoom control

### LINKED ISSUE #1715: Zoom Control does not make the Zoom level visually enabled instantly.
**Describe the bug**
Under the Zoom options in settings the Zoom controls switch enables the custom zoom level slider option but it does not get view of a enabled option, it gets view of enabled option after we reopen the settings page. Although the slider works perfectly fine.

**Expected behavior**

Every time we enable the Zoom controls swithc the zoom level should turn on(should lighten / turn as a usable option)

**Steps to reproduce the behavior:**
1. Download the kiwix app from play store
2. Go to settings
3. Scroll down to Zoom
4. Enable the Zoom Control switch
5. Check the error

**Screenshots**
zoom_issue1

**Environment**
- Version of Kiwix Android : 3.1.3
- Device : Pixel 4
- OS version : Android 10

### PR DESCRIPTION
**Pull request by 4shutosh**
Fixes #1715 

Added missing condition in `SliderPrefernce.java` 

zoom_issue_solution1

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java [hunk 1]
```diff
@@ -168,12 +174,22 @@ protected void onBindView(View view) {
   private void setGrayState(View view) {
     SharedPreferenceUtil sharedPreferenceUtil = new SharedPreferenceUtil(getContext());
     boolean enabled = sharedPreferenceUtil.getPrefZoomEnabled();
+    NightModeConfig nightMode = new NightModeConfig(sharedPreferenceUtil,getContext());
+    boolean nightMode_enabled = nightMode.isNightModeActive();
 
     TextView titleView = view.findViewById(android.R.id.title);
     TextView summaryTV = view.findViewById(android.R.id.summary);
     if (!enabled) {
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: As you have appended `else` the negative control flow can be avoided:
```java
if (enabled) {
  // some statements
} else {
  // other statements
}
```
Negative flow is difficult to read. :(

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java [hunk 2]
```diff
@@ -168,12 +174,22 @@ protected void onBindView(View view) {
...
       titleView.setTextColor(Color.GRAY);
       summaryTV.setTextColor(Color.GRAY);
+    }else{
+      if(nightMode_enabled){
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: There should be spaces before `(` & after `)`.
Check out our code style guidelines in the README of this repo.

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java [hunk 3]
```diff
@@ -40,6 +43,9 @@
 
   private TextView mMessage;
 
+  @Inject
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: If you annotate a field `@Inject` then you have to call `TheCorrectComponent.inject(this)` for the object to be injected.

In this instance it would be `CoreApp.getCoreComponent().inject(this)` and that should be called in the constructor

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java (hunk 2 above)
Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: you can press `ctrl+alt+l` to format, our codestyle is part of this project. I generally recommend setting up a macro to format,optimise imports and save bound to ctrl+s

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java [hunk 4]
```diff
@@ -168,12 +174,22 @@ protected void onBindView(View view) {
...
     if (!enabled) {
       titleView.setTextColor(Color.GRAY);
       summaryTV.setTextColor(Color.GRAY);
+    }else{
+      if(nightMode_enabled){
+        titleView.setTextColor(Color.WHITE);
+        summaryTV.setTextColor(Color.WHITE);
+      }else{
+        titleView.setTextColor(Color.BLACK);
+        summaryTV.setTextColor(Color.BLACK);
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: This whole logic can have the scope reduced, what actually happens here is you decide the textColor and then repeat the text setting code. 
Something like
```
int color = resolveColorFromState()
titleView.setTextColor(color);
summaryTV.setTextColor(color);

private int resolveColorFromState(){
  if(isEnabled){
    return nightModeConfig.isNightModeActive ? WHITE : BLACK
  }
  return GRAY;
}
```
and that is just a rough outline, AS will probably offer to reduce that even further

**Comment by macgills** [comment]
@abdulwd re:Themes I would think if we just deleted the code that sets the text color in SliderPreference and just set the enabled state of the view then the text should behave correctly

**Comment by abdulwd** [comment]
> @abdulwd re:Themes I would think if we just deleted the code that sets the text color in SliderPreference and just set the enabled state of the view then the text should behave correctly

@4shutosh can you please try this?

**Comment by 4shutosh** [comment]
> > @abdulwd re:Themes I would think if we just deleted the code that sets the text color in SliderPreference and just set the enabled state of the view then the text should behave correctly
> 
> @4shutosh can you please try this?

Yes I'll surely try this and get back to you.

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java (hunk 2 above)
Comment (4shutosh) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: I'll fix the spaces and use proper codestyle wherever required.

**Comment by 4shutosh** [comment]
> @abdulwd re:Themes I would think if we just deleted the code that sets the text color in SliderPreference and just set the enabled state of the view then the text should behave correctly

> > @abdulwd re:Themes I would think if we just deleted the code that sets the text color in SliderPreference and just set the enabled state of the view then the text should behave correctly
> 
> @4shutosh can you please try this?

Hey!
This defintely worked.
Unused statements have been removed.

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java [hunk 5]
```diff
@@ -171,9 +170,12 @@ private void setGrayState(View view) {
...
     TextView summaryTV = view.findViewById(android.R.id.summary);
-    if (!enabled) {
-      titleView.setTextColor(Color.GRAY);
-      summaryTV.setTextColor(Color.GRAY);
+    if (enabled) {
+      titleView.setEnabled(true);
+      summaryTV.setEnabled(true);
+    } else {
+      titleView.setEnabled(false);
+      summaryTV.setEnabled(false);
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: Can you try removing these statements & check if it works?
Otherwise, it can be shortened to:
```java
titleView.setEnabled(enabled);
summaryTV.setEnabled(enabled);
```
;)

Comment (4shutosh) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: > Can you try removing these statements & check if it works?
> Otherwise, it can be shortened to:
> 
> ```java
> titleView.setEnabled(enabled);
> summaryTV.setEnabled(enabled);
> ```
> 
> ;)

Yes i did try this as well.
It keeps the zoom level enabled irrespective of the Zoom controls toggle state.
If you insist I'll try again and get back to you! :)

Comment (4shutosh) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: > Can you try removing these statements & check if it works?
> Otherwise, it can be shortened to:
> 
> ```java
> titleView.setEnabled(enabled);
> summaryTV.setEnabled(enabled);
> ```
> 
> ;)

Hey @abdulwd thee code you suggested is not working .
It keeps the zoom level enabled irrespective of the zoom controls toggle state.

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java [hunk 6]
```diff
@@ -171,9 +170,12 @@ private void setGrayState(View view) {
 
     TextView titleView = view.findViewById(android.R.id.title);
     TextView summaryTV = view.findViewById(android.R.id.summary);
-    if (!enabled) {
-      titleView.setTextColor(Color.GRAY);
-      summaryTV.setTextColor(Color.GRAY);
+    if (enabled) {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: just delete these, this whole method should be deleted. Setting the enabled state of the parent view should mean that state gets propagated downwards to its children and this already occurs in `CorePrefsFragment`
```
  private void setSliderState() {
    boolean enabled = getPreferenceManager().getSharedPreferences().getBoolean(
      PREF_ZOOM_ENABLED, false);
    if (enabled) {
      mSlider.setEnabled(true);
    } else {
      mSlider.setEnabled(false);
    }
  }
```
albeit in a very longwinded way could be 1 line
```
mSlider.setEnabled(sharedPrefUtil.getPrefZoomEnabled());
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java (hunk 5 above)
Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: this cannot be logically true as the code
```
if(myBoolean){
setEnabled(true)
} else{
setEnabled(false)
}
```
is identical to
```
setEnabled(myBoolean)
```

Android studio should give you warning and even still I would say the compiler rewrites it

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java (hunk 6 above)
Comment (4shutosh) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: > just delete these, this whole method should be deleted. Setting the enabled state of the parent view should mean that state gets propagated downwards to its children and this already occurs in `CorePrefsFragment`
> 
> ```
>   private void setSliderState() {
>     boolean enabled = getPreferenceManager().getSharedPreferences().getBoolean(
>       PREF_ZOOM_ENABLED, false);
>     if (enabled) {
>       mSlider.setEnabled(true);
>     } else {
>       mSlider.setEnabled(false);
>     }
>   }
> ```
> 
> albeit in a very longwinded way could be 1 line
> 
> ```
> mSlider.setEnabled(sharedPrefUtil.getPrefZoomEnabled());
> ```

@macgills This has been implemented in the latest commit.
Please review!

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java]: All working great, thanks for the work

**Comment by abdulwd** [comment]
@4shutosh Nice work!

**Comment by 4shutosh** [comment]
> @4shutosh Nice work!

I really look forward to contribute more to this repo!
