### PR TITLE
Fix #2071 Update the start server dialog

### LINKED ISSUE #2071: Kiwix hotspot starts without mobile hotspot being turned on
**Describe the bug**

Even if the hotspot of the device isn't on, and then the start server button is clicked, the Kiwix Hotspot starts. If I enter the provided URL in another device, the ZIMS appear in the browser of the other device too.
Earlier if Start Server was clicked without turning on the device hotspot, a toast used to be shown saying that the server couldn't be started.

From what I noticed, this is only happening when a device is already connected to some wifi network.
Then the Kiwix Server starts. And in order to use the address generated by the Kiwix Server in this case, the other device on which we want to view the ZIMS should also be connected to the same wifi network.

**Steps to reproduce the behavior:**
1. Go to host books.
2. Ensure that the device is connected to a wifi network 
3. Press on the start server button with at least one book selected.
4. When the dialog comes, click on the option saying that mobile hotspot is already on
5. The Kiwix Server starts

**Environment**
- Version of Kiwix Android : 3.3.1
- Device : Redmi K20
- OS version : Android 10

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #2071 

Update the start server dialog to give user information that books can also be hosted if the devices are on the same wifi network. 

**Screenshots** 

screencap

### CODE REVIEW

**Comment by yashk2000** [comment]
@abdulwd @macgills given that the user needs to be told to either turn on the hotspot or keep devices on the same wifi network, I think this dialog will be necessary. 
So should https://github.com/kiwix/kiwix-android/issues/1841 be closed?

File: app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostActivity.kt [hunk 1]
```diff
@@ -225,7 +226,9 @@ class ZimHostActivity : BaseActivity(), ZimHostCallbacks, ZimHostContract.View {
 
     alertDialogShower.show(KiwixDialog.StartHotspotManually,
       ::launchTetheringSettingsScreen,
-      {},
+      {
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostActivity.kt:229]: this could probably fit on one line

**Comment by yashk2000** [comment]
@macgills could there be something wrong with the CI itself?
This is completely unrelated to the other testing PR, but the build is getting canceled here to for some reason.
