### PR TITLE
#3675 Notification Navigation to KiwixReaderFragment

### LINKED ISSUE #3675: ZIM download Notification Click
**Describe the bug**

Nothing happens on click of the notification after successful download of the ZIM file.

**Expected behavior**

If should Open the ZIM in reader.

**Steps to reproduce the behavior:**
1. Download a ZIM
2. See the notification
3. Click on it.
4. Nothing happens

**Screenshots**

https://github.com/kiwix/kiwix-android/assets/85388413/377e4ddb-e40e-4509-a3a6-18b2af186c17

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT
- OS version : 13

**Logs**

### PR DESCRIPTION
**Pull request by Sagar0-0**
Fixes #3675 

**Screenshots**

### CODE REVIEW

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Whenever your PR is ready for review, please ask for a review this will be helpful for us to identify that your PR is ready for a review. See for more details https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Please also upload a screencast on the PR description whenever you fix any UI-related thing, it will be appreciated.

File: app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /*
  * Kiwix Android
- * Copyright (c) 2020 Kiwix <android.kiwix.org>
+ * Copyright (c) 20 20 Kiwix <android.kiwix.org>
```
[the remark this answers is not in the document]
Comment (Sagar0-0) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:3]: Sorry, I didn't check, studio code formatting might have caused this.

**Comment by Sagar0-0** [comment]
Working as expected now

https://github.com/kiwix/kiwix-android/assets/85388413/72b797cd-7bae-4070-adcc-5c79b6d28b46

File: app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt [hunk 2]
```diff
@@ -179,10 +188,32 @@ class KiwixMainActivity : CoreMainActivity() {
...
   }
 
+  @Suppress("MagicNumber")
+  private fun handleNotificationIntent(intent: Intent) {
+    if (intent.hasExtra(DOWNLOAD_NOTIFICATION_TITLE)) {
+      Handler(Looper.getMainLooper()).postDelayed(
+        {
+          intent.getStringExtra(DOWNLOAD_NOTIFICATION_TITLE)?.let {
+            newBookDao.bookMatching(it)?.let { bookOnDiskEntity ->
+              navigate(
```
Comment (MohitMaliFtechiz) [inline app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:204]: Please create a function for this for better readability of code like we have other functions `openSearch`, `openPage` etc so that it can be reused from other places as well. `openZimFromFilepath` would be better.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@Sagar0-0 Just a small change and then we are good for merge.

File: app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt (hunk 2 above)
Comment (Sagar0-0) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:204]: Sounds good. I should make it public,right?

Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:204]: Yes.

Comment (Sagar0-0) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:204]: I am getting an error "Function 'openZimFromFilePath' could be private", how to suppress?

Comment (Sagar0-0) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt:204]: Resolved

**Comment by Sagar0-0** [comment]
@MohitMaliFtechiz LGTM, let me know if anything else can be improved here.

**Review by MohitMaliFtechiz — APPROVED** [review]
@Sagar0-0 Thanks :tada:
