### PR TITLE
Fix #4632: Skip nav and footer text in TTS

### LINKED ISSUE #4632: Read aloud starts abnormally
**Describe the bug**
Read aloud starts abnormally. It reads the metadata or other things before it starts reading the page.

**Expected behavior**
It should start from the page or shown.

**Steps to reproduce the behavior:**
1. Open a page
2. Click the Read aloud section from the right hand side 3 dot menu. 
-->

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.14
- Device : samsung 
- OS version : 14

**Logs**

### PR DESCRIPTION
**Pull request by harshsomankar123-tech**
Fixes #4632

TTS was previously using the full  body text, which caused navigation
menus, headers, and footer links to be read before the actual article
content.

This change prefers main /  article (and  #content where present) and
filters out common navigation elements before passing text to TTS. If none
of those tags are available, it falls back to body as before.

Tested locally on multiple pages – TTS now starts reading directly from the
article instead of menu and footer text.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt [hunk 1]
```diff
@@ -152,13 +152,35 @@ class KiwixTextToSpeech internal constructor(
...
-      javascript:
-      body = document.getElementsByTagName('body')[0].cloneNode(true);
-      toRemove = body.querySelectorAll('sup.reference, #toc, .thumbcaption, title, .navbox, style');
-      Array.prototype.forEach.call(toRemove, function(elem) {    
-        elem.parentElement.removeChild(elem);});
-      tts.speakAloud(body.innerText);
-      """.trimIndent()
+            javascript:
+            (function() {
+                var content = document.querySelector('main') ||
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt]: @harshsomankar123-tech This condition is very risky; we should not be ID-specific for getting the content of a page. What if there is a CSS ID `main` for a particular section, and some other content is written in different ones? Then it will only read the content of the selected ID. There are 4 IDS in this condition, which makes it riskier. We should not rely on IDs.

The fallback will only work if no content is found with these ids. Instead, we should stick to our previous approach, where we fetch all the content we fetch from the page, and exclude the content which we don't want to read. 

Here, which content is it reading? We should exclude that one or exclude some other tags which is unneccessary if this page has.

**Comment by harshsomankar123-tech** [comment]
@MohitMaliFtechiz All requested changes have been applied. Please review.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt [hunk 2]
```diff
@@ -154,9 +154,19 @@ class KiwixTextToSpeech internal constructor(
       """
       javascript:
       body = document.getElementsByTagName('body')[0].cloneNode(true);
-      toRemove = body.querySelectorAll('sup.reference, #toc, .thumbcaption, title, .navbox, style');
-      Array.prototype.forEach.call(toRemove, function(elem) {    
-        elem.parentElement.removeChild(elem);});
+      toRemove = body.querySelectorAll(
+          'sup.reference, #toc, .thumbcaption, title, .navbox, style, script, noscript, ' +
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt]: @harshsomankar123-tech It is huge excluding(It could be break reading). Have you seen these things in the ZIM files? Headers and footers can contain the actual content that should be read. It already does not read the `banner`. Here in the `js` code, we should do minimal exclusion, which is necessary. 

What are the things it is reading extra that are reported in the issue?

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

**Comment by harshsomankar123-tech** [comment]
@MohitMaliFtechiz Thanks for the guidance. I’ve made the changes with minimal exclusion. Let me know if this looks fine.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt [hunk 3]
```diff
@@ -152,12 +152,31 @@ class KiwixTextToSpeech internal constructor(
...
+                var body = document.getElementsByTagName('body')[0].cloneNode(true);
+
+                var selectorsToRemove = [
+                    'script',
+                    'style',
+                    'noscript',
+                    'sup.reference',
+                    '#toc',
+                    '.thumbcaption',
+                    '.navbox'
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt]: @harshsomankar123-tech Thanks for making the changes. Here are my feedback:

* First, it is still reading the unnecessary things, so we have to first identify what things it is reading(what tags it is including while reading). First, we have to identify those tags, and then we will exclude them.
* The previous exclusion code is better, you can directly add more tags `toRemove = body.querySelectorAll('sup.reference, #toc, .thumbcaption, title, .navbox, style');` in this line and it will exclude them.
* In the new code, you forgot to exclude the `title`.

**Comment by harshsomankar123-tech** [comment]
@MohitMaliFtechiz Thanks for the feedback. The issue was that the sidebar is built using div role="navigation", not a nav tag, so it was still getting read. I removed nav and instead exclude: [role="navigation"], script, noscript, style. Tested on D3.js docs and Wikipedia — sidebar is no longer read and the main content works as expected. Let me know if this is okay.

**Comment by MohitMaliFtechiz** [comment]
@harshsomankar123-tech Thanks for the changes. I will review soon.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt [hunk 4]
```diff
@@ -154,9 +154,8 @@ class KiwixTextToSpeech internal constructor(
       """
       javascript:
       body = document.getElementsByTagName('body')[0].cloneNode(true);
-      toRemove = body.querySelectorAll('sup.reference, #toc, .thumbcaption, title, .navbox, style');
-      Array.prototype.forEach.call(toRemove, function(elem) {    
-        elem.parentElement.removeChild(elem);});
+      toRemove = body.querySelectorAll('[role="navigation"], script, noscript, style');
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt]: Do not remove the old properties. They are written for some reason, and removing them can introduce regressions. So add them back here. Then we are good to merge :).
