### PR TITLE
#2797 fixing the note not saving issue.

### LINKED ISSUE #2797: Unable to save notes in android 10 and above
**Describe the bug**

 Unable to save notes in android 10 and above 

**Expected behavior**

Note Should be saved in data folder without any error.

**Steps to reproduce the behavior:**

1. After downloading ZIM file 
2. Click on Note
3. When trying to save note in Android 10 and above, Toast message displayed ” Note saved ” as showing in screenshot below but note not saved.
In Logcat Showing error mention below.

That means it’s unable to create folder in android 10 and above.

**Screenshots**
| Screenshot_2022-04-04-13-58-35-164_org kiwix kiwixmobile| Screenshot_2022-04-04-13-58-40-660_org kiwix kiwixmobile | 
| --- | :-- | 

**Environment**
- Deivce : Redmi Note 9 Pro
- OS version : Android
- Kiwix version:- 3.4.6

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2797

I have changed the method for retrieving data directory for android 10 or above.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please don't forget to lin properly PR and issue and to request review. This PR is pending since 16 days!

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda ,

can you please review this PR asap.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Sure!

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt [hunk 1]
```diff
@@ -399,7 +398,7 @@ class AddNoteDialog : DialogFragment() {
 
   companion object {
     @JvmField val NOTES_DIRECTORY =
-      Environment.getExternalStorageDirectory().toString() + "/Kiwix/Notes/"
+      instance.getExternalFilesDir("").toString() + "/Kiwix/Notes/"
     const val TAG = "AddNoteDialog"
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt:402]: `Environment.getExternalStorageDirectory()` returns the primary/external storage **directory**. It can be build-in storage in a device. `context.getExternalFilesDir("")` returns absolute paths to application-specific directories on all shared/external **storage devices**. Do we need to store this directory in external storage devices? It can be ejected by the user.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt:402]: hi @gouri-panda ,

It will save on app specific directory , I changed this method because ```Environment.getExternalStorageDirectory()``` is depreciated.

https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()
