### PR TITLE
Unregister Receiver

### LINKED ISSUE #600: [Bug] App crashes when you close the app in while downloading in no connection condition
### Environment
  * version of the software you use: Android Studio 3.0.1
  * device / operating system : Nexus 6 / Android 7.0.1
  
### The Bug:

 App crashes when you close the app in no network condition while downloading the content.

#### Logs
```
  ActivityThread  E  Activity org.kiwix.kiwixmobile.zim_manager.ZimManageActivity has leaked IntentReceiver org.kiwix.kiwixmobile.zim_manager.library_view.LibraryFragment$NetworkBroadcastReceiver@3aca9c3 
                            that was originally registered here. Are you missing a call to unregisterReceiver()?
                         E  android.app.IntentReceiverLeaked: Activity org.kiwix.kiwixmobile.zim_manager.ZimManageActivity has leaked IntentReceiver org.kiwix.kiwixmobile.zim_manager.library_view.LibraryFragment
                            $NetworkBroadcastReceiver@3aca9c3 that was originally registered here. Are you missing a call to unregisterReceiver()?
                         E      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
                         E      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
                         E      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
                         E      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
                         E      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1276)
                         E      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
                         E      at org.kiwix.kiwixmobile.zim_manager.library_view.LibraryFragment.onCreateView(LibraryFragment.java:142)
                         E      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                         E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                         E      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                         E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                         E      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                         E      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                         E      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                         E      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                         E      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
                         E      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
                         E      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                         E      at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
                         E      at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
                         E      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:719)
                         E      at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
                         E      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
                         E      at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:789)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                         E      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                         E      at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                         E      at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                         E      at com.android.internal.policy.DecorView.onMeasure(DecorView.java:
                         E  Activity org.kiwix.kiwixmobile.zim_manager.ZimManageActivity has leaked ServiceConnection org.kiwix.kiwixmobile.zim_manager.library_view.LibraryFragment$DownloadServiceConnection$Down
                            loadServiceInterface@8cb1c7a that was originally bound here
                         E  android.app.ServiceConnectionLeaked: Activity org.kiwix.kiwixmobile.zim_manager.ZimManageActivity has leaked ServiceConnection org.kiwix.kiwixmobile.zim_manager.library_view.LibraryFr
                            agment$DownloadServiceConnection$DownloadServiceInterface@8cb1c7a that was originally bound here
                         E      at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                         E      at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                         E      at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
                         E      at android.app.ContextImpl.bindService(ContextImpl.java:1422)
                         E      at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                         E      at org.kiwix.kiwixmobile.zim_manager.library_view.LibraryFragment.downloadFile(LibraryFragment.java:315)
                         E      at org.kiwix.kiwixmobile.zim_manager.library_view.LibraryPresenter.loadRunningDownloadsFromDb(LibraryPresenter.java:46)
                         E      at org.kiwix.kiwixmobile.zim_manager.library_view.LibraryFragment.onCreateView(LibraryFragment.java:145)
                         E      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                         E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                         E      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                         E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                         E      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                         E      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                         E      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                         E      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                         E      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
                         E      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
                         E      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                         E      at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
                         E      at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
                         E      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:719)
                         E      at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
                         E      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
                         E      at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:789)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                         E      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                         E      at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                         E      at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                         E      at android.view.View.measure(View.java:19857)
                         E      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                         E      at android.widget.FrameLayout.onMea

                            Process org.kiwix.kiwixmobile (PID: 32453) ended
```

#### Steps to reproduce:

  1. Start downloading some content
  2. disconnect network
  3. force close the app

### PR DESCRIPTION
**Pull request by hjoshi123**
Fixes #600 

Changes: Added unregisterReceiver() in LibraryFragment to stop the crash.

### CODE REVIEW

**Comment by hjoshi123** [comment]
@mhutti1 Could you please take a look into this?

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java [hunk 1]
```diff
@@ -158,6 +158,40 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
     return llLayout;
   }
 
+  @Override
+  public void onStop() {
+    if (mBound && super.getActivity() != null) {
+      super.getActivity().unbindService(mConnection.downloadServiceInterface);
+      mBound = false;
+    }
+    if (isReceiverRegistered){
```
[the remark this answers is not in the document]
Comment (hjoshi123) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java]: Ok. just a question. The logic of unregistering should be done in onStop right?

[the remark this answers is not in the document]
Comment (hjoshi123) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java]: I have changed it. Can you review it again?

[the remark this answers is not in the document]
Comment (hjoshi123) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java]: @srv-twry take a look at it

**Comment by hjoshi123** [comment]
@srv-twry I have changed the code and adjusted the spaces. can you take a look into it?

**Comment by srv-twry** [comment]
@hjoshi123 Yes, looking at it again but please don't ping multiple times for it. You did it in the review comments as well. 
I know you want it done quickly but give reviewers some time :smile:

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java [hunk 2]
```diff
@@ -45,6 +46,7 @@
 import javax.inject.Inject;
 
 import static org.kiwix.kiwixmobile.utils.StyleUtils.dialogStyle;
+import static org.kiwix.kiwixmobile.zim_manager.library_view.LibraryFragment.DownloadServiceConnection.*;
```
Comment (srv-twry) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java]: I am not sure we need these imports. You have just removed a method. Why add these ? May be you were trying out things but make sure to optimize imports before sending the PR.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java [hunk 3]
```diff
@@ -158,6 +158,27 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
...
+      isReceiverRegistered = false;
+    }
+    super.onStop();
+  }
+
+  @Override
+  public void onDetach() {
+    if (mBound && super.getActivity() != null) {
+      super.getActivity().unbindService(mConnection.downloadServiceInterface);
+      mBound = false;
```
Comment (srv-twry) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java]: ```onDetach``` gets called everytime the fragment is recreated inside the Activity. If you're unbinding the service in the ```onDetach``` then you don't need to do it ```onStop``` i.e. it should only be in one method.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java (hunk 2 above)
Comment (hjoshi123) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java]: @srv-twry I wanted to ask about that. Could we like write a gradle script or something so that we don't need to remove those manually?

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java (hunk 3 above)
Comment (hjoshi123) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java]: Oh Yeah. Sorry for that mistake. Lemme correct it.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java (hunk 2 above)
Comment (srv-twry) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java]: Android studio has a shortcut ```ctrl + alt + o```. I haven't seen anyone writing the gradle script for it.

**Comment by hjoshi123** [comment]
@srv-twry Give it a look again. :)

**Comment by srv-twry** [comment]
@hjoshi123 Please update the branch.

**Comment by hjoshi123** [comment]
@rashiq @kelson42 Can you merge this PR?

**Comment by hjoshi123** [comment]
@kelson42 Can you give a look into it and merge this?

**Comment by kelson42** [comment]
@mhutti1 Can you please review that PR as downloading related crash are massive and quite annoying to leave in 2.4?
