### PR TITLE
Fixed bug in bookmark and history list.

### LINKED ISSUE #1907: Bug in Bookmarks and History list selection
**Describe the bug**
In history and bookmarks screen one can select items for deletion, but there is a button which allows user to view bookmark or history from all books. Even after selecting the items one can switch the view. Which results in confusing list(shown in screen shot).

**Expected behavior**
The view book marks from all books switch should be gone after selecting items, so that user cannot change the list. Another way is that number of selected item should change according to the list items.

**Steps to reproduce the behavior:**
1. Open pages from different books.
2. Open history from the menu items.
3. Select multiple items from different books.
4. Click the switch "View history from all books".
5. See the wrong number of selections.

**Screenshots**
Screenshot_2020-03-17-14-46-36-539_org kiwix kiwixmobile
Screenshot_2020-03-17-14-55-48-004_org kiwix kiwixmobile

### PR DESCRIPTION
**Pull request by yash1ts**
Fixes #1907 

Changed:
BookmarksActivity, HistoryActivity : made switch "View from all books" invisible in action mode.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java [hunk 1]
```diff
@@ -84,6 +84,7 @@
     @Override
     public boolean onCreateActionMode(ActionMode mode, Menu menu) {
       mode.getMenuInflater().inflate(R.menu.menu_context_delete, menu);
+      bookmarksSwitch.setVisibility(View.INVISIBLE);
```
Comment (yashk2000) [inline core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java]: Instead of making it invisible, maybe we could just disable the buttons in both history and bookmarks? If we make it invisible, a small black bar will still be visible below the actionMode which looks a bit peculiar.

Comment (yash1ts) [reply core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java]: Yeah you are right. Changed it.

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java]: Cool :+1:
