### PR TITLE
#1466 npe hotspot service

### LINKED ISSUE #1466: Crash Report: java.lang.NullPointerException:      at org.kiwix.kiwixmobile.wifi_hotspot.HotspotService.onHotspotTurnedOn (HotspotService.java)
**Describe the bug**
in 3.01 beta:
```
java.lang.NullPointerException: 
  at org.kiwix.kiwixmobile.wifi_hotspot.HotspotService.onHotspotTurnedOn (HotspotService.java)
  at org.kiwix.kiwixmobile.wifi_hotspot.WifiHotspotManager$1.onStarted (WifiHotspotManager.java)
```

**Expected behavior**
No crash.

**Steps to reproduce the behavior:**
Unknow, reported from play store

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.0.1
- Device : Pixel XL
- OS version : 10

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1466

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/di/ActivityScope.kt [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package org.kiwix.kiwixmobile.di
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/di/ActivityScope.kt]: I remember I have used `ActivityScope`. I think we call it `PerActivity`, you can reuse that and rename it if you like.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/di/ActivityScope.kt]: I wanted to keep `dagger.android` and `dagger` separate was my motivation of adding this new annotation

Comment (abdulwd) [reply app/src/main/java/org/kiwix/kiwixmobile/di/ActivityScope.kt]: It will be quite confusing having two annotation sounding to provide the same functionality.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/di/ActivityScope.kt]: Deleted PerActivity, on a green build I will merge this so we can do another beta release today

Comment (abdulwd) [reply app/src/main/java/org/kiwix/kiwixmobile/di/ActivityScope.kt]: When are you going to merge release/3.0 with develop? Otherwise, it will be very difficult to merge them later.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/di/ActivityScope.kt]: we are going to merge the `release/3.0` branch to master and tag it for the full release, at that time I will also merge it to dev
