### PR TITLE
Fix #1899 Finish action mode when shifting fragments

### LINKED ISSUE #1899: ActionMode not finishing when shifting library fragments
**Describe the bug**
When shifting between the Device ad Online fragments in Library, the actionMode from the Device Fragment does not finish. 

**Expected behavior**
ActioMode should finish when shifting fragments. 

**Steps to reproduce the behavior:**
1. Go to the library
2. Go to Device fragment
3. Long press any book to select it
4. The actionMode turns on in the toolbar
5. Press on online
6. The action mode stays on while it should have been finished when shifting the fragment. 

**Screenshots**

screencap

screencap

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi K20
- OS version : Android 10

**Additional Context**

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #1899 

The action mode is now finished when a user shifts from the library to the online fragment. 

**Screenshots** 

ezgif com-video-to-gif

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt [hunk 1]
```diff
@@ -113,6 +113,15 @@ class ZimFileSelectFragment : BaseFragment() {
     }
   }
 
+  override fun setUserVisibleHint(isVisibleToUser: Boolean) {
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: this method is deprecated, I would avoid using it

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: @macgills I was unable to find another method which is called when the fragment made visible or hidden. I tried using onHiddenChanged(), but that did not work. 

I tried using `userVisibleHint` too inside onPause(), that didn't work.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: You could go to the activity and add an onPageChangeListener to the viewPager

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: @macgills `SimplePageChangeListener` already exists. I tried making a function in `ZimFileSelectFragment` and calling it in the listener, but I wasn't able to make it work.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: It is possible, push your attempt and I can help guide you

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: @macgills I pushed some changes that I made but didn't work. Please guide me. 

I'll squash all extra commits once done.

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: The same thing I've done in ZimManageAcitivty, I placed the same code in the onPageScrollStateChanged of SimplePageChangeListener. That also didn't work.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt [hunk 2]
```diff
@@ -88,6 +90,11 @@ class ZimManageActivity : BaseActivity() {
     searchItem?.isVisible = position == 1
     languageItem?.isVisible = position == 1
     getZimItem?.isVisible = position == 0
+    if (position == 1) {
+      val fragment: Fragment?
+      fragment = ZimFileSelectFragment()
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt]: this creates a fragment, you want to retrieve the existing instance from the viewpager's adapter.

You also probably want to do this in another pageChangeListener

**Comment by yashk2000** [comment]
@macgills is this fine?

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt [hunk 3]
```diff
@@ -71,6 +71,34 @@ class ZimManageActivity : BaseActivity() {
       offscreenPageLimit = sectionsPagerAdapter.count - 1
       tabs.setupWithViewPager(this)
       addOnPageChangeListener(SimplePageChangeListener(::updateMenu))
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt]: `sectionsPagerAdapter.getItem(position)` will give you the fragment, use SimplePageChangeListener but just add another one

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt]: @macgills I tried this earlier. It didn't work. What am I doing wrong?

```kotlin
override fun onPageScrolled(
          position: Int,
          positionOffset: Float,
          positionOffsetPixels: Int
        ) {
          if (position == 1) {
            val page = sectionsPagerAdapter.getItem(0)
            if (page != null) {
              (page as ZimFileSelectFragment).finishActionMode()
            }
          }
        }
```

> SimplePageChangeListener but just add another one

This means I should add the condition to the existing SimplePageChangeListener and add a new one in the ZimManageActivity.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt]: Use a debugger and find out

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt]: >This means I should add the condition to the existing SimplePageChangeListener and add a new one in the ZimManageActivity.

`addOnPageChangeListener(SimplePageChangeListener(::updateActionMode))`

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt]: @macgills I checked the values returned by `getItem()` and the method I have used. The values differ. I don't think that `getItem()` returns the exact value of the fragment that is needed to obtain a fragment instance.

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt]: @macgills sorry, I am not very clear about how to send a signal to the LibraryFragment.
Do I have to communicate through the `ZimManageViewModel` and use `instantiateItem`?

Also could you please tell me what is wrong with the approach I have used currently?

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt]: You are depending on internal apis to not change, a bad practice

```
    private static String makeFragmentName(int viewId, long id) {
        return "android:switcher:" + viewId + ":" + id;
    }
```

The androidx team have made no guarantee that this Id will stay the same (sidenote: it will likely never change because a billion apps rely on this fix so now we have hamstrung the androidx team so they cannot change. It is a shitty situation from all sides and I want to sidestep it, _don't depend on private methods_) and neither should we.

Create a publishProcessor in the viewmodel, maybe something like currentTabIndex, send it the currentPage when the page changes, in ZimFileSelectFragment subscribe to this processor. There are additional steps you can take to make this cleaner but this will do for the broad outline

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt]: @macgills thanks a lot for this explanation. This made things pretty clear :+1:

**Comment by yashk2000** [comment]
@macgills I updated the pr. I used LiveData instead of publishProcessor as I thought that our use of the data is pretty simple so using LiveData will also solve the problem well. Please let me know if any more changes are needed.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt [hunk 4]
```diff
@@ -111,9 +111,15 @@ class ZimFileSelectFragment : BaseFragment() {
     if (savedInstanceState != null && savedInstanceState.getBoolean(WAS_IN_ACTION_MODE)) {
       zimManageViewModel.fileSelectActions.offer(FileSelectActions.RestartActionMode)
     }
+
+    zimManageViewModel.currentPage.observe(viewLifecycleOwner, Observer<Int> { currentPage ->
+      if (currentPage == 1) {
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: I'd prefer if this logic was handled outside of the view. LiveData has MoediatorLiveData, had a publishProcessor been used to send the data then there is filter/map and any number of other operators

**Comment by abdulwd** [comment]
@yashk2000 Do you plan to work on this?

**Comment by yashk2000** [comment]
@abdulwd yes, sorry for being inactive for a few days. I'll get back to work from today.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt (hunk 4 above)
Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt:116]: @macgills I am having some trouble in using a publish processor. I've never used it before. Could you please provide some help here?

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt:116]: It is even simpler, you can just use `.map` to transform your liveData. You will want to rename some things also as it will no longer be `currentPage` being observed here

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt:116]: ehhh after looking at the Transformations API for liveData I like it a lot less.

PublishProcessor would be a lot handier. A publish processor is like a multicast queue

If in a client I have
```
theProcessor.subscribe { print(it) }
```

then every time I call `theProcessor.offer("test")` that sends "test" to every subscription to `theProcessor`

RxJava has a lot of operators that do handy things like so we could say

```
theProcessor.map{ it +"mapped!"}.subscribe{ print(it)}
```

and then we would get ` testmapped!` printed. Map is way more powerful than this 

eg
```
theProcessor.map{ it.equals("test")}. subscribe{ if (it) print("it was test") else print("it wasn't test")}
```
where we can change the type from what was originally sent to the processor.

See how far you can get with a processor and I'll be back tomorrow to review

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: @macgills thanks a lot for the above explanation :)
I have updated the pr using a publish processor. It works and turns off the action mode on changing tabs. Please let me know if the way I have used the publish processor is correct.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt [hunk 5]
```diff
@@ -111,6 +111,12 @@ class ZimFileSelectFragment : BaseFragment() {
     if (savedInstanceState != null && savedInstanceState.getBoolean(WAS_IN_ACTION_MODE)) {
       zimManageViewModel.fileSelectActions.offer(FileSelectActions.RestartActionMode)
     }
+
+    zimManageViewModel.currentPage.map { it == 1 }.subscribe { if (it) finishActionMode() }
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt:115]: I think filter would be apt here.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt:115]: I also want this logic in the viewmodel

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt:115]: @macgills if I put it in the view model, do I need to make it like the other disposables which are already created there? 
Sorry for a bit of inefficiency from my side here, I'm not very familiar with how to use publish processors, but I'm interested in learning about them as they seem better than live data.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt:115]: They are very different things, livedatas have really only one android specific use and Rx has almost every use under the sun and has implmentations across many languages. It is slightly falling out of popularity in favour of coroutines because it is very complicated and easy to misuse.

So we already have our input Processor, on page change send the page.
Then inside our ViewModel we can have our output processor eg
```
input.map { /*whatever we want to do*/ }
```
we can preform any dat transformation here.

filter only allows an item downstream if the condition inside is true

eg
```
Flowable.just("a", "b", "c")
.filter { it == "b"}
.subscribe { print(it) }
```
would print "b" but without the filter would print "a" then "b" then "c"

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt]: @macgills please take a look at the latest changes I made. 
I am facing one issue here. When the action mode is on and I shift fragments, the action mode stays on, when I go back to the offline files section and then again to the online section, then the action mode turns off. It doesn't turn off the first time the transition is done. I checked the logs and the function in the view model is called whenever the selected page index is 1, but action mode doesn't get turned off. Could you please provide some help with this?

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt [hunk 6]
```diff
@@ -19,7 +19,9 @@
 package org.kiwix.kiwixmobile.zim_manager
 
 import android.app.Application
+import android.content.Context
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:22]: static analysis failed on this unused import.

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:22]: I'll fix that in the next commit. There is a minor issue in the pr right now. Hopefully, I'll fix both the issues with the next commit.

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt [hunk 7]
```diff
@@ -143,6 +146,12 @@ class ZimManageViewModel @Inject constructor(
     )
   }
 
+  fun actionMode(actionMode: ActionMode?) {
+    currentPage.filter { it == 1 }.subscribe {
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:150]: I wanted the logic, not the actual function, in the viewmodel.

there should be a field in ZimManageViewModel
```
val libraryFragmentIsVisible = currentPage.filter{ it == 1}
```

and in ZimFileSelectFragment
```
disposable.add(viewModel.libraryFragmentIsVisible.subscribe{ actionMode?.finish() })
```

if the action mode isn't finishing the maybe actionMode is null? Or the condition is activating wrong or the page change listener isn't sending the data.

`.doOnNext{ //log some stuff}`

is generally the easiest way to get an idea of what Rx is at

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:150]: > if the action mode isn't finishing the maybe actionMode is null? Or the condition is activating wrong or the page change listener isn't sending the data.

@macgills I checked all these conditions. The page change listener was sending data and the condition waa activation correctly. But for some reason, I think the first time actionMode was being sent as null. I wasn't able to figure out why though. Just for trying, I checked the value of actionMode after converting it to a string to see result, and it was same both the times the function was being called. 

I tried the way you suggested in the above comment.It works properly, I'll update the pr with that. Thanks a lot for helping with this pr. Learned a lot :)

File: app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt [hunk 8]
```diff
@@ -108,6 +108,9 @@ class ZimManageViewModel @Inject constructor(
   val fileSelectActions = PublishProcessor.create<FileSelectActions>()
   val requestDownloadLibrary = BehaviorProcessor.createDefault<Unit>(Unit)
   val requestFiltering = BehaviorProcessor.createDefault<String>("")
+  val currentPage = PublishProcessor.create<Int>()
+
+  val libraryFragmentIsVisible = currentPage.filter { it == 1 }
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:113]: Great work, but now this is in a ViewModel so I would request unit tests for this filter.

if you look at ZimManageViewModelTest
```
    @Test
    fun `RestartActionMode offers StartMultiSelection`() {
      viewModel.sideEffects.test()
        .also { viewModel.fileSelectActions.offer(RestartActionMode) }
        .assertValues(StartMultiSelection(viewModel.fileSelectActions))
    }
```
even though it is a livedata the apis are very similar for testing disposables so your tests should bare a resemblance to this. Have 1 test where the filter emits and another where it doesn't, please.

Also on a fresh look I no longer like the name so `libraryTabIsVisible` is a teensy bit better I think, no need to leak an implementation detail in a name

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:113]: @macgills I'm facing a bit of difficulty over here. 
I offered the values 1 and 0 to the publishProcessor, `currentPage`. 1 for the case when user shifts to the online fragment and action mode has to be finished.
0 for when nothing has to be done. 
After this how do I check the filter? The disposable becomes a Flowable<Int!>

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:113]: you want to call `.test()` on the Flowable, under the hood this calls `.subscribe` with a `TestSubscriber`

as I said very similar to this

```
viewModel.sideEffects.test()
        .also { viewModel.fileSelectActions.offer(RestartActionMode) }
        .assertValues(StartMultiSelection(viewModel.fileSelectActions))
```

but `viewModel.sideEffects` is `libraryFragmentIsVisible `

Comment (yashk2000) [reply app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt:113]: Thanks for this. I'll try to get this working ASAP.

File: app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt [hunk 9]
```diff
@@ -517,4 +517,18 @@ class ZimManageViewModelTest {
         .assertValues(StartMultiSelection(viewModel.fileSelectActions))
     }
   }
+
+  @Test
+  fun `finish actionMode on tab change to online section`() {
+    viewModel.libraryTabIsVisible.test()
+      .also { viewModel.currentPage.offer(1) }
+      .assertValue(1)
```
Comment (yashk2000) [inline app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt:525]: @macgills here the filter condition wil pass and hence 1 value will be there. Right now I have hardcoded it. I'm not sure what condition to check for here.

File: app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt [hunk 10]
```diff
@@ -517,4 +517,18 @@ class ZimManageViewModelTest {
...
+  }
+
+  @Test
+  fun `no change in actionMode`() {
+    viewModel.libraryTabIsVisible.test()
+      .also { viewModel.currentPage.offer(0) }
+      .assertEmpty()
```
Comment (yashk2000) [inline app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt:532]: Here, since the filter condition won't pass, no value will be there and hence I checked that it should be empty which seems to work fine. Please let me know if this should be changed.

File: app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt (hunk 9 above)
Comment (macgills) [reply app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt:525]: The test name is inaccurate, this knows nothing about an action mode. `libraryTabIsVisible emits when currentPage is 1` is probably most descriptive.

Aside from that this is all good, the logic of the filter is tested. We could take it a bit further because it feels a little odd that `libraryTabIsVisible` tells us `1` and also that we have no true concept in code that the `LibraryTab` is page 1, it is largely incidental.

To solve the `libraryTabIsVisible` problem is quite straighforward, we could map it

```
currentPage.map{ it == 1 }.filter { it }
```

now we would receive `true` here and continue to receive nothing in our other test.

The `1` problem requires us to model this data better. I tend to favour modelling tabs as Enums because enums give us access to a lot of fun little functions eg given an enum

```
enum class Suits(val color:String){
HEARTS("red"),DIAMONDS("red"),SPADES("black"),CLUBS("black")
}
```

if I were to call `Suits.values()` it would return a list of all those defined enums. Enums are also implicitly ordered eg `HEARTS.ordinal()==0`...`CLUBS.ordinal()==3`

Inside SectionsPagerAdapter we could migrate PagerData into being an enum, probably rename it to something more tabby too.

This is of course all quite a bit of overkill probably. If you want to learn more on enums etc, go for it, otherwise after a little rename of these test methods I am happy

File: app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt (hunk 10 above)
Comment (macgills) [reply app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt:532]: Test is exactly what I wanted to see but the test name needs a little work as mentioned above

File: app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt (hunk 9 above)
Comment (yashk2000) [reply app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt]: @macgills I have updated the pr with proper method names. Also, for now, I used a map and then a filter so that instead of `1` we could put `true` in the test to make it look more suitable. 

Thanks a lot for the above explanation. I'll look into what you told about modeling the data better using enums too later.

Comment (macgills) [reply app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt]: @yashk2000 do you want to explore an enum solution now on this PR or should I just merge it?

Comment (yashk2000) [reply app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt]: @macgills if it's fine, you can merge this.
