### PR TITLE
Fixed AndroidView Height Issue

### LINKED ISSUE #4626: ScrollView doesn't scroll to the bottom
**Describe the bug**
The webview doesn't scroll to the last bottom. It hides in the bottom navigation view. It doesn't scroll to the end.
**Expected behavior**
We should see the total bottom webview content
**Steps to reproduce the behavior:**
1. Open a file
2. Go to the bottom without zooming
3. See the last bottom content doesn't show 
-->

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.14
- Device : Samsung
- OS version : 14

https://github.com/user-attachments/assets/efe79a8f-bd31-42d8-b3a6-bc8b8c2169ab

### PR DESCRIPTION
**Pull request by atharvyadav22**
Fixes #4626

### What Changed?
Layout Orientation for ReaderScreen

### Why?
WebView was content was hinding behind `TlsControl`

#### Screenshots

https://github.com/user-attachments/assets/a75c7146-6248-479b-a54d-0bb29577c3ac

### CODE REVIEW

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22 Is this PR ready for review?

**Comment by atharvyadav22** [comment]
> @atharvyadav22 Is this PR ready for review?

Yes!

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt [hunk 1]
```diff
@@ -317,25 +317,38 @@ private fun ReaderContentLayout(
...
+            ) {
+              ShowZIMFileContent(
+                state,
+                bottomAppBarScrollBehavior,
+                topAppBarScrollBehavior,
+                shouldUpdateTopAppBarAndBottomAppBarOnScrolling
+              )
+              ShowProgressBarIfZIMFilePageIsLoading(state)
+            }
+            if (state.showTtsControls) {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt]: These logics are unnecessary here. Inside those methods, they are still written.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt [hunk 2]
```diff
@@ -317,25 +317,38 @@ private fun ReaderContentLayout(
...
+              TtsControls(state)
+            }
+            if (state.shouldShowDonationPopup) {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt]: This too.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt [hunk 3]
```diff
@@ -317,25 +317,38 @@ private fun ReaderContentLayout(
...
+              ShowDonationLayout(state)
+            }
+
+            if (state.shouldShowBottomAppBar) {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt]: This one too.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt [hunk 4]
```diff
@@ -317,25 +317,38 @@ private fun ReaderContentLayout(
...
-            BottomAppBarOfReaderScreen(
-              state.bookmarkButtonItem,
-              state.previousPageButtonItem,
-              state.onHomeButtonClick,
-              state.nextPageButtonItem,
-              state.tocButtonItem,
-              state.shouldShowBottomAppBar,
-              bottomAppBarScrollBehavior
-            )
+          Column(modifier = Modifier.fillMaxSize()) {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt]: Instead of adding this in Column, we should move `BottomAppBarOfReaderScreen` to the scaffold's bottomBar, which is the best placement for this.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

**Review by MohitMaliFtechiz — APPROVED** [review]
@atharvyadav22 Thanks 🎉 🎉 . Once CI is green, we will merge.
