### PR TITLE
Bugfix/macgills/1818 search input

### LINKED ISSUE #1818: Input methods are broken in search
**Describe the bug**

When searching for an article, kiwix-android messes with the text box in a way that breaks many forms of input.

**Expected behavior**

To be able to enter text properly in the text box, just like in version 3.1.3.

**Steps to reproduce the behavior:**

1. Tap on the search icon in the app bar
2. Do one of the following:
a. Type fast with an English keyboard. Notice that some letters are lost.
b. Use Japanese handwriting input. Notice that you can only enter one stroke before the character disappears.
c. Use Chinese handwriting input. Notice the same problem as with Chinese
d. Type with Japanese flick input. Notice that the word being typed in deselected. Entry of neither dakuten, handakuten, nor Kanji work.
e. Type with Japanese QWERTY input. Notice the same problem as with flick input. No Japanese at all can be typed, only fullwidth Latin.

This is a nuisance for English, Chinese, and other languages that don't use selection.

This bug completely prevents any Japanese from being typed.

**Screenshots**

Japanese flick input being broken in kiwix-android article search:

Screenshot_20200225-173225

Japanese flick input working in the system launcher search (it worked similarly in kiwix-android 3.1.3):

Screenshot_20200225-173232

**Environment**
- Version of Kiwix Android : 3.2.0
- Device : OnePlus 7 Pro
- OS version : OxygenOS Beta 9

This was working fine with version 3.1.3.

### PR DESCRIPTION
**Pull request by macgills**
Fixes #1818

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt [hunk 1]
```diff
@@ -127,8 +126,7 @@ class SearchViewModel @Inject constructor(
       searchResultsFromZimReader(),
       filter,
       Function3(this::reduce)
-    ).debounce(100, MILLISECONDS)
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt]: Why was this added? :/

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt]: I think in an earlier incarnation of the screen I didn't have an appropriate `Initialising` state so there was a brief flicker as the screen moved states on creation. All in all a poor decision by myself that is now being corrected
