### PR TITLE
Remove redundant permission toast

### LINKED ISSUE #978: Redundant Toast pops up even when storage permissions are allowed
**Describe the bug**

When the app starts up, the app asks for permissions to access the storage. Upon pressing "Yes" a toast pops up saying "To access offline content we need access to your storage" which is redundant as permissions have already been given.  

**Expected behavior**

There is no use of this toast to pop up when permissions have been allowed.

**Steps to reproduce the behavior:**

1. Open the app for the first time
2. Press "Yes" on the prompt for storage access permissions 
**Screenshots**

screenshot_20190213-155709

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Moto G5 Plus
- OS version : Android 8.0

### PR DESCRIPTION
**Pull request by abdulwd**
Fixes #978

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots/GIF for the change: [If possible, please add relevant screenshots/GIF]

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 1]
```diff
@@ -205,9 +207,6 @@
   CoordinatorLayout snackbarRoot;
   @BindView(R2.id.fullscreen_video_container)
   ViewGroup videoView;
-
-  @Inject
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: why did this move from the other injected fields?

Comment (abdulwd) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: I just did ⌘+⌥+L to reformat the code after importing Square's code style to reformat the code. I think this move because it's protected.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: bring up the reformat dialog for java files, for me that is `ctrl+alt+shift+l`, and untick `rearrange entries`

Comment (abdulwd) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: My reformat dialog had rearrange entries checked. :p

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: _untick_

Comment (abdulwd) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Done. I think we should also rearrange the code in our pre-commit hook.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: There is no rearrange for kotlin so I don't rate it highly

**Comment by macgills** [comment]
I still got the toast, check ZimFileSelectFragment

**Comment by abdulwd** [comment]
I did this only for the home activity.

**Comment by macgills** [comment]
https://github.com/kiwix/kiwix-android/issues/978#issuecomment-523019700 I requested for the ZimManage screens as well

**Comment by abdulwd** [comment]
It's there in `ZimFileSelectFragment` in the `onResume` method but I think we should keep it as it should only pop up if the user hasn't granted the permission.

**Comment by macgills** [comment]
Not the case as I got the toast after granting permission on MainActivity and then navigating to the ZimManage. There exists an underlying error, one requests WRITE, the other requests READ. These 2 permissions have a sordid and complicated history of being intertwined. Changing both to read should be sufficient as we should only be saving files to our internal storage
