### PR TITLE
#1709 Change icon of history and bookmarks items on selection and unselection

### LINKED ISSUE #1709: Icon of bookmarks and history items does not change on unselecting the item
**Describe the bug**
After an item/s is selected in the bookmarks or history section, then on unselecting it, the icon does not change back to the default. It stays as a blue circular tick mark.

**Expected behavior**
The icon should change back to back it was before selection. 

**Steps to reproduce the behavior:**
1. Go to bookmarks.
2. Select items.
3. Unselect them.
4. The original icon does not come back. Instead a blue tick mark is shown. 

**Screenshots**

After selecting and unselecting
screencap

Original
screencap

**Environment**
- Version of Kiwix Android : 3.1.3
- Device : Redmi K20
- OS version : Android 9(Pie)

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #1709 

The tag condition while setting the icon has been removed for proper changing of icons. Now when an item is selected or unselected in the bookmarks or history activity, the icon is changed properly.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ImageViewExtensions.kt [hunk 1]
```diff
@@ -25,13 +25,11 @@ import androidx.core.widget.ImageViewCompat
...
-    base64String.toBitmap()
-      ?.let {
-        setImageBitmap(it)
-        tag = base64String
-      }
-  }
+  base64String.toBitmap()
+    ?.let {
+      setImageBitmap(it)
+      tag = base64String
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ImageViewExtensions.kt]: we don't need to set the tag either

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ImageViewExtensions.kt]: Also here is a great video on [debugging](https://www.youtube.com/watch?v=rjlhSDhFwzM) if you get the free time.

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ImageViewExtensions.kt]: Thanks!! I'll definitely look into it.
