### PR TITLE
Fix Back button after opening a search result closes the app

### LINKED ISSUE #2886: Back button after opening a search result closes the app
**Describe the bug**
Pressing Back closes the app, if you have opened an article from the search result list.

**Expected behavior**
It should bring you back to the search result list.

**Steps to reproduce the behavior:**
- Open article A.
- Follow a wikilink to B.
- Press Back. It brings to A, as expected.
- Click the magnifying glass.
- Press Back. It brings to A, as expected.
- Click the magnifying glass, search for an article and open it.
- Press Back. The app closes. Instead, the app should go back to the search result list.

**Environment**
- Version of Kiwix Android : Both 3.5.0 and 3.4.1 from F-droid
- OS version : Android 10, Android 7.1.1

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2886

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt [hunk 1]
```diff
@@ -36,7 +36,8 @@ data class OpenSearchItem(
       SearchItemToOpen(searchListItem.value, openInNewTab),
       TAG_FILE_SEARCHED
     )
-    activity.popNavigationBackstack()
+    val readerFragmentResId = (activity as CoreMainActivity).readerFragmentResId
+    activity.navigate(readerFragmentResId)
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt:40]: Instead of navigating to the new fragment, we should pop the fragment from the stack.

**Review by gouri-panda — CHANGES_REQUESTED** [review]

**Review by gouri-panda — APPROVED** [review]
