### PR TITLE
Task/anr fix zimfile reader

### LINKED ISSUE #3929: org.kiwix.kiwixmobile.core.reader.ZimReaderContainer.setZimFile Input dispatching timed out
image

### PR DESCRIPTION
**Pull request by CalebKL**
Fixes #3929

* This PR fixes the ANR thats being caused while trying to create the `zimFileReader` object. The UI was being blocked since we were creating the object on `IO` Thread but we are using `runblocking` which blocks the main thread. The solution to the problem was to `suspend` `setZimFile` and `setZimFileDescriptor`. Then tie the scope on `lifecycleScope` on the Fragments.  When the `zimFileReader` is being created and it takes time for the initial load, the `progressBar` will be visible to the users and when Loading is complete, the `progressBar` will be Gone. 
The solution doesn't block the `Main` Thread and instead switches the background work to a different thread(`IO`)
* Removed the unnecessary creation of ZimFileReader when opening notes on the Notes screen. Refactored `AddNoteDialog` to use database values for performing note-related operations (e.g., view, edit, delete notes) instead of setting and using `ZimFileReader`.
* Improved the tab closing and restoring process. Previously, when the user closed all tabs, the `ZimFileReader` was set to null. If the user restored the tabs, a new `ZimFileReader` was created, which was a resource-intensive operation, especially for large ZIM files.
* Now, the `ZimFileReader` is not set to null while the "restore tab" snackbar is visible, allowing users to restore tabs without recreating the ZimFileReader.
* Once the snackbar is dismissed, the `ZimFileReader` is set to null to free up resources since it is no longer required.
* Made the convertToBookOnDisk method suspend, as it creates the ZimFileReader object to convert the files into Books.

By doing the above changes now our UI is working flawlessly as there is no extra ZilFileReader creation happens. See the below video.

https://github.com/user-attachments/assets/d259f701-73a3-46f1-a411-92ea6846ae66

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt [hunk 1]
```diff
@@ -1721,7 +1733,7 @@ abstract class CoreReaderFragment :
     closeAllTabsButton?.isClickable = isClickable
   }
 
-  private fun restoreDeletedTabs() {
+  private suspend fun restoreDeletedTabs() {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt:1736]: There is also a leg while restoring all tabs if closed(which is obvious since it is preparing the zimFileReader on the IO thread). But the user is not aware of it so we should show some progress/something so that the user can know about what is going on. Also, if we move to any other fragment while in this process then the application crashes.


https://github.com/user-attachments/assets/5149e3d9-449f-4332-8f62-7e22db981184



```kotlin
FATAL EXCEPTION: main
                                                                                                    Process: org.kiwix.kiwixmobile, PID: 18742
                                                                                                    java.util.NoSuchElementException: List is empty.
                                                                                                    	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:418)
                                                                                                    	at org.kiwix.kiwixmobile.core.main.CoreReaderFragment.restoreDeletedTabs(CoreReaderFragment.kt:1746)
                                                                                                    	at org.kiwix.kiwixmobile.core.main.CoreReaderFragment.access$restoreDeletedTabs(CoreReaderFragment.kt:177)
                                                                                                    	at org.kiwix.kiwixmobile.core.main.CoreReaderFragment$restoreDeletedTabs$1.invokeSuspend(Unknown Source:18)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:808)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                                    	at android.os.Looper.loop(Looper.java:166)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7425)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowOpenNoteDialog.kt [hunk 2]
```diff
@@ -51,35 +54,37 @@ data class ShowOpenNoteDialog(
...
-            val urls = JSONArray()
-            val positions = JSONArray()
-            urls.put(CONTENT_PREFIX + zimReaderContainer.mainPage)
-            positions.put(0)
-            editor.putString(TAG_CURRENT_FILE, zimReaderContainer.zimCanonicalPath)
-            editor.putString(TAG_CURRENT_ARTICLES, "$urls")
-            editor.putString(TAG_CURRENT_POSITIONS, "$positions")
-            editor.putInt(TAG_CURRENT_TAB, 0)
-            editor.apply()
+        dialogScope.launch {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowOpenNoteDialog.kt:57]: There is also a delay in showing the notes dialog, if we open the note from `Notes Screen`(if note's zim file is not currently set in the `zimReaderContainer`).

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@CalebKL Thanks for the PR and your hard work. But there are some edge cases and crashes scenarios introduced we should fix them.

There is a crash when I frequently changed the zim files. Also, in UI there is old zim files loading when I am switching to other zim file which is bigger in size. I guess because of this, this crash is happening.

```
2024-07-16 14:20:19.873 12535-12609 libc                    org.kiwix.kiwixmobile                A  Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12609 (ThreadPoolForeg)
2024-07-16 14:20:19.875 12535-12602 ZimFileReader           org.kiwix.kiwixmobile                E  Could not get Item for url = https://kiwix.app/I/Flag_of_Greece.svg.png.webp 
                                                                                                     original exception = java.lang.Exception: Cannot find entry
2024-07-16 14:20:19.876 12535-12602 ZimFileReader           org.kiwix.kiwixmobile                D  getting mimetype for https://kiwix.app/I/Flag_of_Greece.svg.png.webp = null
2024-07-16 14:20:19.877 12535-12821 ZimFileReader           org.kiwix.kiwixmobile                E  Could not get Item for url = https://kiwix.app/I/Political_slogan_by_Red_Guards_on_the_campus_of_Fudan_University_1976.jpg.webp 
                                                                                                     original exception = java.lang.Exception: Cannot find entry
2024-07-16 14:20:19.898 12535-15737 ZimFileReader           org.kiwix.kiwixmobile                E  Could not get Item for url = https://kiwix.app/I/Flag_of_Greece.svg.png.webp 
                                                                                                     original exception = java.lang.Exception: Cannot find entry
2024-07-16 14:20:19.904 12535-12535 AppCompatViewInflater   org.kiwix.kiwixmobile                I  app:theme is now deprecated. Please move to using android:theme instead.
2024-07-16 14:20:19.911 12535-12535 CubicBezierInterpolator org.kiwix.kiwixmobile                D  CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
2024-07-16 14:20:19.912 12535-12535 CubicBezierInterpolator org.kiwix.kiwixmobile                D  CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
2024-07-16 14:20:19.913 12535-12535 CubicBezierInterpolator org.kiwix.kiwixmobile                D  CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
2024-07-16 14:20:19.913 12535-12535 CubicBezierInterpolator org.kiwix.kiwixmobile                D  CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
2024-07-16 14:20:20.129 17250-17250 DEBUG                   pid-17250                            A  pid: 12535, tid: 12609, name: ThreadPoolForeg  >>> org.kiwix.kiwixmobile <<<
2024-07-16 14:20:20.132 17250-17250 DEBUG                   pid-17250                            A      #00 pc 0000000000010630  /data/app/org.kiwix.kiwixmobile-G5GGa4VbPmK5Z5zSGKhzQw==/base.apk (offset 0x71f000)
2024-07-16 14:20:20.132 17250-17250 DEBUG                   pid-17250                            A      #01 pc 000000000005be38  /data/app/org.kiwix.kiwixmobile-G5GGa4VbPmK5Z5zSGKhzQw==/oat/arm64/base.odex (offset 0x46000)
```

**Comment by CalebKL** [comment]
@MohitMaliFtechiz When I switch to different zimFiles, I get this crash after numerous attempts. 
I am not sure if its the same crash you were referring to earlier. 

```shell
Cmdline: org.kiwix.kiwixmobile
2024-07-18 12:44:02.286  5611-5611  DEBUG                   pid-5611                             A  pid: 5387, tid: 5606, name: DefaultDispatch  >>> org.kiwix.kiwixmobile <<<
2024-07-18 12:44:02.286  5611-5611  DEBUG                   pid-5611                             A        #00 pc 0000000000010630  /data/app/~~2cz1tgEo0aQgZshuQoQHsg==/org.kiwix.kiwixmobile-ZpQbVVYb8qkV5KrowJ_Pfg==/base.apk!libzim_wrapper.so (offset 0x1b2a000) (Java_org_kiwix_libzim_Archive_getEntryByPath__Ljava_lang_String_2+120) (BuildId: bb96395f5068f1755a93f5daa08b7a934333f07e)
2024-07-18 12:44:02.286  5611-5611  DEBUG                   pid-5611                             A        #02 pc 00000000020ad728  /memfd:jit-cache (deleted) (offset 0x2000000) (org.kiwix.kiwixmobile.core.reader.ZimFileReader.getItem+376)
2024-07-18 12:44:02.286  5611-5611  DEBUG                   pid-5611                             A        #03 pc 000000000214569c  /memfd:jit-cache (deleted) (offset 0x2000000) (org.kiwix.kiwixmobile.core.reader.ZimFileReader.loadContent+204)
2024-07-18 12:44:02.286  5611-5611  DEBUG                   pid-5611                             A        #08 pc 0000000000008cd0  /data/data/org.kiwix.kiwixmobile/code_cache/.overlay/base.apk/classes13.dex (org.kiwix.kiwixmobile.core.reader.ZimFileReader.access$loadContent+0)
```

**Comment by MohitMaliFtechiz** [comment]
@CalebKL No it is not that crash i have uploaded the crash logs in the review comment.

Also, now on my device, it is crashing immediately when I switch to other zim files(I am using the old version of Android for testing Android 8).

```kotlin
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11992 (DefaultDispatch)
2024-07-18 16:33:50.291 12077-12077 DEBUG                   pid-12077                            A  pid: 11734, tid: 11992, name: DefaultDispatch  >>> org.kiwix.kiwixmobile <<<
2024-07-18 16:33:50.294 12077-12077 DEBUG                   pid-12077                            A      #00 pc 0000000000010630  /data/app/org.kiwix.kiwixmobile-YaobaHgoDzW2aibsfWri3g==/base.apk (offset 0x71f000)
2024-07-18 16:33:50.294 12077-12077 DEBUG                   pid-12077                            A      #01 pc 000000000005be38  /data/app/org.kiwix.kiwixmobile-YaobaHgoDzW2aibsfWri3g==/oat/arm64/base.odex (offset 0x46000)
```

In the CoreReaderFragment there is a `restore tabs` functionality also for opening the previous zim file and restoring the previous tabs, and their article opens in the webView(if we are not opening the new zim file).

Currently, it is somehow restoring the previous zim file and tabs when we open the new file. However, it should not do it according to our `openPageInBookFromNavigationArguments` method's logic. Can you please check this? It is the main reason for these crashes.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz When I switch to different zimFiles, I get this crash after numerous attempts.

This crash is newer, on which device you are testing.

**Comment by CalebKL** [comment]
> @CalebKL No it is not that crash i have uploaded the crash logs in the review comment.
> 
> Also, now on my device, it is crashing immediately when I switch to other zim files(I am using the old version of Android for testing Android 8).
> 
> ```kotlin
> Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11992 (DefaultDispatch)
> 2024-07-18 16:33:50.291 12077-12077 DEBUG                   pid-12077                            A  pid: 11734, tid: 11992, name: DefaultDispatch  >>> org.kiwix.kiwixmobile <<<
> 2024-07-18 16:33:50.294 12077-12077 DEBUG                   pid-12077                            A      #00 pc 0000000000010630  /data/app/org.kiwix.kiwixmobile-YaobaHgoDzW2aibsfWri3g==/base.apk (offset 0x71f000)
> 2024-07-18 16:33:50.294 12077-12077 DEBUG                   pid-12077                            A      #01 pc 000000000005be38  /data/app/org.kiwix.kiwixmobile-YaobaHgoDzW2aibsfWri3g==/oat/arm64/base.odex (offset 0x46000)
> ```
> 
> In the CoreReaderFragment there is a `restore tabs` functionality also for opening the previous zim file and restoring the previous tabs, and their article opens in the webView(if we are not opening the new zim file).
> 
> Currently, it is somehow restoring the previous zim file and tabs when we open the new file. However, it should not do it according to our `openPageInBookFromNavigationArguments` method's logic. Can you please check this? It is the main reason for these crashes.

let me look into this as well

**Comment by CalebKL** [comment]
> > @MohitMaliFtechiz When I switch to different zimFiles, I get this crash after numerous attempts.
> 
> This crash is newer, on which device you are testing.

Samsung S22+

**Comment by MohitMaliFtechiz** [comment]
@CalebKL Thanks, it is a native crash in libzim, but currently, our PR has many bugs and workarounds that can lead to this issue, so probably first we have to fix these things. @mgautierfr can have a better idea about this error when it occurs. Might be the data is corrupted at some point due to these scenarios.

**Comment by kelson42** [comment]
Any news here?

**Comment by CalebKL** [comment]
> Any news here?

There are some fixes that I am working on from @MohitMaliFtechiz reviews. I will complete it ASAP, although this PR will need to wait until the native error([3956](https://github.com/kiwix/kiwix-android/issues/3956)) causing the crash is fixed.

**Comment by MohitMaliFtechiz** [comment]
@CalebKL I have found some serious issues in our implementation, especially when working with `Coroutines`(in a multithreading environment). With the main thread, there are no issues because the implementation was made according to the main thread. But now we are moving to use the `Coroutines` in our code. The issue we are facing in this PR is related to https://github.com/kiwix/kiwix-android/issues/4104 which I have already fixed in https://github.com/kiwix/kiwix-android/pull/4105.

In the meantime, we have also improved our code. So now, we have a better routine implementation to create an archive object on the IO thread. Also, we have improved the UI side to properly show users the progress when the archive object is in the creation process: https://github.com/kiwix/kiwix-android/pull/4074.

So now, you can start working on my review comments.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please complete PR

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @CalebKL has started working on this issue. So let him complete this PR.

**Comment by kelson42** [comment]
5 months without activity, this is too long by far, it should be completed.

**Comment by CalebKL** [comment]
> 5 months without activity, this is too long by far, it should be completed.

Completing this ASAP

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please complete PR

File: core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowOpenNoteDialog.kt (hunk 2 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowOpenNoteDialog.kt]: Fixed in latest commit.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt (hunk 1 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt]: Fixed in latest commit.

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt [hunk 3]
```diff
@@ -154,14 +161,16 @@ class KiwixReaderFragment : CoreReaderFragment() {
...
       mainMenu?.showWebViewOptions(true)
-      if (webViewList.isEmpty()) {
-        exitBook()
-      } else {
-        // Reset the top margin of web views to 0 to remove any previously set margin
-        // This ensures that the web views are displayed without any additional
-        // top margin for kiwix main app.
-        setTopMarginToWebViews(0)
-        selectTab(currentWebViewIndex)
+      lifecycleScope.launch {
```
[the remark this answers is not in the document]
Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt]: Fixed in latest commit.

**Comment by MohitMaliFtechiz** [comment]
@CalebKL I have made the necessary changes, you can test and give your feedback.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please rebase

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Done.
