### PR TITLE
fix: Appended Device Details in the logs file as well

### LINKED ISSUE #2258: Diagnostic report integrity is not secured
Steps to reproduce:
* Ask for a send a diagnostic report
* Choose "Save to Drive" (Google)
* Save it

I get a file with the logs

I should get the whole diagnostic

### PR DESCRIPTION
**Pull request by s-ayush2903**
Close #2258 

* Appended the mail body and device configs to the logs file. 
* [Here](https://docs.google.com/document/d/186nqZb2TR55_DD_sOJzt8Yr9Ts7VwUE4SruJN96oI4g/edit?usp=sharing) is the current logs file.

**Screenshots** 
NA

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt [hunk 1]
```diff
@@ -113,7 +114,8 @@ open class ErrorActivity : BaseActivity() {
   ${if (allowZims.isChecked) zimFiles() else ""}
   ${if (allowLanguage.isChecked) languageLocale() else ""}
   ${if (allowDeviceDetails.isChecked) deviceDetails() else ""}
-  ${if (allowFileSystemDetails.isChecked) systemDetails() else ""}
+  ${if (allowFileSystemDetails.isChecked) systemDetails() else ""} 
+  ${"\n"}
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt:118]: you can just put a blank line here, the beauty of raw strings

File: core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt [hunk 2]
```diff
@@ -94,6 +94,7 @@ open class ErrorActivity : BaseActivity() {
       putExtra(Intent.EXTRA_TEXT, buildBody())
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt:94]: we can extract a variable for `buildBody()` so we don't need to construct it again

File: core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt [hunk 3]
```diff
@@ -113,7 +114,8 @@ open class ErrorActivity : BaseActivity() {
   ${if (allowZims.isChecked) zimFiles() else ""}
   ${if (allowLanguage.isChecked) languageLocale() else ""}
   ${if (allowDeviceDetails.isChecked) deviceDetails() else ""}
-  ${if (allowFileSystemDetails.isChecked) systemDetails() else ""}
+  ${if (allowFileSystemDetails.isChecked) systemDetails() else ""} 
+  ${""}
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt:118]: literally a blank line, you only need to use `${}` when you are accessing a property or method on a variable

eg:
image

File: core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt [hunk 4]
```diff
@@ -84,16 +84,18 @@ open class ErrorActivity : BaseActivity() {
   }
 
   private fun emailIntent(): Intent {
+    val fileContent = buildBody()
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt:87]: hmmm `fileContent`...technically true but only conditionally right? What it actually is is the body of the email and that is always the case

Comment (s-ayush2903) [reply core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt:87]: It isn't just the email-body but it contains more device info in comparison to that of _body material_, that's why I left it as to be the fileContent, it should've been if it contained only starting note stuff(like hi, hello etc.), I think . Views?

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt:87]: `putExtra(Intent.EXTRA_TEXT, fileContent)`

it is the body of the email, it just so happens that the body of the email contains info about the device which I find immaterial to the fact of it being the email contents.

`buildBody()` starts with `initialBody` aka 

```
  protected open val initialBody: String
    get() = """
      Hi Kiwix Developers!
      The Android app crashed, here are some details to help fix it:
      """.trimIndent()
```

I think what you are suggesting is a method `diagnosticDetails` that would encompass only these sections?
```
  ${if (allowCrash.isChecked && exception != null) exceptionDetails() else ""}
  ${if (allowZims.isChecked) zimFiles() else ""}
  ${if (allowLanguage.isChecked) languageLocale() else ""}
  ${if (allowDeviceDetails.isChecked) deviceDetails() else ""}
  ${if (allowFileSystemDetails.isChecked) systemDetails() else ""}
```

Regardless I am the consumer of this and I don't care about the log file having a tiny pre-amble. renaming to `emailBody` is sufficient

Comment (s-ayush2903) [reply core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt:87]: Okay fine, I'm convinced about it and understood too because of the exhaustive dissection provided.

**Review by macgills — APPROVED** [review]
all good just waiting on a green build
