### PR TITLE
#2203 Fullscreen Video does not display 

### LINKED ISSUE #2203: Fullscreen Video does not display
**Describe the bug**
Only a white screen is shown with no video or controls

**Expected behavior**

**Steps to reproduce the behavior:**
1. Open Mali les Pour les Nuls
1. click fullscreen on a video

### PR DESCRIPTION
**Pull request by macgills**
Fixes #2203 

- use activity_main_root

**Screenshots** 
image

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java [hunk 1]
```diff
@@ -333,7 +333,7 @@ public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceStat
   @Nullable @Override public View onCreateView(@NonNull LayoutInflater inflater,
     @Nullable ViewGroup container,
     @Nullable Bundle savedInstanceState) {
-    root = inflater.inflate(R.layout.fragment_main, container, false);
+    View root = inflater.inflate(R.layout.fragment_main, container, false);
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:336]: One of the `root`s should be renamed.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:336]: a commit is on its way
