### PR TITLE
Fixed: Version `3.9.1` was experiencing occasional crashes when setting the `SuggestionSearcher`.

### LINKED ISSUE #3643: Version `3.9.1` sometimes crashing while setting the `SuggestionSearcher`.
**Describe the bug**
The bug has been reported by the Play Store.

**Expected behavior**
it should not crash.

**Environment**
- Version of Kiwix Android: 3.9.1
- Device: OPPO OP4F83L1 (CPH2251)
- OS version: Android 12

**Logs**
```kotlin
pid: 0, tid: 21148 >>> org.kiwix.kiwixmobile <<<

backtrace:
  #00  pc 0x0000000000025464  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/split_config.arm64_v8a.apk!libzim_wrapper.so (Java_org_kiwix_libzim_SuggestionSearcher_setNativeSearcher+112) (BuildId: 6c0d6ee977af86c7d817e067ec4176543043faa4)
  #01  pc 0x0000000000026680  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.odex (art_jni_trampoline+128)
  #02  pc 0x00000000005ba6b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #03  pc 0x0000000000243b7e  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.vdex (org.kiwix.libzim.SuggestionSearcher.<init>+6)
  #04  pc 0x00000000005ba654  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #05  pc 0x0000000000221022  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.reader.ZimFileReader.<init>+34)
  #06  pc 0x00000000005bad58  /apex/com.android.art/lib64/libart.so (nterp_helper+5720)
  #07  pc 0x0000000000220a18  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.reader.ZimFileReader$Factory$Impl.create+72)
  #08  pc 0x00000000005bb474  /apex/com.android.art/lib64/libart.so (nterp_helper+7540)
  #09  pc 0x00000000002154a0  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.main.CoreReaderFragment.openAndSetInContainer$default+176)
  #10  pc 0x00000000005b9734  /apex/com.android.art/lib64/libart.so (nterp_helper+52)
  #11  pc 0x0000000000215802  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.main.CoreReaderFragment.openZimFile$default+114)
  #12  pc 0x00000000005b9734  /apex/com.android.art/lib64/libart.so (nterp_helper+52)
  #13  pc 0x000000000023d716  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.nav.destination.reader.KiwixReaderFragment.onNewIntent$enumunboxing$+166)
  #14  pc 0x00000000005bb474  /apex/com.android.art/lib64/libart.so (nterp_helper+7540)
  #15  pc 0x0000000000218f0e  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.main.NavigationHostFragment.onNewIntent$enumunboxing$+134)
  #16  pc 0x00000000005bb474  /apex/com.android.art/lib64/libart.so (nterp_helper+7540)
  #17  pc 0x0000000000211344  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.main.CoreMainActivity.onNewIntent+132)
  #18  pc 0x00000000005ba654  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #19  pc 0x00000000002397c2  /data/app/~~XpNvqzOWyVeCmo1-3zQ8Zg==/org.kiwix.kiwixmobile-09YHqXWEyerwxB3D8E3uSw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.main.KiwixMainActivity.onNewIntent+10)
  #20  pc 0x0000000000777fa0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.Instrumentation.callActivityOnNewIntent+64)
  #21  pc 0x0000000000778084  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.Instrumentation.callActivityOnNewIntent+196)
  #22  pc 0x000000000085a0bc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.deliverNewIntents+460)
  #23  pc 0x000000000087a348  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.handleNewIntent+328)
  #24  pc 0x0000000000a6a4b8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.NewIntentItem.execute+152)
  #25  pc 0x0000000000a560fc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.ActivityTransactionItem.execute+92)
  #26  pc 0x00000000007b0994  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.TransactionExecutor.executeCallbacks+580)
  #27  pc 0x00000000007b06d4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.TransactionExecutor.execute+740)
  #28  pc 0x0000000000854d44  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread$H.handleMessage+1268)
  #29  pc 0x0000000000b544a8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Handler.dispatchMessage+168)
  #30  pc 0x0000000000b57f88  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+1000)
  #31  pc 0x0000000000b57af8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+1112)
  #32  pc 0x000000000086e4cc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.main+2332)
  #33  pc 0x000000000033f080  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
  #34  pc 0x00000000003884dc  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1588)
  #35  pc 0x0000000000387e98  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32)
  #36  pc 0x00000000003946a8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+120)
  #37  pc 0x0000000000abd288  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136)
  #38  pc 0x0000000000ac88fc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3548)
  #39  pc 0x000000000033f080  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
  #40  pc 0x00000000004e1ea8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+728)
  #41  pc 0x000000000057b930  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+156)
  #42  pc 0x00000000000bfce8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120)
  #43  pc 0x00000000000cc444  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+852)
  #44  pc 0x0000000000002574  /system/bin/app_process64 (main+1300)
  #45  pc 0x0000000000084d70  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+96)
```

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3643 
The crashes occurred in the Play Store version due to insufficient permissions for opening a file via `fileDescriptor`. To address this issue, we have modified the implementation to use the `file` instead of `fileDescriptor`. This adjustment ensures smooth operation in the non-Play Store version where we have permission to open a file via its path. In the Play Store version, it will display a proper error message to the user, preventing errors thrown by libkiwix.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz You seems to imply that the root cause of these crash is in libkiwix but you propose a patch in Kiwix. To me this seems incoherent.

What is the precise and exact root cause of these crash scenarios?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz You seems to imply that the root cause of these crash is in libkiwix but you propose a patch in Kiwix. To me this seems incoherent.
What is the precise and exact root cause of these crash scenarios?

@kelson42, There are a few occurrences detected by playstore, this error is happening on the Play Store which has limited access to storage. We are experiencing the same issue with the same logs in #3636. Here in Play Store variant, since there are a few occurrences, it might be possible only a few users are using this feature of our application. When there is a permission-related issue `openAssetFileDescriptor` throws the `SecurityException`.

So to address this problem we have improved the exception handling on the Android side, and improved our `getAssetFileDescriptorFromUri` method, to catch the security exception thrown by this method when the URI has insufficient permission to open the `fileDescriptor` from it.
Now, we have improved this on the Android side to catch the security exception if there is a permission-related issue with the URI, and the other part we are trying to fix in #3636. Let me know, if still anything is unclear or if I missed something to explain.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I think the root problem is not well understand so far and I have therefore concern to merge a PR which might simply hide the issue.

**Comment by gouri-panda** [comment]
@kelson42 I think @MohitMaliFtechiz can't produce this bug and based on the log the playstore provided @MohitMaliFtechiz is trying to solve them. Both this and #3636 might solve this problem. If there's no error in the playstore in the future we'll guess it solved. @MohitMaliFtechiz am i right?

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda, I have added the check on `fileDescriptor` which checks if libkiwix can open the `fileDescriptor` or not before passing it to the `libkiwix` to avoid the crash thrown by the `libkiwix`. However, if we succeed in implementing https://github.com/kiwix/kiwix-android/pull/3636 then we can remove this check in the future but for now, we need this to avoid application crash.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Thanks! I'll look into that.

**Comment by kelson42** [comment]
#3636 is about opening ZIM files via filehandler. This should not happen in Kiwix (only in custom apps). So what is the root cause of the crashes we have here?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 We are using deep linking in our application for directly opening the externally downloaded ZIM file. We had an [seen issue](https://github.com/kiwix/kiwix-android/issues/1447) where we were not able to open the externally downloaded ZIM file for that issue we had introduced the opening ZIM file by fd [see](https://github.com/kiwix/kiwix-android/issues/1447#issuecomment-1801216999).

**Comment by MohitMaliFtechiz** [comment]
@kelson42 this functionality is working fine in the non-playstore variant. However, in play store variant, it is showing the `Failed to open file Please try looking for this file in the Device Tab of your Library` toast message since in this variant we don't have the access

https://github.com/kiwix/kiwix-android/blob/3f19f55b99c83152d9f6be2d910894c9409c8637/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt#L304

I got a new pixel 2 device today, and I have tested this scenario with that device and I can reproduce the bug on that device with the same logs.

```kotlin
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  Build fingerprint: 'google/lynx/lynx:14/UQ1A.231205.015/11084887:user/release-keys'
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  Revision: 'MP1.0'
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  ABI: 'arm64'
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  Timestamp: 2024-01-15 15:03:48.266380955+0530
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  Process uptime: 18s
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  Cmdline: org.kiwix.kiwixmobile
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  pid: 32558, tid: 32558, name: wix.kiwixmobile  >>> org.kiwix.kiwixmobile <<<
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  uid: 10372
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  Cause: null pointer dereference
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A      x0  0000000000000000  x1  000000005c000000  x2  b40000727b87d380  x3  000000000000004a
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A      x4  000000000000004a  x5  656c646e61486576  x6  656c646e61486576  x7  00000071ba4a8ff4
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A      x8  0c19bb479d82c700  x9  0c19bb479d82c700  x10 00000071bae03620  x11 0000007fc2bd4100
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A      x12 0000000000000001  x13 000000712c8e6cd4  x14 00000000000000a3  x15 0000007466c42a70
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A      x16 0000000000000001  x17 000000745f8e4900  x18 00000074661d6000  x19 b40000739b878530
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A      x20 0000007fc2bd437c  x21 0000007fc2bd4378  x22 000000712caf3c62  x23 0000000000002070
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A      x24 00000071ba9b0c80  x25 0000007fc2bd4390  x26 0000007fc2bd43a8  x27 0000007fc2bd4390
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A      x28 0000007fc2bd4290  x29 0000007fc2bd4270
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A      lr  00000071b5f2f464  sp  0000007fc2bd4230  pc  00000071b5f2f464  pst 0000000060001000
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  46 total frames
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A  backtrace:
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A        #00 pc 0000000000025464  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/base.apk!libzim_wrapper.so (offset 0x119e000) (Java_org_kiwix_libzim_SuggestionSearcher_setNativeSearcher+112) (BuildId: 6c0d6ee977af86c7d817e067ec4176543043faa4)
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A        #01 pc 0000000000355830  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.403   374-374   DEBUG                   pid-374                              A        #02 pc 00000000005ba6b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #03 pc 0000000000242c62  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/oat/arm64/base.vdex (org.kiwix.libzim.SuggestionSearcher.<init>+6)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #04 pc 00000000005ba654  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #05 pc 00000000002200fa  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.reader.ZimFileReader.<init>+34)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #06 pc 00000000005bad58  /apex/com.android.art/lib64/libart.so (nterp_helper+5720) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #07 pc 000000000021fad4  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.reader.ZimFileReader$Factory$Impl.create+72)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #08 pc 00000000005bb474  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #09 pc 0000000000214508  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.main.CoreReaderFragment.openAndSetInContainer$default+176)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #10 pc 00000000005b9734  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #11 pc 000000000021485a  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.main.CoreReaderFragment.openZimFile$default+114)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #12 pc 00000000005b9734  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #13 pc 000000000023c5e2  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.nav.destination.reader.KiwixReaderFragment.onNewIntent$enumunboxing$+166)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #14 pc 00000000005bb474  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #15 pc 0000000000217fbe  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.main.NavigationHostFragment.onNewIntent$enumunboxing$+134)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #16 pc 00000000005bb474  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #17 pc 0000000000210650  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.core.main.CoreMainActivity.onNewIntent+132)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #18 pc 00000000005ba654  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #19 pc 000000000023843a  /data/app/~~47c46jMWHkPfuKlhZIWq7A==/org.kiwix.kiwixmobile-QcJwRLIuFEQJJcKwmYHhGw==/oat/arm64/base.vdex (org.kiwix.kiwixmobile.main.KiwixMainActivity.onNewIntent+10)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #20 pc 0000000000632ffc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.Instrumentation.callActivityOnNewIntent+156)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #21 pc 0000000000633124  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.Instrumentation.callActivityOnNewIntent+180)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #22 pc 00000000006ffc7c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.deliverNewIntents+396)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #23 pc 000000000071c548  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.handleNewIntent+312)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #24 pc 00000000008df4a0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.NewIntentItem.execute+144)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #25 pc 00000000008caf1c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.ActivityTransactionItem.execute+92)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #26 pc 000000000066716c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.TransactionExecutor.executeCallbacks+572)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #27 pc 0000000000666ec4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.TransactionExecutor.execute+708)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #28 pc 00000000006fae68  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread$H.handleMessage+1464)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #29 pc 000000000096d298  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Handler.dispatchMessage+152)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #30 pc 0000000000970be4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+980)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #31 pc 0000000000970774  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+916)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #32 pc 00000000007127dc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.main+2028)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #33 pc 000000000033f080  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #34 pc 00000000003884dc  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1588) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #35 pc 0000000000387e98  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #36 pc 000000000031b038  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+120)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #37 pc 0000000000b60bb4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+116)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #38 pc 0000000000b6b738  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3208)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #39 pc 000000000033f080  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #40 pc 00000000004e1ea8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+728) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #41 pc 000000000057b930  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+156) (BuildId: 735f12f804f88d62a2cb437261076ff7)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #42 pc 00000000000daca8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+104) (BuildId: 04347e608daaf447fe7dabf331c4ff21)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #43 pc 00000000000e6e2c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+860) (BuildId: 04347e608daaf447fe7dabf331c4ff21)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #44 pc 000000000000254c  /system/bin/app_process64 (main+1260) (BuildId: e8762c072e6c37bb8093e340cc42e9f2)
2024-01-15 15:03:48.404   374-374   DEBUG                   pid-374                              A        #45 pc 00000000000546e8  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: 19c32900d9d702c303d2b4164fbba76c)
```

This PR resolved this crash and shows the `Failed to open file Please try looking for this file in the Device Tab of your Library` toast message since we does not have the permission to read the fd with the filePath.

**Comment by kelson42** [comment]
@MohitMaliFtechiz What you say here is in contradiction with what you say at #3636 where we fail there to open the Xapian index if ZIM file is open via fd even on a non playstore version. Please clarify.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have not said that this is not working on the non-playstore variant!! I have put the findings on #3636 for play store variant where we cannot directly access the storage.

[Please see point number 4](https://github.com/kiwix/kiwix-android/issues/3636#issuecomment-1873269686)

**Comment by kelson42** [comment]
@MohitMaliFtechiz OK, but here we are trying to fix a problem on the PS version, so we should not use fd as this is simply not working! We should rewrite the code to stop to do - or stop allowing to do so - so for PS version.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I understand your concern, I also try to make sure every feature works fine on every device, and for that, I test all functionality on different devices with different architectures.

> @MohitMaliFtechiz You should perfectly know already if a file can be open or not and how. You should not wait for an error at the libkiwix level and treat it. The libkiwix does not trigger any random error. Please secure you use procedures which work properly.

Most of the things are clear now after a conversation with @mgautierfr in #3628 and in this PR I am using the same way for validating the fd before opening the ZIM file in libkiwix to avoid this type of crash, and yes libkiwix is triggering the genuine error as libkiwix using the path to open fd for properly work with xapian. But for the PS variant, we can not do it.

> Both open-by-path and open-by-fd work perfectly fine is you understand them.

Yes, I understand how these functions are working they both need access to the file path to properly work with the Xapian and in the PS version we have this limitation that is why we are encountering this type of problem. But now we are not waiting for libkiwix error we are handling them on our end. 

> Otherwise open a bug in openzim/libkiwix.

Sorry for not opening the issue on the libkiwix repo I only ask @mgautierfr for the might possible solution for open Xapain without filepath in #3628, but now I opened a ticket in libzim for it https://github.com/openzim/libzim/issues/852.

**Comment by kelson42** [comment]
> Yes, I understand how these functions are working they both need access to the file path to properly work with the Xapian and in the PS version we have this limitation that is why we are encountering this type of problem. But now we are not waiting for libkiwix error we are handling them on our end.

Don't open a file via fd if this will generate an exception, this is what your fix should do. Not catching an exception.

**Comment by MohitMaliFtechiz** [comment]
> Don't open a file via fd if this will generate an exception, this is what your fix should do. Not catching an exception.

@kelson42 Let me explain what is going on in PS version.

In the PS version there is no way to open the ZIM file when a user tries to open this by just clicking on it, since we do not have permission to access that ZIM file via its path, whether we can open it via filePath or fileDescriptor both will throw permission denied exception. However, in the non PS version, there is no error while reading this by filePath or fileDescriptor we have the necessary permission for both. 

> Are you pointing to disabling this feature in the Play Store variant?

For this reason, I thought you asking for disabling the feature. But you were not pointing to this, so for this, we have to catch the exception as we can not open the ZIM file via both `filePath` and `fileDescriptor` in the PS variant, we are checking this before passing it to the libkiwix so that libkiwix will not throw any error.

let me know if anything is still unclear about this fix.

**Comment by gouri-panda** [comment]
@kelson42 Are you ok with the current solution? Then I can move on with the review.

**Comment by kelson42** [comment]
No! Confusing wxception mgmt with error mgmt is NOK. code should be adapted to avoid triggering this exception. Its trivial to do one way for PS version and another way for non PS version so user get the best.

**Comment by MohitMaliFtechiz** [comment]
> Don't open a file via fd if this will generate an exception, this is what your fix should do. Not catching an exception. code should be adapted to avoid triggering this exception.

@kelson42, @gouri-panda I have made the changes in the code according to your request.

**Comment by gouri-panda** [comment]
@MohitMaliDeveloper Thanks! sorry for being late in this thread! I'll look into that.

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt [hunk 1]
```diff
@@ -311,6 +307,28 @@ class KiwixReaderFragment : CoreReaderFragment() {
     return ShouldCall
   }
 
+  private fun getZimFileFromUri(
+    uri: Uri
+  ): File? {
+    val filePath = FileUtils.getLocalFilePathByUri(
+      requireActivity().applicationContext, uri
```
Comment (gouri-panda) [inline app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt:314]: @MohitMaliDeveloper we should add tests for this. Maybe in a new PR. This PR is too old now.

**Review by gouri-panda — APPROVED** [review]
@kelson42 LGTM!

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt (hunk 1 above)
Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt:314]: Okay sure.

Comment (kelson42) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt:314]: @MohitMaliDeveloper In such case, please update immediatly a new issue, I think this has not been done.
