### PR TITLE
#2110 Zoom controls disappeared in v3.3.1

### LINKED ISSUE #2110: Zoom controls disappeared in v3.3.1
I have upgraded Kiwix Android application to v3.3.1 yesterday and now none of the articles are readable, because the default text size is too small and the zoom controls disappeared from the Settings. Fortunately, apkpure hosts the previous versions, so I downgraded Kiwix to v3.2.1 and everything is perfect now.

**Expected behaviour**

Zoom controls should be present in the Settings menu, as in the previous versions.

**Steps to reproduce the behaviour:**
1. Try to read any article in WikiPedia and fail, because the text size is too small (if you read 2000 pages a day, you will soon notice the difference). Go to Settings and find that the Zoom control option is gone. Trying to "zoom in" by pinching the screen is not an option, obviously, because the text does not reflow, so parts of the page end up to the right of the screen and are invisible. And one cannot be expected to read gigabytes of data by scrolling all the time horizontally.

**Environment**
- Version of Kiwix Android : v3.3.1
- Device : Samsung Galaxy Tab S4
- OS version : Android 9

### PR DESCRIPTION
**Pull request by macgills**
Fixes #2110

 - upgrade preferences to androidx
 - add text zoom preference
 - observe preference in WebView

**Screenshots** 
cc1cfd63-941c-4540-bd76-2dd992a00695

### CODE REVIEW

File: buildSrc/src/main/kotlin/Versions.kt [hunk 1]
```diff
@@ -87,27 +84,27 @@ object Versions {
...
 
-  const val barista: String = "2.7.1" // available: "3.2.0"
+  const val barista: String = "2.7.1" // available: "3.5.0"
 
   const val xfetch2: String = "3.1.4"
 
   const val jsr305: String = "3.0.2"
 
-  const val ktlint: String = "0.36.0"
+  const val ktlint: String = "0.36.0" // available: "0.37.1"
```
Comment (abdulwd) [inline buildSrc/src/main/kotlin/Versions.kt:101]: Minor versions can be updated.

Comment (macgills) [reply buildSrc/src/main/kotlin/Versions.kt:101]: I'd prefer to do that in a separate update, upgrading ktlint could introduce extra noise and this is already a good deal noisier than I like because I upgraded to AS 4.0.0 and that enforced new lint rules, hence the `requireXXX()`s

**Comment by macgills** [comment]
I don't think the codefactor is valid here?

File: core/src/main/java/org/kiwix/kiwixmobile/core/settings/CustomSwitchPreference.java [hunk 2]
```diff
@@ -1,91 +0,0 @@
-/*
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/settings/CustomSwitchPreference.java:1]: Finally getting rid of this 🎉
