### PR TITLE
#1734 3.1.3 Crash Report: ConcurrentModificationException CoreMainAct…

### LINKED ISSUE #1734: 3.1.3 Crash Report: ConcurrentModificationException CoreMainActivity.sectionsLoaded
**Describe the bug**
Error in google play console

**Expected behavior**
A list being iterated should not be added to

**Logs**
```
java.util.ConcurrentModificationException: 

 
  at java.util.ArrayList$Itr.next (ArrayList.java:860)

 
  at org.kiwix.kiwixmobile.core.main.CoreMainActivity$4.sectionsLoaded (CoreMainActivity.java:374)

 
  at org.kiwix.kiwixmobile.core.main.DocumentParser$ParserCallback.lambda$stop$1 (DocumentParser.java:83)

 
  at org.kiwix.kiwixmobile.core.main.-$$Lambda$DocumentParser$ParserCallback$nmKDgZ-jP6YFR80cg8s_sC-WKxA.run (Unknown Source:2)
```

### PR DESCRIPTION
**Pull request by macgills**
…ivity.sectionsLoaded - emit copy of list

Fixes #1734

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/DocumentParser.java [hunk 1]
```diff
@@ -80,7 +80,10 @@ public void start() {
     @JavascriptInterface
     @SuppressWarnings("unused")
     public void stop() {
-      new Handler(Looper.getMainLooper()).post(() -> listener.sectionsLoaded(title, sections));
+      List<DocumentSection> listToBeSentToMainThread = new ArrayList<>();
+      listToBeSentToMainThread.addAll(sections);
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/DocumentParser.java]:
```suggestion
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/DocumentParser.java [hunk 2]
```diff
@@ -80,7 +80,10 @@ public void start() {
     @JavascriptInterface
     @SuppressWarnings("unused")
     public void stop() {
-      new Handler(Looper.getMainLooper()).post(() -> listener.sectionsLoaded(title, sections));
+      List<DocumentSection> listToBeSentToMainThread = new ArrayList<>();
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/DocumentParser.java]:
```suggestion
      List<DocumentSection> listToBeSentToMainThread = new ArrayList<>(sections);
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/DocumentParser.java [hunk 3]
```diff
@@ -80,12 +80,11 @@ public void start() {
     @JavascriptInterface
     @SuppressWarnings("unused")
     public void stop() {
-      List<DocumentSection> listToBeSentToMainThread = new ArrayList<>();
+      List<DocumentSection> listToBeSentToMainThread = new ArrayList<>(sections);
       listToBeSentToMainThread.addAll(sections);
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/DocumentParser.java]:
```suggestion
```
