### PR TITLE
Feature/frans lukas/2304 fix scroll start

### LINKED ISSUE #2304: Newly opened pages starts slightly scrolled.
**Describe the bug**

When entering any page of any book, the page is scrolled down by (about) the height of the toolbar. 

**Expected behavior**

When opening a new page, its scroll position should be zero. 

**Steps to reproduce the behavior:**
1. Open any book and any new page. 
2. Notice that the scroll position is not zero. 

**Screenshots**

Screenshot_1597912717

### PR DESCRIPTION
**Pull request by Frans-Lukas**
Fixes #2304 

Because our content frame lies within a NestedCoordinatorLayout, it freaks out in many ways. One of the ways is that it's position is a bit off to start with. To fix this I move all bars by 0 on web view initialization. This fixes the odd scrolling on startup. All moved views have a Y position of 0, and are moved in Y by 0 but for some reason this forces the content frame to position correctly in relation to the top toolbar.  If someone wants to do a deeper dive into why this is odd, I suggest you start with this answer https://stackoverflow.com/a/36663732/14053602 . Setting the content frames' behavior to `ScrollingViewBehavior` fixes the initial scrolling being weird, but adds other issues, such as an invisible toolbar being appended to below our top action bar. 

ezgif com-gif-maker

### CODE REVIEW

**Comment by Frans-Lukas** [comment]
Is the ` re-added toolbar hiding in overridden hideTabSwitcher` commit wrong here? It's so small but might be a problem in custom too, in which case it might need to be a `good first issue`?

**Comment by macgills** [comment]
Invisible toolbar?

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/ToolbarScrollingKiwixWebView.java [hunk 1]
```diff
@@ -51,6 +51,13 @@ public ToolbarScrollingKiwixWebView(Context context, WebViewCallback callback, A
     this.toolbarView = toolbarView;
     this.bottomBarView = bottomBarView;
     this.sharedPreferenceUtil = sharedPreferenceUtil;
+    // The webview needs to be scrolled with 0 to not be slightly hidden on startup.
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/ToolbarScrollingKiwixWebView.java:54]: I'd move this comment to a javadoc, also git blame provides us enough info because the commit has the ticket number in it but maybe that won't be preserved in a kotlin conversion?

**Comment by Frans-Lukas** [comment]
This is what the invisible toolbar looks like: 
Screenshot_1598434846

**Comment by macgills** [comment]
ah, well we can't introduce that, its much worse

**Review by macgills — APPROVED** [review]
