### PR TITLE
Fix app bar collapse when ZIM pages use internal scroll containers.

### LINKED ISSUE #4677: Freecodecamp sections doesn't collapse by default
Zim -- Freecodecamp

### PR DESCRIPTION
**Pull request by Piyush-Kumar-Mishra**
Fixes #4677 

This PR fixes an issue where the top and bottom app bars were not collapsing properly when opening certain ZIM files.

- Some pages use internal scroll containers instead of scrolling the WebView itself. In such cases, WebView.scrollY does not change, preventing the scroll behavior from updating the app bars.
- Added a View.OnTouchListener fallback to detect user scroll gestures when internal page scrolling is used.
- Extracted offset update logic into a reusable helper function to satisfy Detekt rules.

https://github.com/user-attachments/assets/1277b41b-31d7-41aa-9458-e86d12ffb92e

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt [hunk 1]
```diff
@@ -527,49 +532,111 @@ private fun ShowZIMFileContent(
...
-              FrameLayout.LayoutParams.MATCH_PARENT
-            )
-            addView(selectedWebView)
-          }
-        },
-        modifier = Modifier.fillMaxSize(),
-      )
+      false
     }
+    selectedWebView.setOnScrollChangeListener(scrollListener)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt]: @Piyush-Kumar-Mishra We don't need to set both listeners to webView. Since it handles the scrolling, it will collision the logic when both observe the scrolling event. Instead, we should only add a single listener. The current scrollListener does not observe the internal scrolling of the webView. So we should use the touchListener here.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt [hunk 2]
```diff
@@ -527,49 +532,111 @@ private fun ShowZIMFileContent(
...
+        factory = { context -> createWebViewContainer(selectedWebView, context) },
+        modifier = Modifier.fillMaxSize()
+      )
+    }
+  }
+}
+
+@OptIn(ExperimentalMaterial3Api::class)
+@Composable
+private fun WebViewScrollEffect(
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/ReaderScreen.kt]: The second thing, we recently improved the scrolling of webView, and we have created the `KiwixWebViewWithAppBarScrolling` composable, which efficiently handles the scrolling and hides/shows the bottomAppBar and topAppBar. So you just need to rebase your PR and update the logic there.

The new logic should be: You can directly copy/paste it into that composable and attach it to the webView.

```kotlin
@SuppressLint("ClickableViewAccessibility")
@OptIn(ExperimentalMaterial3Api::class)
private fun createTouchListener(
  topAppBarScrollBehavior: TopAppBarScrollBehavior,
  bottomAppBarScrollBehavior: BottomAppBarScrollBehavior,
  shouldUpdateScroll: MutableState<Boolean>,
  accumulatedScroll: () -> Float,
  updateAccumulatedScroll: (Float) -> Unit,
  scope: CoroutineScope,
  settleJob: MutableState<Job?>
): View.OnTouchListener {

  var lastY = 0f

  return View.OnTouchListener { _, event ->

    if (!shouldUpdateScroll.value) return@OnTouchListener false

    when (event.actionMasked) {

      MotionEvent.ACTION_DOWN -> {
        lastY = event.y
        settleJob.value?.cancel()
      }

      MotionEvent.ACTION_MOVE -> {
        val deltaY = event.y - lastY
        lastY = event.y
        val accumulated = accumulatedScroll() - (-deltaY)

        if (abs(accumulated) < MIN_SCROLL_DELTA) {
          updateAccumulatedScroll(accumulated)
          return@OnTouchListener false
        }

        val scroll = accumulated * SCROLL_CONSUME_FACTOR
        updateAccumulatedScroll(0f)

        consumeScroll(
          scroll,
          topAppBarScrollBehavior,
          bottomAppBarScrollBehavior
        )
      }

      MotionEvent.ACTION_UP,
      MotionEvent.ACTION_CANCEL -> {
        settleJob.value?.cancel()
        settleJob.value = scope.launch {
          delay(DEFAULT_SETTLE_DELAY)
          settleTopAppBarWithoutVelocity(topAppBarScrollBehavior)
          settleBottomAppBarWithoutVelocity(bottomAppBarScrollBehavior)
        }
      }
    }

    false
  }
}
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt [hunk 3]
```diff
@@ -125,6 +125,8 @@ open class KiwixWebView @SuppressLint("SetJavaScriptEnabled") constructor(
     return super.performLongClick()
   }
 
+  @Suppress("RedundantOverride")
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt:138]: You should add comments here so that devs can know about it why we are overriding this.

Something like:

```kotlin
 /**
   * We are overriding this because we are attaching the OnTouchListener on webView.
   * See [org.kiwix.kiwixmobile.core.ui.components.KiwixWebViewWithAppBarScrolling]
   */
  @Suppress("RedundantOverride")
  override fun performClick(): Boolean = super.performClick()
```

**Comment by Piyush-Kumar-Mishra** [comment]
@MohitMaliFtechiz
 Rebased the PR and updated the scroll handling to use KiwixWebViewWithAppBarScrolling with the new touch listener.

Also added comment  for performClick() override.

Please let me know if anything else needs improvement.

File: core/src/main/java/org/kiwix/kiwixmobile/core/ui/components/KiwixWebViewWithAppBarScrolling.kt [hunk 4]
```diff
@@ -103,36 +105,63 @@ fun KiwixWebViewWithAppBarScrolling(
...
-      settleBottomAppBarWithoutVelocity(bottomAppBarScrollBehavior)
+      MotionEvent.ACTION_DOWN -> {
+        lastY = event.y
+        settleJob.value?.cancel()
+      }
+
+      MotionEvent.ACTION_MOVE -> {
+        val deltaY = event.y - lastY
+        lastY = event.y
+        val accumulated = accumulatedScroll() - (-deltaY)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/ui/components/KiwixWebViewWithAppBarScrolling.kt]: @Piyush-Kumar-Mishra Now, the logic is good. But there is a codeFactor issue, which is correct. We should fix it.

Use 

```kotlin
val accumulated = accumulatedScroll() + deltaY
```

Instead of:

```kotlin
val accumulated = accumulatedScroll() - (-deltaY)
```

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@Piyush-Kumar-Mishra Need a small change, then we are good to merge.

**Review by MohitMaliFtechiz — APPROVED** [review]
@Piyush-Kumar-Mishra Thank you for making the changes. Once CI is green, we will merge.
