### PR TITLE
Fixed: Saving broken/internet files in storage.

### LINKED ISSUE #4607: Application is crashing while saving the image in `D3.js Docs` ZIM file.
**Describe the bug**
The application is crashing while saving the image in the `D3.js Docs` ZIM file.

**Expected behavior**
It should not crash; instead, it should save the image.

**Environment**
- Version of Kiwix Android : 4.0.0
- Device : Google Pixel 7a
- OS version : Android 16

https://github.com/user-attachments/assets/396f8789-9f02-4c6b-9916-07563dd62c33

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #4607 

When an image is on interne,t we are not loading that image, so when the user tries to save it. It saves inside the storage, which is wrong. Now, instead of saving a broken image or file, we show an error message to the user.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FileExtensions.kt [hunk 1]
```diff
@@ -37,3 +38,6 @@ suspend fun File.canReadFile(dispatcher: CoroutineDispatcher = Dispatchers.IO):
 
 suspend fun File.deleteFile(dispatcher: CoroutineDispatcher = Dispatchers.IO): Boolean =
   withContext(dispatcher) { delete() }
+
+suspend fun File.hasContent(dispatcher: CoroutineDispatcher = Dispatchers.IO): Boolean =
+  withContext(dispatcher) { isFileExist() && length() > ZERO }
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FileExtensions.kt:43]: @MohitMaliDeveloper I'm confused with the broken image comment. What happens if the file is corrupted?

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FileExtensions.kt:43]: @gouri-panda Here, corrupted means which files on the internet(not inside the ZIM file). We are not loading online resources, so they will not show in the reader(they are broken does not have any content), and if someone tries to save them, they should not save in the storage.
