### PR TITLE
Fixes #1886 Crash fixed in Notes

### LINKED ISSUE #1886: App crashing on pressing back button in Notes
**Describe the bug**

When someone presses the back button in the Notes page, app crashes.

**Expected behavior**

The notes should be saved and the page should leave the screen.

**Steps to reproduce the behavior:**
1. Click on the Notes option.
2. Click the back button.
3. App crashes.

**Screenshots**

[Link](https://imgur.com/gBWWDVz)

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi 4
- OS version : Nougat

**Logs**

2020-03-12 15:03:03.575 1510-1718/? E/WifiHAL: Received fatal event, sending alert
2020-03-12 15:05:41.115 22459-22459/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 22459
    java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Dialog org.kiwix.kiwixmobile.core.utils.DialogShower.create(org.kiwix.kiwixmobile.core.utils.KiwixDialog, kotlin.jvm.functions.Function0[])' on a null object reference
        at org.kiwix.kiwixmobile.core.main.ConfirmationAlertDialogFragment.onCreateDialog(ConfirmationAlertDialogFragment.java:65)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:403)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1484)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

### PR DESCRIPTION
**Pull request by sonusourav**
Fixes #1886 

## Changes
Added a new parameter in the constructor of `ConfirmationAlertDialogFragment`.

**Screenshots** 

[Link](https://imgur.com/URbRm3y)

### CODE REVIEW

**Comment by yashk2000** [comment]
@sonusourav while making prs, you can follow a more descriptive style for naming your branches as mentioned over [here](https://github.com/kiwix/kiwix-android/blob/develop/CONTRIBUTING.md#branching).

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java [hunk 1]
```diff
@@ -238,7 +238,7 @@ private void exitAddNoteDialog() {
       if (previousInstance == null) {
         // Custom AlertDialog for taking user confirmation before closing note dialog in case of unsaved changes
         DialogFragment newFragment = new ConfirmationAlertDialogFragment(sharedPreferenceUtil, TAG,
-          R.string.confirmation_alert_dialog_message);
+          R.string.confirmation_alert_dialog_message,getActivity());
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java]:
```suggestion
          R.string.confirmation_alert_dialog_message, getActivity());
```

Comment (sonusourav) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java]: Done

**Comment by macgills** [comment]
@sonusourav I believe you have `Rearrange code` enabled somewhere in your process. We do not dictate any specific field ordering in the project so ensure you are not changing them without good cause

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java [hunk 2]
```diff
@@ -49,14 +49,14 @@
...
-  protected DialogShower alertDialogShower;
+  protected AlertDialogShower alertDialogShower;
 
   public ConfirmationAlertDialogFragment(SharedPreferenceUtil sharedPreferenceUtil,
-    String parentDialogFragmentTAG, int stringResourceId) {
+    String parentDialogFragmentTAG, int stringResourceId, Activity activity) {
     this.sharedPreferenceUtil = sharedPreferenceUtil;
     this.parentDialogFragmentTAG = parentDialogFragmentTAG;
     this.stringResourceId = stringResourceId;
+    alertDialogShower = new AlertDialogShower(activity);
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: Nope, we use dagger to provide dependencies.

I shouldn't have allowed this constructor in the first place. Pass arguments to this fragment as a bundle and delete this constructor please.

Use dagger to inject AlertDialogShower.

Comment (sonusourav) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: Please review

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: My comment now is identical to the comment above

Comment (yash1ts) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: @sonusourav I think i got the problem with the DI of ConfirmationAlertDialog. If you are not working on this can i send a PR.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: @sonusourav any response for @yash1ts ?

Comment (sonusourav) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: @macgills I haven't used dagger before so exploring it took some time but got to learn something new and useful.
@yash1ts Hey it would be great if instead of opening a new PR, you can review or add your comments in this PR only. This is how we contribute and learn together in open source 😃

Comment (yash1ts) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: Ok cool .

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: I made a very long post about it in the `skillshare` channel on kiwix's slack, I don't know if it is visible to you?

The offical [docs](https://developer.android.com/training/dependency-injection) have also been updated late last year to not suck real bad

Comment (sonusourav) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: > 
> 
> I made a very long post about it in the `skillshare` channel on kiwix's slack, I don't know if it is visible to you?
> 
> The offical [docs](https://developer.android.com/training/dependency-injection) have also been updated late last year to not suck real bad

Hey I am not there in slack. If you could add me there, if would be great. Here is my email:
`sonusouravdx001@gmail.com`

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: @sonusourav https://join.slack.com/t/kiwixoffline/shared_invite/enQtOTUyMTg4NzMxMTM4LTU0MzYyZDliYjdmMDYzYWMzNDA0MDc4MWE5OGM0ODFhYjAxNWIxMjVjZTU4MTkyODJlZWFkMmQ2YTZkYTUzZDY

Comment (sonusourav) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: > 
> 
> Nope, we use dagger to provide dependencies.
> 
> I shouldn't have allowed this constructor in the first place. Pass arguments to this fragment as a bundle and delete this constructor please.
> 
> Use dagger to inject AlertDialogShower.

Not sure if this is what you requested! Please let me know if any changes are to be made.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java]: This still isn't what I want.

```
  public ConfirmationAlertDialogFragment(SharedPreferenceUtil sharedPreferenceUtil,
    String parentDialogFragmentTAG, int stringResourceId) {
    this.sharedPreferenceUtil = sharedPreferenceUtil;
    this.parentDialogFragmentTAG = parentDialogFragmentTAG;
    this.stringResourceId = stringResourceId;
  }
```

This constructor should not exist, the typical looking code for passing trivial things to a Fragment is the following
```
    /**
     * Create a new instance of DetailsFragment, initialized to
     * show the text at 'index'.
     */
    public static DetailsFragment newInstance(int index) {
        DetailsFragment f = new DetailsFragment();

        // Supply index input as an argument.
        Bundle args = new Bundle();
        args.putInt("index", index);
        f.setArguments(args);

        return f;
    }
```
[source](https://developer.android.com/reference/android/app/Fragment)

Should be noted this is how you would do it when I first started writing android, the way we should share data is through a ViewModel but we don't have to worry about that here because the data is not so important.

The DialogShower is null because `.inject(this)` has not been called in this class. If you have read my rant on the skillshare channel I am sure I said something like "marking a field inject does nothing, you have to ask dagger to put an object into the fields marked inject"

You can probably delete this entire class as all it does is show a dialog, you can just use DialogShower from AddNoteDialog.

**Comment by macgills** [comment]
@sonusourav do you have the availability to finish this PR?

**Comment by sonusourav** [comment]
> 
> 
> @sonusourav do you have the availability to finish this PR?

Hey @macgills , extremely sorry for the delay. I was busy writing my proposal so could not do it. I am on it and will get it done today at the earliest.

**Comment by macgills** [comment]
Good good, just making sure the pandemic isn't preventing you from working on it or indeed any number of other valid reasons.

**Comment by sonusourav** [comment]
> You can probably delete this entire class as all it does is show a dialog, you can just use DialogShower from AddNoteDialog.

Hey actually other activities are using `AlertDialogShower` so can't delete it. Rest please check.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java [hunk 3]
```diff
@@ -238,9 +239,11 @@ private void exitAddNoteDialog() {
         .findFragmentByTag(ConfirmationAlertDialogFragment.TAG);
 
       if (previousInstance == null) {
+        AlertDialogShower alertDialogShower = new AlertDialogShower(getActivity());
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java:242]: Must be instantiated by Dagger

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.java [hunk 4]
```diff
@@ -40,7 +41,7 @@
  */
 
 @Singleton
-public class SharedPreferenceUtil {
+public class SharedPreferenceUtil implements Serializable {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.java:44]: Do not make anything serializable in android ever. If you need to pass stuff around you use parcelable and even so you should not be passing this class or DialogShower around.

Serializable has awful performance impacts on Android.

**Comment by macgills** [comment]
>Hey actually other activities are using AlertDialogShower so can't delete it. Rest please check.

I meant delete `ConfirmationAlertDialogFragment` and

>just use DialogShower from AddNoteDialog.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java (hunk 3 above)
Comment (sonusourav) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java]: @macgills  The app is not building when I am adding the injection line i.e.
`  @Inject protected AlertDialogShower alertDialogShower;
`
Its throwing this error 

> D:\kiwix-android\core\src\main\java\org\kiwix\kiwixmobile\core\data\local\dao\BookDao.java:43: error: cannot find symbol
  private void setBookDetails(Book book, SquidCursor<BookDatabaseEntity> bookCursor) {
                                                     ^
  symbol:   class BookDatabaseEntity
  location: class BookDaoD:\kiwix-android\core\src\main\java\org\kiwix\kiwixmobile\core\data\local\dao\BookmarksDao.java:42: error: cannot find symbol
  public List<Bookmark> getBookmarks() {
              ^
  symbol:   class Bookmark
  location: class BookmarksDaoD:\kiwix-android\core\src\main\java\org\kiwix\kiwixmobile\core\data\local\dao\RecentSearchDao.java:45: error: cannot find symbol
  public List<RecentSearch> getRecentSearches() {
              ^
  symbol:   class RecentSearch


Could you please help to find what am I doing wrong?

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java [hunk 5]
```diff
@@ -97,6 +97,7 @@
 
   @Inject SharedPreferenceUtil sharedPreferenceUtil;
   @Inject ZimReaderContainer zimReaderContainer;
+  @Inject protected AlertDialogShower alertDialogShower;
```
Comment (sonusourav) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java:100]: If @Inject is added, the app does not build.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java:100]: For a very good reason, DialogModule should not be added to CoreComponent

Look at AlertDialogShower
`class AlertDialogShower @Inject constructor(private val activity: Activity) ` 
it needs an Activity to be constructed.

DialogModule is unfortunately a misdirection, this class should be deleted, it is not used anywhere.

ActivityModule is what you should be looking at because that is where we provide the binding of AlertDialogShower to the interface `DialogShower`

```
  @Binds
  @ActivityScope
  abstract fun bindDialogShower(alertDialogShower: AlertDialogShower): DialogShower
```

Because this class resides in core module we should look to `CoreActivityComponent`

When you create a `CoreActivityComponent` you pass in an activity
```
  @Subcomponent.Builder
  interface Builder {
    @BindsInstance
    fun activity(activity: Activity): CoreActivityComponent.Builder

    fun build(): CoreActivityComponent
  }
```

so whatever we define in the modules, if they need an activity they will get this one.

Now the issue becomes how do you create this component. I'll leave it as an exercise

Comment (sonusourav) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java:100]: Finally, I guess I have cracked it 😃 . Please check  it once.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java [hunk 6]
```diff
@@ -234,22 +236,20 @@ public void onBackPressed() {
...
+        dismissAddNoteDialog();
+        return Unit.INSTANCE;
+      });
     } else {
       // Closing unedited note dialog straightaway
       dismissAddNoteDialog();
     }
   }
 
+  protected void injection(@NonNull CoreComponent coreComponent) {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java:249]: this doesn't need to be protected, just an artifact of being copy pasted. You can just inline it, the original method is just a convenience because Activities are the most common place you have to call `inject` manually

Comment (sonusourav) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java]: Done. Please review.
