### PR TITLE
#2308 duplicate page fragments will no longer occur.

### LINKED ISSUE #2308: On re-opening of history/bookmarks after having opened a page from either of them, the back button requires a double click to work.
**Describe the bug**

The first click does nothing, and the second click works as expected. 

**Expected behavior**

The back button should always work on the first click.

**Steps to reproduce the behavior:**
1. Open history.
2. Select a page.
3. Re-open history.
4. Click back and notice that nothing happens.
5. Click back again, and see that it works as expected. 

**Screenshots**
This is what happens after step 2 from above, the first click is subtle: 

untitled

### PR DESCRIPTION
**Pull request by Frans-Lukas**
Fixes #2308

The page fragment was not popped from the fragment backstack when a page was opened. This is now fixed, which fixes the back button in the top action bar from requiring double taps if two page fragments are active. 

**Screenshots**

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/OpenPage.kt [hunk 1]
```diff
@@ -30,6 +31,7 @@ data class OpenPage(
 ) : SideEffect<Unit> {
   override fun invokeWith(activity: AppCompatActivity) {
     activity as CoreMainActivity
+    activity.popNavigationBackstack()
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/OpenPage.kt:34]: I would expect to see a unit test update for this added functionality in a SideEffect

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/OpenPage.kt:34]: @Frans-Lukas i am correct in thinking you won't have availability until next weekend? I can finish this up if needed

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/OpenPage.kt:34]: This seems like a quick fix. If you have the time, go ahead, if not, tell me and I'll do it tonight or tomorrow.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/OpenPage.kt:34]: I am eager to release so I'll add the test

**Review by macgills — APPROVED** [review]
