### PR TITLE
Hide Tab Switcher onBackPressed

### LINKED ISSUE #1057: Zim files go backward onBackpressed when TabSwitcher is visible
**Describe the bug**
When the user goes forward using links in Zim files (i.e. user have opened multiple pages of the same file in the same tab) and then tab switcher is showing then if the user presses the back button, Zim file goes backward.

**Expected behavior**
Upon pressing the back button,  tab Switcher should hide.

**Steps to reproduce the behavior:**
1. Open multiple pages of same Zim file.
2. Open tab switcher.
3. Press back button and observe Zim files go backward.

**Screenshots**
showtabswitcher

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Android Nougat 7.1

### PR DESCRIPTION
**Pull request by sonusourav**
Fixes #1057 

Changes:
1. Added one more switch case in the *onKeyDown* method that if Tab switcher is showing, hide it on pressing back button.

Screenshots/GIF for the change: 
hidetabswitcher

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java [hunk 1]
```diff
@@ -1130,7 +1130,10 @@ public boolean onKeyDown(int keyCode, KeyEvent event) {
     if (event.getAction() == KeyEvent.ACTION_DOWN) {
       switch (keyCode) {
         case KeyEvent.KEYCODE_BACK:
-          if (getCurrentWebView().canGoBack()) {
+          if (tabSwitcherRoot.getVisibility() == View.VISIBLE) {
+            selectTab(webViewList.size() - 1);
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: This will hide the tab switcher but will always take me to the last tab in the list. Instead it should take me to the last tab viewed before the tab switcher was opened. Google Chrome handles it in the same way.

Comment (sonusourav) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: @abdulwd  Now onBackpressed, last view tab will open. Please review it.
