### PR TITLE
#2463 Progress Bar Fixed in VideoView

### LINKED ISSUE #2463: ProgressBar and other stuff of VideoView doesn't show
**Describe the bug**
ProgessBar and other stuff of VideoView don't show after OnResume state of the application.

**Expected behavior**
Show ProgressBar and other visible stuff of video view after OnResume state of the application.

**Steps to reproduce the behavior:**
1. Open a video
2. Make sure Bottom navigation  is visible 
 while the video go to the full screen
3. Foreground the app.
4. Open The app
5. See the video view is now unresponsive.

**Environment**
- Version of Kiwix Android: develop
- Device: Real me
- OS version: 10

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes #2463

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt [hunk 1]
```diff
@@ -67,6 +67,7 @@ import java.io.File
 private const val HIDE_TAB_SWITCHER_DELAY: Long = 300
 
 class KiwixReaderFragment : CoreReaderFragment() {
+  private var isFullScreen: Boolean = false
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt:70]: maybe `isFullscreenVideo`, so as not to cause confusion with the separate fullscreen feature

**Review by macgills — APPROVED** [review]

**Review by abdulwd — APPROVED** [review]
