### PR TITLE
Enhancement in tests for reducing CI failure

### LINKED ISSUE #3128: Improvement/Enhancement in Tests for reducing  CI failure.
**Describe the bug**
Improvement/Enhancement in Test for better CI.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3128

### CODE REVIEW

File: app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt [hunk 1]
```diff
@@ -33,17 +33,24 @@ import org.kiwix.kiwixmobile.testutils.TestUtils.TEST_PAUSE_MS
...
+  @Rule
+  @JvmField
+  var activityTestRule = ActivityTestRule(
     KiwixMainActivity::class.java
   )
 
-  @Rule @JvmField var readPermissionRule: GrantPermissionRule =
+  @Rule
+  @JvmField
+  var readPermissionRule: GrantPermissionRule =
```
Comment (gouri-panda) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt:44]: @MohitMaliDeveloper Please commit the change code into the relevant commit. These code changes are unnecessary for this  PR and the commit as well.

File: app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroRobot.kt [hunk 2]
```diff
@@ -32,14 +32,12 @@ fun intro(func: IntroRobot.() -> Unit) = IntroRobot().applyWithViewHierarchyPrin
...
 
   private val getStarted = ViewId(R.id.get_started)
-  private val viewPager = ViewId(R.id.view_pager)
 
   fun swipeLeft() {
     isVisible(getStarted)
     isVisible(TextId(R.string.welcome_to_the_family))
     isVisible(TextId(R.string.humankind_knowledge))
     attempt(10) {
-      isVisible(viewPager).swipeLeft()
```
Comment (gouri-panda) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroRobot.kt:42]: Why are we removing this test?

File: app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt [hunk 3]
```diff
@@ -36,7 +32,7 @@ class LanguageRobot : BaseRobot() {
 
   fun waitForDataToLoad() {
     try {
-      isVisible(Findable.Text("Off the Grid"))
+      isVisible(Text("Off the Grid"))
```
Comment (gouri-panda) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt:35]: Here too.

File: app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt [hunk 4]
```diff
@@ -18,18 +18,31 @@
...
   fun verifyNoteFragment() {
-    UiThreadStatement.runOnUiThread { activityRule.activity.navigate(R.id.notesFragment) }
-    note {
-      assertNoteRecyclerViewExist()
-      assertSwitchWidgetExist()
+    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
+      UiThreadStatement.runOnUiThread { activityRule.activity.navigate(R.id.notesFragment) }
+      note {
+        assertToolbarExist()
+        assertNoteRecyclerViewExist()
```
Comment (gouri-panda) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt:43]: We should remove this check. I can't find the tickets to solve this kind of problem.

**Review by gouri-panda — CHANGES_REQUESTED** [review]
@MohitMaliDeveloper Thanks for the PR! I have requested some changes in order to clean this PR as well code base.

File: app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt (hunk 1 above)
Comment (MohitMaliFtechiz) [reply app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt:44]: hi @gouri-panda ,
i did this for project consistency. okay i'm reverting this

File: app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroRobot.kt (hunk 2 above)
Comment (MohitMaliFtechiz) [reply app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroRobot.kt:42]: hi @gouri-panda ,
i have removed this because  ```ViewPager``` is automatically swipe after some interval and sometimes this code leads to ```ViewNotFound Execption```.

File: app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt (hunk 1 above)
Comment (MohitMaliFtechiz) [reply app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt]: hi @gouri-panda , Done

File: app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt (hunk 3 above)
Comment (MohitMaliFtechiz) [reply app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt]: Done

File: app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt (hunk 4 above)
Comment (MohitMaliFtechiz) [reply app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt]: hi @gouri-panda , done

File: app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt (hunk 1 above)
Comment (gouri-panda) [reply app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt]: > i did this for project consistency. okay i'm reverting this

Yes!, if we are adding the codes. Changing the existing code without reason is overwhelming.

**Review by gouri-panda — APPROVED** [review]
@MohitMaliDeveloper Thanks!
