### PR TITLE
Fixed Media Saving Issue updated Test Cases

### LINKED ISSUE #4631: Media files don't save
**Describe the bug**
Photos or videos doesn't save in the device even though the prompt says 
**Expected behavior**
It should save in the device
**Steps to reproduce the behavior:**
1. Go to zim files
2. Find an image
3. Long click to save it
4. Search in the device

**Environment**
- Version of Kiwix Android : 3.14
- Device : Samsung
- OS version : 14

**Logs**

### PR DESCRIPTION
**Pull request by atharvyadav22**
Fixes: #4631

### What Changed?
- For Android 13+ MediaStore is used
- Used proper sealed classes to handle errors and file states
- Added logs to show proper downloading
- Used latest downloadRootDir code 
- Future robust if new files type is supported for download 
- Changed Images file location so it can be tracked by gallery app
- Updated test cases

### CODE REVIEW

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz @gouri-panda 
Please review took time so to understand the code and tried to avoid unnecessary changes

**Comment by atharvyadav22** [comment]
Test is failing with similar issue like for my earlier PR same issue with same code 

```
> Task :app:connectedDebugAndroidTest

org.kiwix.kiwixmobile.reader.KiwixReaderFragmentTest > testBase64ImageSaving[emulator-5554 - 13] FAILED 
	java.lang.AssertionError: Base64 image was not saved
	at org.kiwix.kiwixmobile.reader.KiwixReaderFragmentTest.waitForDownloadedImageFile(KiwixReaderFragmentTest.kt:376)
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 1]
```diff
@@ -696,63 +698,161 @@ object FileUtils {
...
-      File(
-        "${Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)}/org.kiwix"
-      ).apply {
-        if (!exists()) mkdir()
-      }
-    }
+  suspend fun getDownloadRootDir(
+    context: Context
+  ): File? {
+    val dir = context.getExternalFilesDir(null)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: @atharvyadav22 Why are you saving everthing inside `getExternalFilesDir`(it is private app directory)? It is an app-specific directory. Here we have discussed that the images should be saved inside the `Pictures` directory in the `Kiwix` folder so that they can easily be shown in the device's image viewer app. Other files should be saved in the same location where they are currently saved(externalMediaDirs, which is the public app-specific directory).

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt [hunk 2]
```diff
@@ -167,26 +168,46 @@ open class KiwixWebView @SuppressLint("SetJavaScriptEnabled") constructor(
...
+                appContext.getString(
+                  R.string.save_media_saved,
+                  result.displayName
+                )
+              )
+            }
+
+            is SaveResult.Error -> {
+              Log.e("MEDIA_SAVE", result.message, result.throwable)
+              appContext.toast(R.string.save_media_error)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt:218]: The error message is not generic here. What if the image is an internet image that we are not loading in our webView? We have an issue like this https://github.com/kiwix/kiwix-android/pull/4671. We should improve this error message for invalid files. And for other errors, we can show the current error message.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 3]
```diff
@@ -696,63 +698,161 @@ object FileUtils {
...
+
+    Log.e("MEDIA_SAVE", "base64 mime=$mime")
+
+    if (mime == "image/svg+xml") {
+      val dir = getDownloadRootDir(context)
+        ?: return SaveResult.Error("Download dir unavailable")
+
+      val file = File(dir, generateBase64FileName(extension))
+      file.writeBytes(bytes)
+      return SaveResult.FileSaved(file)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: Here, base64 is used for images, not for files like PDF, epub, etc. So we should return this as `MediaSaved` so it will save in the pictures directory.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 4]
```diff
@@ -696,63 +698,161 @@ object FileUtils {
...
+      ?: return SaveResult.Error("Invalid base64 data")
+
+    val (extension, bytes) = decoded
+
+    val mime = MimeTypeMap.getSingleton()
+      .getMimeTypeFromExtension(extension) ?: "application/octet-stream"
+
+    Log.e("MEDIA_SAVE", "base64 mime=$mime")
+
+    if (mime == "image/svg+xml") {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: Why are we matching for a specific extension here? It should save inside the `Pictures` directory. This condition should not be placed here.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 5]
```diff
@@ -696,63 +698,161 @@ object FileUtils {
...
+        ?: return SaveResult.Error("Download dir unavailable")
+
+      val file = File(dir, generateBase64FileName(extension))
+      file.writeBytes(bytes)
+      return SaveResult.FileSaved(file)
+    }
+
+    val uri = saveImageToMediaStore(
+      context,
+      generateBase64FileName(extension),
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: You are calling `generateBase64FileName(extension)` twice, one for saving the file and once for returning the `MediaSaved` result. It is wrong, it will give a different fileName. We should use the same file name.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 6]
```diff
@@ -696,63 +698,161 @@ object FileUtils {
...
-        }
+      val mime = MimeTypeMap.getSingleton()
+        .getMimeTypeFromExtension(
+          MimeTypeMap.getFileExtensionFromUrl(source)
+        ) ?: "application/octet-stream"
+
+      Log.e("MEDIA_SAVE", "mime=$mime")
+
+      // Saves Images
+      if (mime.startsWith("image/") && mime != "image/svg+xml") {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: How is the second condition different? Is `image/svg+xml` not an image?

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 7]
```diff
@@ -696,63 +698,161 @@ object FileUtils {
...
+        val uri = saveImageFromUrl(
+          source,
+          mime,
+          context,
+          zimReaderContainer
+        ) ?: return SaveResult.Error("MediaStore image save failed")
+
+        val name = URLUtil.guessFileName(source, null, null)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: Please don't use `URLUtils.guessFileName` directly; instead, use `getSafeFileNameAndSourceFromUrlOrSrc`. We've seen issues in the past and improved our codebase based on that. There are some comments mentioned in the codebase on that method see that.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@atharvyadav22 Thank you, and sorry for the late review. Please see the review changes.

**Comment by MohitMaliFtechiz** [comment]
> Test is failing with similar issue like for my earlier PR same issue with same code

@atharvyadav22 If the test is failing, that means there is something we are missing. Also, according to the new codebase, we should add test cases as well.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt [hunk 8]
```diff
@@ -165,28 +165,57 @@ open class KiwixWebView @SuppressLint("SetJavaScriptEnabled") constructor(
...
-    private val kiwixDataStore: KiwixDataStore
-  ) :
-    Handler(Looper.getMainLooper()) {
-    @SuppressWarnings("InjectDispatcher")
+    private val zimReaderContainer: ZimReaderContainer
+  ) : Handler(Looper.getMainLooper()) {
     override fun handleMessage(msg: Message) {
-      val url = msg.data.getString("url", null)
-      val src = msg.data.getString("src", null)
+      val url = msg.data.getString("url")
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt]: Use the previous `getString` method. That returns the `defaultValue` if there is no value available.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 9]
```diff
@@ -696,63 +709,187 @@ object FileUtils {
...
-      Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU
-    ) {
-      CoreApp.instance.externalMediaDirs.firstOrNull()
-    } else {
-      File(
-        "${Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)}/org.kiwix"
-      ).apply {
-        if (!exists()) mkdir()
-      }
+  @Suppress("Deprecation")
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: Do not use the deprecated methods for getting the storage.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 10]
```diff
@@ -696,63 +709,187 @@ object FileUtils {
...
+  private suspend fun getDownloadRootDir(
+    context: Context
+  ): File? {
+    return try {
+      val dir = context.getExternalFilesDir(null)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: As I have mentioned earlier. This will give us the app-specific private directory, which is not accessible in most file managers. So the user won't find the saved files. We should use `externalMediaDirs`, which is our public app-specific directory.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 11]
```diff
@@ -696,63 +709,187 @@ object FileUtils {
...
-    ) {
-      CoreApp.instance.externalMediaDirs.firstOrNull()
-    } else {
-      File(
-        "${Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)}/org.kiwix"
-      ).apply {
-        if (!exists()) mkdir()
-      }
+  @Suppress("Deprecation")
+  private suspend fun getDownloadRootDir(
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: The method name should be updated according to the new directory.

File: core/src/main/res/values/strings.xml [hunk 12]
```diff
@@ -17,6 +17,7 @@
   <string name="menu_wifi_hotspot">WiFi Hotspot</string>
   <string name="save_media">Save Media</string>
   <string name="save_media_error">An error occurred when trying to save the media!</string>
+  <string name="invalid_media_source">The selected media is invalid or unsupported.</string>
```
Comment (MohitMaliFtechiz) [inline core/src/main/res/values/strings.xml]: The message should be updated; it is unclear to users. It should show the proper error to the user. Like some file is an internet file, and we are not loading it in the application, so it is not found. So in this case, the error message should be "The selected media is not found". For normal error,s we are showing `save_media_error` message. See https://github.com/kiwix/kiwix-android/pull/4671 for more reference.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt [hunk 13]
```diff
@@ -28,12 +28,14 @@ import org.kiwix.kiwixmobile.core.R
...
-import org.kiwix.kiwixmobile.core.utils.files.FileUtils.downloadFileFromUrl
+import org.kiwix.kiwixmobile.core.utils.files.FileUtils
+import org.kiwix.kiwixmobile.core.utils.files.SaveResult
 import java.io.File
 import javax.inject.Inject
 
 class UnsupportedMimeTypeHandler @Inject constructor(
   private val activity: Activity,
+  @Suppress("UnusedPrivateProperty")
   private val kiwixDataStore: KiwixDataStore,
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt]: If it is unused, then we should remove this.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 14]
```diff
@@ -271,12 +273,23 @@ object FileUtils {
    * @return A `HashSet<String>` containing paths of available storage volumes.
    */
   private fun getStorageVolumesList(context: Context): HashSet<String> {
-    val storageVolumes = context.getSystemService(Context.STORAGE_SERVICE) as StorageManager
-    val storageVolumesList = HashSet<String>()
-    storageVolumes.storageVolumes.filterNotNull().forEach {
-      storageVolumesList.add(getStoragePath(context, it))
+    return try {
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: Good improvement 👏 . But the first try catch is unnecessary here.  As the `getSystemService` does not throw any error, it simply returns the list or null.

Image

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 15]
```diff
@@ -271,12 +273,23 @@ object FileUtils {
...
+      val storageManager =
+        context.getSystemService(Context.STORAGE_SERVICE) as? StorageManager ?: return hashSetOf()
+
+      val storageVolumesList = HashSet<String>()
+
+      storageManager.storageVolumes.filterNotNull().forEach {
+        try {
+          storageVolumesList.add(getStoragePath(context, it))
+        } catch (_: Exception) {
+        }
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: It will silently swallow the error, and will make debugging hard when there is an error in this area. Also, the logs will not be captured in the crash/diagnostic report. We should add a proper log here.

The method should be like this:

```kotlin
private fun getStorageVolumesList(context: Context): HashSet<String> {
    val storageVolumesList = HashSet<String>()
    val storageManager =
      context.getSystemService(Context.STORAGE_SERVICE) as? StorageManager
        ?: return storageVolumesList

    storageManager.storageVolumes.filterNotNull().forEach {
      try {
        storageVolumesList.add(getStoragePath(context, it))
      } catch (e: Exception) {
        Log.w("STORAGE_DEVICE", "Failed to get storage path for = $it", e)
      }
    }

    return storageVolumesList
  }
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 16]
```diff
@@ -696,63 +709,187 @@ object FileUtils {
...
+    bytes: ByteArray
+  ): Uri? {
+    val resolver = context.contentResolver
+
+    val values = ContentValues().apply {
+      put(MediaStore.Images.Media.DISPLAY_NAME, fileName)
+      put(MediaStore.Images.Media.MIME_TYPE, mime)
+
+      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
+        put(MediaStore.Images.Media.RELATIVE_PATH, "Pictures/Kiwix")
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt:896]: Where will the media be saved below `Android 10`?

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 17]
```diff
@@ -696,63 +709,187 @@ object FileUtils {
...
+      Log.w("MEDIA_SAVE", "Invalid media source after parsing")
+      return SaveResult.InvalidSource
+    }
+
+    return try {
+      when {
+        isImage(source) -> {
+          Log.d("MEDIA_SAVE", "Detected image: $fileName")
+
+          val bytes = zimReaderContainer
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: What if the written bytes are 0? We have seen an issue https://github.com/kiwix/kiwix-android/pull/4671.

File: app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt [hunk 18]
```diff
@@ -391,13 +392,14 @@ class FileUtilsInstrumentationTest {
...
+    val result = FileUtils.downloadFileFromUrl(
+      context = context!!,
       url = null,
       src = base64Jpeg,
-      zimReaderContainer = zimReader,
-      kiwixDataStore = kiwixDataStore
+      zimReaderContainer = zimReader
     )
 
+    Assertions.assertTrue(result is SaveResult.FileSaved || result is SaveResult.MediaSaved)
```
Comment (MohitMaliFtechiz) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt]: We should explicitly test these scenarios for FileSaved and MediaSaved.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@atharvyadav22 See the review changes.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt (hunk 10 above)
Comment (atharvyadav22) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: `externalMediaDirs` is deprecated ill use its latest api that why i used `@Suppress('Deprecation')` and yes i used wrong like i should have been used `getExternalMediaDir()` instead.
Thanks for pointing out 👍

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt (hunk 16 above)
Comment (atharvyadav22) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt:896]: according to the docs they dont need RELATIVE_PATH they gets saves in default DCMI
https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#RELATIVE_PATH

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt (hunk 13 above)
Comment (atharvyadav22) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt]: there are many places it has been used so i thought of not deleting it and in future it might be useful if we need it.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt]: If it is required in the future, we will add it. But for now, it is unused, so we should remove it.

Comment (atharvyadav22) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt]: Any thing more to change?

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 19]
```diff
@@ -696,63 +708,219 @@ object FileUtils {
...
-    ) {
-      CoreApp.instance.externalMediaDirs.firstOrNull()
-    } else {
-      File(
-        "${Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)}/org.kiwix"
-      ).apply {
-        if (!exists()) mkdir()
+  @Suppress("ReturnCount")
+  private fun getDownloadRootDir(context: Context): File? {
+    val root = context.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: This saves the files under the `/storage/emulated/0/Android/data/org.kiwix.kiwixmobile/files/Download/Kiwix/`. Before we were using the `CoreApp.instance.externalMediaDirs.firstOrNull()`, which returns the `/storage/emulated/0/Android/media/org.kiwix.kiwixmobile/`.

For the latest version of this method, you should use the `ContextWrapper(context).externalMediaDirs`.

The current method you are using is internal to the app and can not be accessed by the user. I have pointed this thing out in an earlier review.


If anything is unclear to you, please ask before making the changes, as it will save time for both of us.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt (hunk 19 above)
Comment (atharvyadav22) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: Sorry ! can you please tell what else do i have to do ill  first discuss and then make changes accordingly.
Thanks

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: The other part of the code is good. But this change breaks our functionality from a user perspective. The user could not see the saved files since those will go inside the app-specific private directory.

According to the new functionality of this method, the name should be updated. Also, we should test scenarios which I have requested previously.

Rebase your PR as well.

File: app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt [hunk 20]
```diff
@@ -378,9 +378,7 @@ class FileUtilsInstrumentationTest {
       zimReaderContainer = mockk(relaxed = true)
     )
 
-    Assertions.assertTrue(
-      result is SaveResult.Error || result is SaveResult.InvalidSource
-    )
+    Assertions.assertTrue(result === SaveResult.InvalidSource)
```
Comment (atharvyadav22) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt]: I have made Test changes an zero bytes too what new test case to be added ?

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt (hunk 19 above)
Comment (atharvyadav22) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: > 

Images and Base64 are now storing via MediaStore only it saves now in for Android 10+ in `Pictures/Kiwix `  below it `/sotrage/emulated/0/` so it will still show in Gallery also i think it is good location its upon you i can change that path too?

For Files(Zim, epub, etc) irrespective of Android version `/storage/emulated/0/Android/media/org.kiwix.kiwismobile/`

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz when i commited all CI was green before so is new CI fixed ?

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22 Yes, the CI should be green now unless there is some real issue in your PR. Rebase your PR, and the CI will green.

**Comment by atharvyadav22** [comment]
> @atharvyadav22 Yes, the CI should be green now unless there is some real issue in your PR. Rebase your PR, and the CI will green.

i have left comments too about the changes please review.

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22 I have already reviewed your PR. There are no new changes I am seeing. Have you pushed your code?

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz 

for you question i have already responsed this i guess you missed it 

Images and Base64 are now storing via MediaStore only it saves now in for Android 10+ in `Pictures/Kiwix` below it `/sotrage/emulated/0/` so it will still show in Gallery also i think it is good location its upon you i can change that path too?

For Files(Zim, epub, etc) irrespective of Android version` /storage/emulated/0/Android/media/org.kiwix.kiwismobile/`

after this there is nothing left

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt (hunk 19 above)
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: I don't understand how this is storing in the `/storage/emulated/0/Android/media/org.kiwix.kiwixmobile/`. I have clearly given you an example with proper paths.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

**Comment by MohitMaliFtechiz** [comment]
> Images and Base64 are now storing via MediaStore only it saves now in for Android 10+ in Pictures/Kiwix below it /sotrage/emulated/0/ so it will still show in Gallery also i think it is good location its upon you i can change that path too?

No, I am not asking you to change that. As it already shows inside the gallery.

> For Files(Zim, epub, etc) irrespective of Android version /storage/emulated/0/Android/media/org.kiwix.kiwismobile/

For this, see the review change.

> after this there is nothing left

Have you at least tested the code where it is saving the files?

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz CI is failing for my new test i tried to fix it but not sure whats the issue. all other tests were working what should i do like changes are been made according to review

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22 I will take charge from here. Thank you for making the review changes.

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz i have added new test case here for Pdf and its failing so should i ignore it like rest all things are done as per review.

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22 Why are you adding that here? It is not related to PDF. Also, where did you see the failure? Can you please point it out?

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz Ready now please check

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt [hunk 21]
```diff
@@ -177,28 +177,57 @@ open class KiwixWebView @SuppressLint("SetJavaScriptEnabled") constructor(
...
-          savedFile?.let {
-            applicationContextForLanguage.toast(
-              applicationContextForLanguage.getString(R.string.save_media_saved, it.name)
-            ).also {
-              Log.e("savedFile", "handleMessage: ${savedFile.isFile} ${savedFile.path}")
+          when (result) {
+            is SaveResult.MediaSaved -> {
+              appContext.toast(
+                appContext.getString(
+                  R.string.save_media_saved,
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt:193]: This message should be updated. It is showing the static `Download` path. We should show the actual fileSaved path.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt [hunk 22]
```diff
@@ -177,28 +177,57 @@ open class KiwixWebView @SuppressLint("SetJavaScriptEnabled") constructor(
...
+                  result.displayName
+                )
+              )
+            }
+
+            is SaveResult.FileSaved -> {
+              appContext.toast(
+                appContext.getString(
+                  R.string.save_media_saved,
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt:202]: Here too.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt (hunk 2 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt:218]: This comment has not been taken.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt (hunk 13 above)
Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt]: This comment also not been taken.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt [hunk 23]
```diff
@@ -64,21 +66,45 @@ class UnsupportedMimeTypeHandler @Inject constructor(
...
+                result.file.name
+              )
+            )
           }
         }
-      } ?: run {
-        activity.toast(R.string.save_media_error)
+
+        is SaveResult.MediaSaved -> {
+          activity.toast(
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/UnsupportedMimeTypeHandler.kt]: If the user presses the "OPEN" button, then it should be open in the dedicated app as we are doing in the `FileSaved`.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt [hunk 24]
```diff
@@ -177,28 +177,57 @@ open class KiwixWebView @SuppressLint("SetJavaScriptEnabled") constructor(
...
+                  result.file.name
+                )
+              )
+            }
+
+            is SaveResult.InvalidSource -> {
+              appContext.toast(
+                appContext.getString(
+                  R.string.error_file_invalid,
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt]: We are showing the wrong error message here. It shows `Error: The selected file is not a valid ZIM file.` which is wrong here. The ZIM file is valid; the image/file is invalid.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 25]
```diff
@@ -701,63 +713,221 @@ object FileUtils {
...
+          Log.d("MEDIA_SAVE", "Detected image: $fileName")
+
+          val bytes = zimReaderContainer
+            .load(source, emptyMap())
+            .data
+            .readBytes()
+
+          if (bytes.isEmpty()) {
+            Log.w("MEDIA_SAVE", "Loaded image bytes are empty for source=$source")
+            return SaveResult.Error("Empty image data")
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt]: Here we should show the proper error message to the user when the downloading media is not found in the ZIM file.

`R.string.invalid_media_source` this message should be show to user.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 26]
```diff
@@ -701,63 +713,221 @@ object FileUtils {
...
+  }
+
+  @Suppress("ReturnCount")
+  private suspend fun saveFileFromUrl(
+    context: Context,
+    source: String,
+    fileName: String,
+    zimReaderContainer: ZimReaderContainer
+  ): File? {
+    val root = getKiwixFileDir(context)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt:930]: If this is null, then returning null will show the error message to user which is correct.

File: core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt [hunk 27]
```diff
@@ -701,63 +713,221 @@ object FileUtils {
...
+    val file = File(root, fileName)
+
+    zimReaderContainer.load(source, emptyMap()).data.use { input ->
+      file.outputStream().use { output ->
+        input.copyTo(output)
+      }
+    }
+
+    if (!file.exists() || file.length() == 0L) {
+      Log.e("MEDIA_SAVE", "Saved file is empty or missing: ${file.absolutePath}")
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt:942]: But in this case, we are already showing the same error message, which is wrong. Because the saving file is not available in a ZIM file. So here, we should show the proper message.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz Done with changes and CI is also Green now !

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz if we are launching PlayStore variant then ig we must address this. I'll solve any review comments fastly so it helps in launching faster.
Thanks

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@atharvyadav22 There are still some issues in your codebase. I have fixed them. Please write test cases for them if they have not already been written. I have not added the test cases; I have only fixed the code issues in https://github.com/kiwix/kiwix-android/pull/4664/commits/bc96a136c3eaadf0b18fde3169491a3442da6586.

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz i have added additional test cases for ZeroBytes, Svg, Epub now. CI is failing for different issue not sure about other PR if this failure persists.
Thanks.

File: app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt [hunk 28]
```diff
@@ -657,6 +660,85 @@ class FileUtilsInstrumentationTest {
...
+    Assertions.assertTrue(
+      (result as SaveResult.MediaSaved).displayName.endsWith(".svg")
+    )
+  }
+
+  @Test
+  fun testEpubRoutesToFileSavedNotImagePath() = runTest {
+    if (Build.VERSION.SDK_INT == Build.VERSION_CODES.N_MR1) return@runTest
+
+    val epubBytes = FileUtilsInstrumentationTest::class.java.classLoader
```
Comment (MohitMaliFtechiz) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt]: For testing the new approaches introduced. We should add unit test cases, not the UI test cases. In unit test cases, we can test more scenarios and edge cases.

Additionally, this is a code test here; no UI is involved in this. So UI test is not suitable for this.

When we write the unit test cases for these, we don't need to add `test.epub` and `test.png` files in project. So remove your last commit(with rebase).

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz 
Too me long as there we many nested logic for testing, covered majority of them.
Now you would ask me questions answering them beforehand.
1. purposely not made helper function for comman code to increase readability and also for future if we change logic for FileUtils and something breaks only affected code will be failed. what say about this?
2. for that `externalFileDir `its deprecated but since our `FileUtils `has that so i kept the same exactly.

also i have tried many new things from my previous test that i learned so could you give me an feedback about the code i wrote, your suggestion would help me make an better engineer.
Thanks.

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz 
Since there were new merge from `FileUtils` we should consider that and look for redundant test cases. I'll do it according to our new logic.

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz Done completely with all the changes all the Test Files are according to our new `FileUtils` .

File: app/src/androidTest/java/org/kiwix/kiwixmobile/utils/UnsupportedMimeTypeHandlerTest.kt [hunk 29]
```diff
@@ -57,7 +57,6 @@ class UnsupportedMimeTypeHandlerTest {
   private val unsupportedMimeTypeHandler =
     UnsupportedMimeTypeHandler(
       activity,
-      kiwixDataStore,
       zimReaderContainer
     ).apply {
       setAlertDialogShower(alertDialogShower)
```
Comment (MohitMaliFtechiz) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/utils/UnsupportedMimeTypeHandlerTest.kt]: We have changed the logic of `UnsupportedMimeTypeHandler` class. There are different scenarios for different file types and `InvalidSource`, `Error`. We should test those sceanrios as well.

File: app/src/androidTest/java/org/kiwix/kiwixmobile/utils/UnsupportedMimeTypeHandlerTest.kt [hunk 30]
```diff
@@ -57,7 +57,6 @@ class UnsupportedMimeTypeHandlerTest {
   private val unsupportedMimeTypeHandler =
     UnsupportedMimeTypeHandler(
       activity,
-      kiwixDataStore,
       zimReaderContainer
```
Comment (MohitMaliFtechiz) [inline app/src/androidTest/java/org/kiwix/kiwixmobile/utils/UnsupportedMimeTypeHandlerTest.kt]: We have changed the logic of `UnsupportedMimeTypeHandler` class. There are different scenarios for different file types and `InvalidSource`, `Error`. We should test those sceanrios as well.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

File: app/src/androidTest/java/org/kiwix/kiwixmobile/utils/UnsupportedMimeTypeHandlerTest.kt (hunk 30 above)
Comment (atharvyadav22) [reply app/src/androidTest/java/org/kiwix/kiwixmobile/utils/UnsupportedMimeTypeHandlerTest.kt]: Yes! Thank You, I'll cover that too.
BTW are other tests fine ?

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz 
Actually for that `FileUtilsTest` other than redundant code cases the code was written according to old methods also they used `runBlocking `and all stuff so i'll replace and use best practices.
Thanks.

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz 
Moved `UnsupportedTypeMimeHandlerTest` to unit test fix that text cases they were broken also added few new ones as you said.
`FileUtilsTest` was also broken for new code.
Additionally ran `FileUtilsInstrumentation` code it's fine too. 
I consider the coverage also here. 
Thanks. 

IMG_20260407_195459

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz 
CI is stuck on this report there must be an problem i suppose.
CI is passed anyway so ready for review.
Thanks.

**Review by MohitMaliFtechiz — APPROVED** [review]
@atharvyadav22 Thank you 🎉 🎉 . It's been a long effort.
