### PR TITLE
Fix: App minimizing on back pressed in fullscreen mode

### LINKED ISSUE #569: App directly minimizes on back pressed in full-screen mode
### Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * version of the software you use : 2.3 build 55
  * device / operating system : Motorola E3 Power, Android version 6.0
  
### The Bug:

  * What do you obtain? A copy of the error message or a screenshot is always useful.

    When in full-screen mode, if back button is pressed, the app directly minimizes.

  * When does this occur? 

#### Steps to reproduce:

  1. Open any screen (hep or content) in full-screen mode
  2. Press back button
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

    The expected behavior should be just to exit to the full-screen mode. Now, this can be implemented 2 ways:

- Just exit the full-screen mode like this:

**OR**

- Go back till the parent WebView and then exit the full-screen like this:

Which one should I go with? @mhutti1 @srv-twry Open to your reviews. Others can say their minds as well.

### PR DESCRIPTION
**Pull request by brijeshshah13**
Fixes #569.

Changes: Implemented the back button action using `onKeyDown()` to support going back till the parent WebView and then exit the full-screen.

Screenshots/GIF for the change: Attached in the issue itself.

### CODE REVIEW

**Comment by brijeshshah13** [comment]
@mhutti1 I think I'm having a bad time with Travis builds 😅. Yet again, the build is failing for the same reason, however the PR can be merged.

File: app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java [hunk 1]
```diff
@@ -1160,7 +1160,11 @@ public boolean onKeyDown(int keyCode, KeyEvent event) {
         case KeyEvent.KEYCODE_BACK:
           if (getCurrentWebView().canGoBack()) {
             getCurrentWebView().goBack();
-          } else {
+          }
+          else if (isFullscreenOpened){
```
Comment (srv-twry) [inline app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java]: Please move ```else if ``` on the previous line and add space before ```{```

File: app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java [hunk 2]
```diff
@@ -1160,7 +1160,11 @@ public boolean onKeyDown(int keyCode, KeyEvent event) {
...
+            closeFullScreen();
+          }
+          else {
```
Comment (srv-twry) [inline app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java]: Similarly here also.
