### PR TITLE
Fixes of files which are too big to be downloaded in the local storage should be greyed

### LINKED ISSUE #2639: Files which are too big to be downloaded in the local storage should be greyed
Exactly like the 4GB+ files if the storage has a fat32 file system.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2639 

* I have added a condition for both internal and external storage. if file system is OK but device has not enough space then ZIM file will showing as grey.
* I have added a new condition on grey view. If ZIM file showing as grey(this means device has not enough space in storage (But ZIM file can be download) which might be internal or external). Then user can long click on grey zim file, it shows a storage selection dialog (like previously showing when we clicking on zim file).

**For Internal Storage**

https://user-images.githubusercontent.com/34593983/217218341-ae428202-a8b2-45a3-bf0d-fb71d8443b7f.mp4

**For External Storage**

https://user-images.githubusercontent.com/34593983/217218892-af801fcd-6de3-4cdc-b520-ba15f5911fef.mp4

* Fixed downloading start after clicking on storage selection dialog if device has not enough storage.

### CODE REVIEW

**Comment by kelson42** [comment]
>     * I have placed a condition if files are bigger then `4GB`. So books will showing grey (in both Internal and external storage), exactly like the 4GB  files if the storage has a `Fat32` file system.

Why, this makes impossible to download 4GB+ files event if the filesystem is OK and there is enough free space?
 
>     * If books are grey (More then 4GB) so i had modified the `Long click method` (if book can be downloaded then downloading will automatically starts.)

Why, these books which can not be saved on the filesystem shoudl never be downloaded, this is the point of this ticket.

I believe the ticket has not been understood.

**Comment by MohitMaliFtechiz** [comment]
> > ```
> > * I have placed a condition if files are bigger then `4GB`. So books will showing grey (in both Internal and external storage), exactly like the 4GB  files if the storage has a `Fat32` file system.
> > ```
> 
> Why, this makes impossible to download 4GB+ files event if the filesystem is OK and there is enough free space?
> 
> > ```
> > * If books are grey (More then 4GB) so i had modified the `Long click method` (if book can be downloaded then downloading will automatically starts.)
> > ```
> 
> Why, these books which can not be saved on the filesystem shoudl never be downloaded, this is the point of this ticket.
> 
> I believe the ticket has not been understood.

Yes i think i have misunderstood this ticket will update the work soon. Thanks for reveiwing.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I see you have fixed something…. But how does it work now? Why we don’t have a description update?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz I see you have fixed something…. But how does it work now? Why we don’t have a description update?

hi @kelson42 , I have already updated the description with new workflow (also attached the videos of new workflow). is i'm missing something?

**Comment by kelson42** [comment]
> > @MohitMaliFtechiz I see you have fixed something…. But how does it work now? Why we don’t have a description update?
> 
> hi @kelson42 , I have already updated the description with new workflow (also attached the videos of new workflow). am i missing something?

OK, updade of pre-existing text is not obvious to track down, in particular on mobile. Thy for it, just make a clear statment about that next time please.

**Comment by kelson42** [comment]
@gouri-panda Any updaze on the review?

File: app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt [hunk 1]
```diff
@@ -60,21 +62,30 @@ sealed class LibraryViewHolder<in T : LibraryListItem>(containerView: View) :
...
-          when (item.fileSystemState) {
-            CannotWrite4GbFile -> R.string.file_system_does_not_support_4gb
-            Unknown -> R.string.detecting_file_system
-            else -> throw RuntimeException("impossible invalid state: ${item.fileSystemState}")
+        when (item.fileSystemState) {
+          CannotWrite4GbFile -> it.centreToast(R.string.file_system_does_not_support_4gb)
+          Unknown -> it.centreToast(R.string.detecting_file_system)
+          else -> {
+            if (item.canBeDownloaded && !hasAvailableSpaceInStorage) {
+              clickAction.invoke(item)
```
Comment (gouri-panda) [inline app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt:83]: We should name these types more accurately. Here we don't know the difference between `Unknown` and `else`. We should add more accurate names.

**Review by gouri-panda — COMMENTED** [review]
@MohitMaliDeveloper I have tested with my device which has exFat file system. I don't have a fat32 file system device. Besides that, it works fine with my device. And It will be better if we add some tests for this.

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda , @kelson42 , While making the changes suggested by @gouri-panda, I discovered a bug that occurs only the first time the storage selection dialog is shown. If the device does not have enough space, clicking on the book and then on 'Yes' to start the download brings up the storage selection dialog again.


https://user-images.githubusercontent.com/34593983/222348371-51bd225e-3832-43bb-b290-267df7b78a11.mp4



I'm placing a fix for it in this PR.

File: app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt (hunk 1 above)
Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt:83]: @gouri-panda , I believe that ```DetectingFileSystem``` would be a more accurate descriptor than ```Unknown```.

Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt]: @gouri-panda , is it looks good to you?

Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt]: I have changed ```Unknown``` to ```DetectingFileSystem``` and update test cases according to it.

**Comment by kelson42** [comment]
@gouri-panda Good to merge this time?

File: app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt (hunk 1 above)
Comment (gouri-panda) [reply app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt]: Looks good to me! Thanks!

**Review by gouri-panda — APPROVED** [review]
