### PR TITLE
Fixed, Hitting back on the DWDS app exits it.

### LINKED ISSUE #3507: Hitting back on the DWDS app exits it
I'm on a Nothing Phone (1) running Android 13. The usual manner to come back to the previous page is to slide the screen right-to-left. With the current test DWDS (as well as Wikimed; 2023-06 build 6231840) apps, this closes the app and returns the user to the phone's home screen.

I cannot reproduce this bug on the Kiwix app (3.7.1 build 7230701) - going back works fine there.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3507 

We removed the activity finishing triggered by pressing the back button in the reader fragment. We initially added this when we were converting CustomReader to a fragment, as we encountered crashing issues at the time. However, it was quite some time ago, and we have since refactored our code. Now, it no longer crashes and functions smoothly without terminating the activity when the back button is pressed. We also made this change for when a user presses the back button from the download screen. This back button press is within the CustomReaderFragment, so it does not impact the functionality of the DownloadFragment.

https://github.com/kiwix/kiwix-android/assets/34593983/40286e03-1156-49fd-9848-df6f04fb4ced

* Moved `openSearchItem`, and `findInPage` functionality to our `CoreReaderFragment` as we used the same code twice for these methods in the app and custom module.

### CODE REVIEW

File: custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt [hunk 1]
```diff
@@ -92,11 +91,6 @@ class CustomReaderFragment : CoreReaderFragment() {
     }
   }
 
-  override fun onBackPressed(activity: AppCompatActivity): FragmentActivityExtensions.Super {
-    requireActivity().finish()
-    return super.onBackPressed(activity)
-  }
-
   private fun openSearchItem(item: SearchItemToOpen) {
```
Comment (kelson42) [inline custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt:94]: Why this method is overriden?

**Review by kelson42 — CHANGES_REQUESTED** [review]
Please follow instructions at https://github.com/kiwix/kiwix-android/issues/3507#issuecomment-1774847992

File: custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt (hunk 1 above)
Comment (kelson42) [reply custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt:94]: talking about opensearchItem() and the question is why it need to be doffetent in a custom app?

Comment (MohitMaliFtechiz) [reply custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt:94]: @kelson42 Thanks for highlighting this, We are observing the `seachedItem` in both modules(app, custom) and this method for opening the searched item, but we have written this method twice in both reader fragments so it would be better to move this code `CoreReaderFragment`.

Comment (MohitMaliFtechiz) [reply custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt]: Done.

**Comment by kelson42** [comment]
@MohitMaliDeveloper You still don't have put the code comments as already requested twice on the parent class methods which are overriden for custom app. This is the only solution we have that a future modification on parent class goes applied as well (if necessary) on the custom class.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Sorry I missed adding the comments, now I have added the necessary comments on methods that are override in CustomReaderFragment with the explanation what are the working of those methods.

**Comment by kelson42** [comment]
@MohitMaliFtechiz What I requested on paretn class is atill missing

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz What I requested on paretn class is atill missing

I have added the comments in the parent class(CoreReaderFragment).

**Comment by kelson42** [comment]
> > @MohitMaliFtechiz What I requested on paretn class is atill missing
> 
> I have added the comments in the parent class(CoreReaderFragment).

You still have followed my instructions.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Can you please point out which parent class you want those comments or remove the unnecessary code?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Attempt number #5: write a comment on each method of corereaderfragment, wich is then superseeded/overriden in the customapp fragment, that the dev has to look to the customapp fragment too if it modifies this method.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please rebase on main (and fix conflicts)

**Comment by gouri-panda** [comment]
I believe it hasn't yet implemented the request @kelson42 made. I'll come back after it has done.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Attempt number https://github.com/kiwix/kiwix-android/issues/5: write a comment on each method of corereaderfragment, wich is superseeded/overriden in the customapp fragment, that way - in the future - the dev is invited to look to the customapp fragment too if it modify this custom app method as well.
This will avoid the kind of bug this PR fixes!

> @MohitMaliFtechiz Please rebase on main (and fix conflicts)

@kelson42 Done.

> I believe it hasn't yet implemented the request @kelson42 made. I'll come back after it has done.

@gouri-panda I have make the changes can you please review this PR.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Sure! Thanks!

**Comment by kelson42** [comment]
@MohitMaliFtechiz red CI

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz red CI

CI is green now.

**Comment by kelson42** [comment]
@MohitMaliFtechiz sorry, you havr to rebase again

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @gouri-panda Conflicts are resolved, @gouri-panda you can review this now.
