### PR TITLE
Fix #1881 Land home screen before exiting

### LINKED ISSUE #1881: Unusual behaviour on pressing back button
**Describe the bug**

In some Zim files, on pressing back button lands on the home screen while in some others it exits the app. I can't guess the pattern in which case first happens and in which case second happens.

**Expected behavior**

In all cases, it should be the same. Either the app should exit or home screen should appear.

P.S.: It would be better if home screen appears.

**Steps to reproduce the behavior:**
Case is random so not necessary it would work on following the steps.

1. Open zim files and press back button and observe.

**Screenshots**

[Link](https://imgur.com/htuwe4G)

**Environment**
- Version of Kiwix Android : Kiwix 3.2.1
- Device : Redmi 4
- OS version : Nougat

### PR DESCRIPTION
**Pull request by sonusourav**
Fixes #1881 

Modified `onBackPressed` in CoreMainActivity.java to land the home screen before exiting.

**Screenshots** 

[Link](https://imgur.com/lflWQdr)

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 1]
```diff
@@ -621,8 +621,10 @@ void openToc() {
       compatCallback.finish();
     } else if (drawerLayout.isDrawerOpen(GravityCompat.END)) {
       drawerLayout.closeDrawers();
-    } else if (getCurrentWebView().canGoBack()) {
+    } else if (getCurrentWebView().canGoBack() && !HOME_URL.equals(getCurrentWebView().getUrl())) {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: I think you can remove this condition and everything will continue working

Comment (sonusourav) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Actually, that condition is required. Without it, the app is stuck in some loop. 
Here is the video if that line is removed
[Link](https://imgur.com/Px0S11V)
