### PR TITLE
Fixed library showing blank screen in android 13

### LINKED ISSUE #3273: Library showing a blank screen in android 13
**Describe the bug**
```LibraryFrgment``` showing a blank screen in android 13.

**Expected behavior**
It should show the zim files instead of blank screen.

**Steps to reproduce the behavior:**
* Install kiwix app in android 13 emulator or in real device.
* Open application and download any zim file
* Goto library screen you will see the blank screen instead of zim files.

**Screenshots**
Screenshot from 2023-03-17 14-42-07

**Environment**
- Version of Kiwix Android : Current develop branch
- Device : Emulator
- OS version : Android 13

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3273 

* In this PR we have fixed the blank screen showing in android 13, Also i have found a bug while testing if we grant permission inside the application(on android 10 and below if we have not any zim file in our device) then it's showing same blank screen as showing in android 13 because in ```onRequestPermissionsResult``` we are settings the visibility of ```Recyclerview``` now i have replaced the visibility with ```requestFileSystemCheck()``` method which automatically check the file system and set the UI according to the file system.

**Edited**

* We have add the test cases for testing the ```LocalLibraryFragment``` , we are testing the both scenario if device has not any zim file and after downloading the zim files Zim list is visible or not.

### CODE REVIEW

**Comment by kelson42** [comment]
@MohitMaliFtechiz I have requested an automated test for this scenario. Why this is not implemented?

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt [hunk 1]
```diff
@@ -448,9 +451,7 @@ class LocalLibraryFragment : BaseFragment() {
       } else if (!isPermissionDenied(grantResults)) {
         fragmentDestinationLibraryBinding?.apply {
           permissionDeniedLayoutShowing = false
-          fileManagementNoFiles.visibility = GONE
-          goToDownloadsButtonNoFiles.visibility = GONE
-          zimfilelist.visibility = VISIBLE
+          requestFileSystemCheck()
```
Comment (gouri-panda) [inline app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt:454]: Why are we removing it here and adding that in the check permission? Plus we are checking `requestFileSystemCheck` twice which is before the permission and after the permission. Is it necessary?  It's computationally expensive.

Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt]: > Plus we are checking requestFileSystemCheck twice which is before the permission and after the permission. Is it necessary? It's computationally expensive.

good catch! i had forget to remove this.

> Why are we removing it here and adding that in the check permission?

I have added the visibility for views after ```requestFileSystemCheck``` method so it's easy to maintain views according to filesystem.

**Review by gouri-panda — COMMENTED** [review]
@MohitMaliFtechiz Code wise it looks good. I haven't tested it in Android 13 but we should add test cases as well as  @kelson42  mentioned.

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda , i have add the test cases.

**Review by gouri-panda — APPROVED** [review]
LGTM!
