### PR TITLE
Fixed, Using TTS on Wikivoyage 2023-06 (Android 13) reads code aloud.

### LINKED ISSUE #3530: Using TTS on Wikivoyage 2023-06 (Android 13) reads code aloud
From a user:
> The read aloud functionality seems to read the code rather than just the text. "The Galapagos" is a good example, it starts off reading the page title and then delves into what I assume is the behind the scenes code. 
> I'm currently using Version 2023-06 on an Android 13 device. Let me know if you need any other info. 

I'm putting this here as we don't recall seeing this kind of bug report for the regular android version. I also see some possibly related issues have been closed for release 3.8.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #3530 

**Issues**
* It was reading the code part(that is style element) in `Wikivoyage 2023-06` ZIM file.
* While reading the article it is skipping lines. For example:- It reads the first line then skips the second line, then it reads the third line, and skips the fourth line.

**Fix**
* We have removed the including of the `style` attribute if any is present in the content to avoid this type of issue, like we are removing the `(title, .navbox etc)`.
https://github.com/kiwix/kiwix-android/blob/252d846b64fc669670b3028f5d59a3ffc211f51e/core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt#L154
* The issue was caused by an unnecessary increment of the 'currentPiece' index in the onDone callback of the TextToSpeech engine. This double increment led to the skipping of lines. The redundant increment at the end of the method has been removed, ensuring that each line is read correctly.

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt [hunk 1]
```diff
@@ -300,7 +300,6 @@ class KiwixTextToSpeech internal constructor(
               bundle,
               bundle.getString(Engine.KEY_PARAM_UTTERANCE_ID)
             )
-            currentPiece.getAndIncrement()
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt:303]: @MohitMaliDeveloper I don't think we should remove that.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt:303]: @gouri-panda can you please share your analysis on this? why you are not in favor of removing this?

As I see in the code we are already incrementing the index 

https://github.com/kiwix/kiwix-android/blob/bd31240002ed417ed9e9587ae088a17198eefab2/core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt#L298

so I don't understand why we are again incrementing the index it will skip the next line. This is happening when I try to read the article, if I keep this then it is skipping the next line.

Comment (gouri-panda) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt:303]: Ohh! I see now @MohitMaliFtechiz That was a bug. We didn't notice earlier.

**Review by gouri-panda — APPROVED** [review]
