### PR TITLE
Search screen not popup after pressing back from search result

### LINKED ISSUE #2939: Search screen not popup after pressing back from search result.
**Describe the bug**
Search screen not popup after pressing back from search result.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Fixes #2939

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt [hunk 1]
```diff
@@ -229,7 +229,10 @@ abstract class CoreMainActivity : BaseActivity(), WebViewProvider {
     }
     activeFragments().filterIsInstance<FragmentActivityExtensions>().forEach {
       if (it.onBackPressed(this) == FragmentActivityExtensions.Super.ShouldCall) {
-        if (navController.currentDestination?.label?.equals("Reader") == true) {
+        if (navController.currentDestination?.label?.equals("Reader") == true &&
+          navController.previousBackStackEntry?.destination
+            ?.label?.equals("SearchFragment") == false
```
Comment (gouri-panda) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt:234]: We should use `id` here. Hardcoded `string` is not a good idea.

Comment (MohitMaliFtechiz) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt]: Done

**Review by gouri-panda — APPROVED** [review]
