### PR TITLE
Feature/frans lukas/2378 fix search keyboard

### LINKED ISSUE #2378: SearchFragment doesn't hide keyboard on finish
**Describe the bug**
Open the search fragment, press the back arrow in the toolbar, see the keyboard is still open in a context where you can't input text.

**Expected behavior**
The only scenario where the keyboard should remain open after leaving search is when launching FindInPage

**Screenshots**

**Environment**
- Version of Kiwix Android : one-activity branch

### PR DESCRIPTION
**Pull request by Frans-Lukas**
Fixes #2378 

`closeKeyboard()` was moved to FragmentExtensions.
Keyboard now closes on fragment exit (from searchFragment).

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt [hunk 1]
```diff
@@ -28,9 +30,12 @@ inline fun <reified T : ViewModel> Fragment.viewModel(
...
-) {
+fun Fragment.toast(stringId: Int, length: Int = Toast.LENGTH_LONG) {
   requireActivity().toast(stringId, length)
 }
+
+fun Fragment.closeKeyboard() {
+  val inputMethodManager =
+    requireContext().getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
+  inputMethodManager.toggleSoftInput(InputMethodManager.HIDE_IMPLICIT_ONLY, 0)
+}
```
Comment (s-ayush2903) [inline core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt:41]: Can't we make some extension on context for keyboard-management, this is just Fragment specific

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt:41]: What are the pros of having it context specific?

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt [hunk 2]
```diff
@@ -28,9 +30,12 @@ inline fun <reified T : ViewModel> Fragment.viewModel(
...
 
-fun Fragment.toast(
-  stringId: Int,
-  length: Int = Toast.LENGTH_LONG
-) {
+fun Fragment.toast(stringId: Int, length: Int = Toast.LENGTH_LONG) {
   requireActivity().toast(stringId, length)
 }
+
+fun Fragment.closeKeyboard() {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt:37]: Have you read this infamous [SO answer](https://stackoverflow.com/a/17789187/12225251)?

`close` is quite misleading when what this method does is actually "toggle"

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt (hunk 1 above)
Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt:41]: `requireContext().getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager`

this line would get shorter. Really it is about asking yourself what class should have this responsibility. Context might not be a great choice as this method is going to change in light of my other comment and a view will become necessary, notably not all `contexts` actually have views. It may make most sense to be on View or Fragment at the end of the day. View makes slightly more sense but putting it on fragment is easier and more inline with the general usage. Fragments also technically can have no view but we don't use them like that and nobody should use them like that anymore now that ViewModels exist

File: core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt (hunk 2 above)
Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt:37]: It seems to always close the keyboard, if I call it twice, the keyboard is not hidden and then shown, but only hidden. If I call "toggleKeyboard" in onCreate, the keyboard is not opened. Am I missing something?

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt:37]: image

regardless it is all fucked up, a hide flag is being used in a show flag position and it only works because they are the same constant. We should fix it

Comment (Frans-Lukas) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt:37]: I've tried most of the things mentioned in the SO post and can not make it work. I think this will have to wait for the weekend  if it's to be changed. 

```kt
fun Fragment.closeKeyboard(context: Context) {
  view?.rootView?.let {
    val imm = context.getSystemService(Activity.INPUT_METHOD_SERVICE) as InputMethodManager
    imm.hideSoftInputFromWindow(it.windowToken, 0)
    it.clearFocus()
  }
}
```
called like: 
```kt

  override fun onDestroyView() {
    super.onDestroyView()
    compositeDisposable.clear()
    closeKeyboard(requireContext())
  }
```

from `SearchFragment.kt`

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt:37]: well I suppose it is minor and if it works it works, the release should march forward and we can accept mild debt

**Review by macgills — APPROVED** [review]
