### PR TITLE
Fix #1823 Change tab theme in light and dark mode

### LINKED ISSUE #1823: Recent tabs are not gray in night mode.
**Describe the bug**
Recent tabs appear white in Night Mode

**Expected behavior**
They should be of dark color

**Screenshots**
Screenshot_2020-02-26-22-20-12-651_org kiwix kiwixmobile

**Environment**
- Version of Kiwix Android : 3.2.0

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #1823

Added check for night mode in the tabs adapter to apply the theme change filter on tabs too. 

**Screenshot**

screencap

screencap

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java [hunk 1]
```diff
@@ -119,7 +127,7 @@ public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
     constraintSet.connect(textView.getId(), ConstraintSet.END, close.getId(), ConstraintSet.START);
 
     constraintSet.applyTo(constraintLayout);
-    return new ViewHolder(constraintLayout, contentImage, textView, close);
+    return new ViewHolder(constraintLayout, contentImage, textView, close, activity.getApplicationContext());
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: all of these views have a context, there is no reason to pass in a context

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java [hunk 2]
```diff
@@ -178,12 +186,42 @@ void setTabClickListener(TabClickListener listener) {
...
+    private final Paint invertedPaint = createInvertedPaint();
 
-    ViewHolder(View v, ImageView content, TextView title, ImageView close) {
+    ViewHolder(View v, ImageView content, TextView title, ImageView close, Context context) {
       super(v);
       this.content = content;
       this.title = title;
       this.close = close;
+
+      SharedPreferenceUtil sharedPreferenceUtil = new SharedPreferenceUtil(context);
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: we use dagger to provide dependencies but seeing as how this class isn't created by dagger you will have to pass this in to the constrcutor

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java [hunk 3]
```diff
@@ -178,12 +186,42 @@ void setTabClickListener(TabClickListener listener) {
...
+    }
+
+    @NotNull private Paint createInvertedPaint() {
+      Paint paint = new Paint();
+      ColorMatrixColorFilter filterInvert = new ColorMatrixColorFilter(NIGHT_MODE_COLORS);
+      paint.setColorFilter(filterInvert);
+      return paint;
+    }
+
+    private void updateNightMode() {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: This entire feature is now duplicated across 2 classes. Create a class to encapsulate this, some like `NightModeViewPainter`, it should have one method `update(view)`

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: I'll do the same for the createInvertedPaint() method too.

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: @macgills the functionality of methods in both classes is same, but the methods differ. 
In KiwixWebView, the the methods are:
```java
public void deactivateNightMode() {
    setLayerType(LAYER_TYPE_NONE, null);
    videoView.setLayerType(LAYER_TYPE_NONE, null);
  }

  public void activateNightMode() {
    if (getUrl() != null && getUrl().equals(HOME_URL)) {
      return;
    }
    setLayerType(LAYER_TYPE_HARDWARE, invertedPaint);
    videoView.setLayerType(LAYER_TYPE_HARDWARE, invertedPaint);
  }
```

How do we keep these methods the same if we encapsulate the class?

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: Should I create more than just the `update(view)` method and overload the methods?

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: Hmm a bit annoying, kotlin gives us a way of working with this but it isn't really pretty

something like 

`fun updateView<T:View>(view:T, shouldActivateCriteria: T.()->Boolean=null, vararg additionalViews:View)`

I freehanded that so the syntax could be off. Touches on a few topics that could be a bit complex.

Try it if you want, otherwise I can live with only 2 duplications

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 4]
```diff
@@ -157,6 +157,7 @@
   public static final String HOME_URL = "file:///android_asset/home.html";
   protected final List<KiwixWebView> webViewList = new ArrayList<>();
   private final BehaviorProcessor<String> webUrlsProcessor = BehaviorProcessor.create();
+  private final NightModeViewPainter painter = new NightModeViewPainter();
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Dagger has to be used

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: @macgills is it fine now?

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
+
+class NightModeViewPainter @Inject constructor(
+  val context: Context?
+) {
+
+  private var nightModeConfig: NightModeConfig? = null
+  private val invertedPaint = createInvertedPaint()
+
+  fun update(view: View) {
+    val sharedPreferenceUtil = SharedPreferenceUtil(context)
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt]: sharedPref and NightModeConfig should be in the constructor

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java [hunk 6]
```diff
@@ -145,6 +145,10 @@ public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
       listener.onSelectTab(v, selectedPosition);
       notifyDataSetChanged();
     });
+    if (!webViewTitle.equals(activity.getString(R.string.menu_home))) {
+      NightModeViewPainter painter = new NightModeViewPainter(holder.content.getContext());
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: NightModeViewPainter should not be constructed by you, only Dagger

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 7]
```diff
@@ -1563,15 +1565,7 @@ private void loadPrefs() {
     }
 
     openFullScreenIfEnabled();
-    updateNightMode();
-  }
-
-  private void updateNightMode() {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: this method shouldn't have been deleted, it should have invoked the NightModeViewPainter

this deletion has resulted in duplicating this call `painter.update(getCurrentWebView(), videoView);`

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+  private fun activateNightMode(webview: WebView, videoView: ViewGroup) {
+    if (webview.url != null && webview.url == CoreMainActivity.HOME_URL) {
+      return
+    }
+    webview.setLayerType(View.LAYER_TYPE_HARDWARE, invertedPaint)
+    videoView.setLayerType(View.LAYER_TYPE_HARDWARE, invertedPaint)
+  }
+
+  private fun createInvertedPaint(): Paint {
+    val paint = Paint()
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt]: invertedPaint could be a property eg `val invertedPaint = Paint().apply{ colorFilter = NIGHT_MODE_COLORS }`

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java (hunk 6 above)
Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: @macgills how do I do that in the TabsAdapter? TabsAdapter isn't created by dagger.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: Pass it to the constructor of TabsAdapter

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt (hunk 5 above)
Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt]: @macgills I if I shift NightModeConfig in the constructor, we won't need context or sharedPref. We only needed them for getting nightModeConfig. So I'll do that.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt [hunk 9]
```diff
@@ -0,0 +1,79 @@
...
+import javax.inject.Inject
+
+/**
+ * NightModeViewPainter class is used to apply respective filters to the views
+ * depending whether the app is in dark mode or not
+ * Created by yashk2000 on 24/03/2020.
+ */
+
+class NightModeViewPainter @Inject constructor(
+  val nightModeConfig: NightModeConfig
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt]: could be private

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt [hunk 10]
```diff
@@ -0,0 +1,79 @@
...
+
+  fun update(view: View) {
+    if (nightModeConfig.isNightModeActive()) {
+      activateNightMode(view)
+    } else {
+      deactivateNightMode(view)
+    }
+  }
+
+  fun update(
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt]: the function declaration can be on one line

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java (hunk 3 above)
Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: @yash1ts did you have trouble with this `updateView<T:View>(view:T, shouldActivateCriteria: T.()->Boolean=null, vararg additionalViews:View)` signature?

I can go into more depth if you need help as I am back on the project for this week and am not just doing drive by reviews.

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: @macgills I'll try using it again by myself once. if it doesn't work I'll definitely ask for more clarification. Thanks for the guidance!

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: @macgills I modifed the NightModeViewPainter like below. Is it fine:

```kotlin
class NightModeViewPainter @Inject constructor(
  private val nightModeConfig: NightModeConfig
) {

  private val invertedPaint =
    Paint().apply { colorFilter = ColorMatrixColorFilter(KiwixWebView.NIGHT_MODE_COLORS) }

  fun update(vararg additionalViews: View) {
    if (nightModeConfig.isNightModeActive()) {
      for (view in additionalViews) {
        activateNightMode(view)
      }
    } else {
      for (view in additionalViews) {
        deactivateNightMode(view)
      }
    }
  }

  fun deactivateNightMode(view: View) {
    view.setLayerType(View.LAYER_TYPE_NONE, null)
  }

  private fun activateNightMode(view: View) {
    view.setLayerType(View.LAYER_TYPE_HARDWARE, invertedPaint)
  }
}
```

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: `if (getUrl() != null && getUrl().equals(HOME_URL)) {` what about this though?

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: I put that condition when I'm calling update from CoreMainActivity.
```java
 private void updateNightMode() {
    if (getCurrentWebView().getUrl() != null && getCurrentWebView().getUrl().equals(HOME_URL)) {
      return;
    }

    painter.update(getCurrentWebView(), videoView);
  }
```

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: This will change the logic, originally it is only triggered for activation not for deactivation.

This checks the condition for both cases.

That was the point of `shouldActivateCriteria: T.()->Boolean=null` which as a [receiver function](https://medium.com/tompee/idiomatic-kotlin-lambdas-with-receiver-and-dsl-3cd3348e1235) typed off of our first argument would have given us access to that arguments methods to perform the check.

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: > originally it is only triggered for activation not for deactivation.

it is still triggered only in case nightMode is on right?
I modified the condition and included `nightModeConfig.isNightModeActive()` so that it only returns when night mode is on.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: Ah sorry, I didn't see the full width of that if statement.

I still think it is more confusing to do it this way. 
"if the url is not null and is home and night mode is active then don't update" as an expression is hiding the intention of the code
"don't activate night mode on the home screen"

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: > That was the point of shouldActivateCriteria: T.()->Boolean=null which as a receiver function typed off of our first argument would have given us access to that arguments methods to perform the check.

I'll try to go ahead with this approach then.

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: @macgills I'm facing some difficulties with this approach. 
```kotlin
fun <T : View> update(
    view: T,
    shouldActivateCriteria: (T.() -> Boolean)? = null,
    vararg additionalViews: View
  ) {
    if (shouldActivateCriteria != null) {
      if (view.shouldActivateCriteria()) {
        //call activateNightMode
      }
    }
  }
```

Is this correct?
And now how do I call this function from CoreMainActivity and TabsAdapter?

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: sorry mislead you a little bit

`shouldActivateCriteria: (T.() -> Boolean)? = null,`

should be

`shouldActivateCriteria: ((T) -> Boolean) = { true },`

so this parameter is "a function which accepts a T and returns a Boolean, the default value of which is a function that returns true"

in kotlin usage would look like

```
painter.update(webView, { it.url == null || it.url !=HOME_URL}, videoView)
```

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java]: @macgills I tried this. I haven't created the body of the `update` function yet, but I'm still unable to call the method. Could you please tell me where I'm going wrong.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 11]
```diff
@@ -1545,6 +1547,10 @@ private void updateUrlProcessor() {
     }
   }
 
+  private void updateNightMode() {
+    painter.update(getCurrentWebView(), { getCurrentWebView().getUrl() == null || getCurrentWebView().getUrl() != HOME_URL}, videoView);
```
Comment (yashk2000) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: @macgills here I'm trying to call the `update` function.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java:1551]: you don't need to call `getCurrentWebview()` in that lambda,

```
    shouldActivateCriteria: ((T) -> Boolean) = { true }
```

`(T)->Boolean` translation: this parameter is a function which takes a view as a parameter and returns a Boolean. In kotlin when a lambda only has 1 parameter you don't have to declare it explicitly and can instead reference it by `it` in the lambda scope.

To be explicit what you wrote could be rewritten as 
```
{ theWebviewYouPassedAsTheFirstParamter ->
getCurrentWebView().getUrl() == null || getCurrentWebView().getUrl() != HOME_URL
}
```

ahhh but this is java. delete the lambda, type `new` press ctrl+space and choose the thing that looks most appropriate to create in this position. See DialogShower usage in java for an example

**Comment by yashk2000** [comment]
@macgills is it fine now?

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt [hunk 12]
```diff
@@ -0,0 +1,65 @@
...
+ */
+
+class NightModeViewPainter @Inject constructor(
+  private val nightModeConfig: NightModeConfig
+) {
+
+  private val invertedPaint =
+    Paint().apply { colorFilter = ColorMatrixColorFilter(KiwixWebView.NIGHT_MODE_COLORS) }
+
+  fun <T : View> update(
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:39]: you can give `vararg additionalViews: View` a default value of `emptyArray()` and then annotate this method with `@JvmOverloads`

This will create 3 different versions of this method you can call from java to ease the interop.

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:39]: @macgills could you please tell why do we need to create 3 different versions of the function? We are just calling the function from 2 places.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt [hunk 13]
```diff
@@ -0,0 +1,64 @@
...
+    view: T,
+    shouldActivateCriteria: ((T) -> Boolean) = { true },
+    vararg additionalViews: View
+  ) {
+    if (nightModeConfig.isNightModeActive()) {
+      if (shouldActivateCriteria(view)) {
+        for (view in additionalViews) {
+          activateNightMode(view)
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:47]: you aren't using additionalViews as additionalViews, you are using it as "the only views that get painted"
I would rewrite de/activate to also accept varargs, and then you can invoke them like so activateNightMode(view, *additionalViews) by using the spread operator

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt (hunk 12 above)
Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:39]: It is to get compatability in java with default arguments.

in kotlin the simple case is you want to paint 1 view `painter.update(myView)`, because of default arguments you don't need to supply anything else

in java - because it sucks - you have to write `painter.update(myView, { true }, emptyArray)`, the emptyArray might not be necessary because of how varargs works but you still have to say more than you want

`@JVMOverloads` will create methods with different numbers of args with the default arguments filled in, you can read more [here](https://android.jlelse.eu/demystifying-the-jvmoverloads-in-kotlin-10dd098e6f72)

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt (hunk 13 above)
Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:47]: @macgills if we use activateNightMode(view, *additionViews), then do we need to use varargs?
In this case, we have both the views we need already, view will have the webview and we can replace the varargs directly with a single view which will contain either the videoView of the holder.content.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:47]: The design of the api is such that it can handle an arbitrary number of views when calling update.

additionalViews should only be used in the case of the web&videoView and I wouldn't be shocked if more views got added given how this feature grows

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:47]: Ok. Thanks for the explanation on both the comments. 
And sorry for the delay in this pr. I am a bit unfamiliar with the current method we're using. So I'm trying to properly learn what is happening. Thanks a lot for the explanations and the blog posts you linked.

Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:47]: They are not easy topics, just keep in mind that what we are trying to do is keep the usage of `painter` as painless as possible. We only specify something if we absolutely must specify it

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt]: @macgills updated, please review.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt (hunk 12 above)
Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:40]: `@JVMOverloads` is a really cool annotation. Thanks for the blog post :)

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt [hunk 14]
```diff
@@ -36,29 +36,32 @@ class NightModeViewPainter @Inject constructor(
...
     } else {
-      for (view in additionalViews) {
-        deactivateNightMode(view)
-      }
+      deactivateNightMode(view, *additionalViews)
     }
   }
 
-  fun deactivateNightMode(view: View) {
+  fun deactivateNightMode(view: View, vararg additionalViews: View) {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:54]: you don't need the first view parameter. Perhaps a small explanation of varargs is in order

in java you define varags like so `public void myMethod(String... someStrings)` and in the body of the method someStrings is just an array of values. You can invoke that method like so `myMethod("first","second","third")` or by just giving it an array `myMethod(myStringArray)`.

Kotlin works much the same but we have a much more explicit `vararg` as opposed to `...`, the thing that is a bit magical here is the spread operator `*` which (funnily enough) spreads out an array eg
```
val myStringArray = arrayOf("1","2")
myMethod("0", *myStringArray)
```
is equivalent to writing
```
myMethod("0","1","2")
```
but it is important to note that it does copy the entire array, sometimes an issue, not here.

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt]: @macgills thanks for this information :)
I updated the pr accordingly. Is it fine now?

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt [hunk 15]
```diff
@@ -51,17 +51,15 @@ class NightModeViewPainter @Inject constructor(
     }
   }
 
-  fun deactivateNightMode(view: View, vararg additionalViews: View) {
-    view.setLayerType(View.LAYER_TYPE_NONE, null)
-    for (v in additionalViews) {
-      v.setLayerType(View.LAYER_TYPE_NONE, null)
+  fun deactivateNightMode(vararg additionalViews: View) {
+    for (view in additionalViews) {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt:55]: the more functional way is to use `.forEach`

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 16]
```diff
@@ -1545,6 +1548,10 @@ private void updateUrlProcessor() {
     }
   }
 
+  private void updateNightMode() {
+    painter.update(getCurrentWebView(), kiwixWebView -> !(kiwixWebView.getUrl() != null && kiwixWebView.getUrl().equals(HOME_URL)), videoView);
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java:1552]: the boolean expression here can be simplified, negating the entire condition is rarely a good decision, I wouldn't be surprised if there was a quick fix

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java [hunk 17]
```diff
@@ -145,6 +147,9 @@ public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
       listener.onSelectTab(v, selectedPosition);
       notifyDataSetChanged();
     });
+    if (!webViewTitle.equals(activity.getString(R.string.menu_home))) {
+      painter.update(holder.content);//, imageView -> true, holder.content);
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java:151]: delete the comment

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt (hunk 14 above)
Comment (macgills) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt]: @yashk2000 very very close, see the last few comments

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt]: @macgills updated. Please take a look.

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java [hunk 18]
```diff
@@ -1545,6 +1548,15 @@ private void updateUrlProcessor() {
     }
   }
 
+  private void updateNightMode() {
+    painter.update(getCurrentWebView(), kiwixWebView -> {
+      if (kiwixWebView.getUrl() != null) {
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java:1553]: this is too complicated, any time you see

```
if { return expression } else return true
```

it is guaranteed to be simplifiable and probably automatically. For starters it could definitely be a ternary

eg
```
return kiwixWebView.getUrl() != null ? !kiwixWebView.getUrl().equals(HOME_URL) : true
```

image

image

image


Also you could have skipped all of these steps by pressing `alt+enter` on the `if`

image

And you could have done it before these changes by pressing `alt+enter` on the `&&`

image

Comment (yashk2000) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java]: Apologies, I did something else by mistake. This is what I intended to do. I updated it now properly.

**Comment by yashk2000** [comment]
@macgills sure I'd like to give a try to make a Unit test for the NightModeViewPatiner too. 
Should I open a separate issue and pr for this or should I keep making changes in this pr itself?

**Comment by macgills** [comment]
Lets do it in a separate PR, a good PR should have unit tests but this has grown pretty big from conversation and I think it will give us piece of mind to close it. Make a ticket if you don't mind
