### PR TITLE
Fixing library Pagination Issues

### LINKED ISSUE #4640: Search Scroll state should restart
**Describe the bug**

When we are browsing the zim files in download and search it the search results are same state as previous state.
**Expected behavior**

We should go to top or restart the scroll state.
**Steps to reproduce the behavior:**
1. Go to the download section
2. Browse the files
3. While browsing search a zim
4. See the scroll state (in other words we manually go to the top results)

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.14
- Device : Samsung 
- OS version : 13

**Logs**

### LINKED ISSUE #4700: The download screen automatically goes to the top when a download is ongoing.
**Describe the bug**
The download screen automatically goes to the top when a download is ongoing.

**Expected behavior**
It should not automatically scroll when the download is ongoing. It should only scroll to the top when 

**Steps to reproduce the behavior:**
1. Go to the Download screen.
2. Click on any ZIM file to download.
3. Scroll down. When the download updates, it takes us to the top of the screen.

**Environment**
- Version of Kiwix Android : 4.0.0
- Device : Google Pixel 7a, Android 11 emualtor.
- OS version : Android 16, Android 11

https://github.com/user-attachments/assets/63c305c1-29e6-4e3a-921a-a659d14e4eed

### LINKED ISSUE #4701: Pagination Logic is Broken
**Describe the bug**
In Download Screen when items are loaded it flickers and resets is scroll state. 
Note- Pagination is successful and items are appended correctly.

**Expected behavior**
Maintain its pagination state

**Steps to reproduce the behavior:**
1. Go to Download Tab
2.  Scroll till loading is showing
3. Pagination resets is state and goes to top again 

**Screenshots**

https://github.com/user-attachments/assets/e713d7c5-a6f2-4f4f-a1a1-59063dda7600

**Environment**
- Version of Kiwix Android 
- Device : OnePlus
- OS version :  16

### PR DESCRIPTION
**Pull request by atharvyadav22**
Fixes #4701 - Fixes Pagination not working while downloading.
Fixes #4700 - Fixes Broken Pagination logic. When downloading is in progress then list automatically goes to the top when a download progress update.

Additionally, this caused a regression issue with the wrong fixes #4640, which was pushed

* Introduced event-based scroll handling instead of relying on condition-based list position changes. This separates scroll behavior from list changes and makes the architecture clearer and more maintainable.
* The list now scrolls to the top only when a fresh set of items is fetched from the online source (e.g., after applying search, filters, category, or language changes).
* The current scroll position is preserved during download progress updates and pagination (load more).
* Improved the loadMore functionality.

### CODE REVIEW

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz one more important thing is while migration this `OnlineLibraryFragment` we should carefully look up these changes too as this viewModel and Screen code are already good just fragment should be updated or else again we will face regression issue or something else like now we did.

File: app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt [hunk 1]
```diff
@@ -531,7 +531,10 @@ class ZimManageViewModel @Inject constructor(
   private fun requestsAndConnectivityChangesToLibraryRequests(
     onlineLibraryResult: MutableStateFlow<OnlineLibraryResult>
   ) = requestDownloadLibrary.onEach { onlineLibraryRequest ->
-    onlineLibraryFetchingJob?.cancel()
+    // Don't cancel job for LoadMore else pagination is canceled.
+    if (!onlineLibraryRequest.isLoadMoreItem) {
```
Comment (MohitMaliFtechiz) [inline app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt]: Why are we not cancelling this? It cancels the previous ongoing job. If a pagination request comes, it cancels the ongoing request, and requests for that incoming page. 


If we don't cancel the request, it simultaneously makes API calls that is unneccessary.

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryScreen.kt [hunk 2]
```diff
@@ -219,25 +218,23 @@ private fun OnlineLibraryList(state: OnlineLibraryScreenState, lazyListState: La
...
-    if (!state.isLoadingMoreItem) {
+  LaunchedEffect(state.isSearchActive, state.searchText) {
+    if (state.isSearchActive) {
       lazyListState.scrollToItem(ZERO)
     }
   }
-  LaunchedEffect(lazyListState, state.onlineLibraryList) {
+  LaunchedEffect(lazyListState) {
     snapshotFlow { lazyListState.layoutInfo }
-      .combine(
```
Comment (MohitMaliFtechiz) [inline app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryScreen.kt:229]: Why are we removing this logic? It is placed for some reason. In your logic, there is no check when there are no books available. It will trigger the loadMore in the initial state as well.

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryScreen.kt [hunk 3]
```diff
@@ -219,25 +218,23 @@ private fun OnlineLibraryList(state: OnlineLibraryScreenState, lazyListState: La
     }
     showLoadMoreProgressBar(state.isLoadingMoreItem)
   }
-  LaunchedEffect(state.onlineLibraryList) {
-    if (!state.isLoadingMoreItem) {
+  LaunchedEffect(state.isSearchActive, state.searchText) {
+    if (state.isSearchActive) {
```
Comment (MohitMaliFtechiz) [inline app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryScreen.kt]: You are only scrolling to the top when searching for an item. What if when someone apply filter to change the language or category?

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt (hunk 1 above)
Comment (atharvyadav22) [reply app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt]: see it cancels pagination request because downloding is going. so when we loadMore we prioritize it over download and after it loads it continues i have already checked that scenerio for other all the cases it works fine.

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryScreen.kt (hunk 2 above)
Comment (atharvyadav22) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryScreen.kt:229]: its already been triggered in downlaod and pagination code so it re triggers again make pagination loose its state

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryScreen.kt (hunk 3 above)
Comment (atharvyadav22) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryScreen.kt]: it resets like see category request comes filter is already doing its reseting work
Can you please run the app i have already tested it and it worked .

File: app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt (hunk 1 above)
Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt]: Why does it cancel the pagination request when a download is ongoing? And how does not canceling this work? If this method runs, it means it asks for the books from the online library, so the newest request should be processed.

If it is losing the pagination request, there should be some other reason

Comment (atharvyadav22) [reply app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt]: when downloading it emits continuously so other states get cancelled (here pagination request) so what i did just wrapped it in condition after it and during that this condtion is true` onlineLibraryRequest.isLoadMoreItem` so we only cancel jobs for this specific. thats why i placed an comment too there so if someone is migration it would be noticed.

**Comment by MohitMaliFtechiz** [comment]
> it resets like see category request comes filter is already doing its reseting work
Can you please run the app i have already tested it and it worked .

@atharvyadav22 It does not need to run the app, as the code clearly says that it would not scroll to the top when these filters apply.

But for your satisfaction, see here the video. The list does not go to the top when the language filter applies. Also, when search words are changed then also do not go to the top. Also, not go to the top when the items are normally changed.


https://github.com/user-attachments/assets/24e8a99e-bf14-46c8-a29d-b88324eed2b0

**Comment by atharvyadav22** [comment]
> > it resets like see category request comes filter is already doing its reseting work
> > Can you please run the app i have already tested it and it worked .
> 
> @atharvyadav22 It does not need to run the app, as the code clearly says that it would not scroll to the top when these filters apply.
> 
> But for your satisfaction, see here the video. The list does not go to the top when the language filter applies. Also, when search words are changed then also do not go to the top. Also, not go to the top when the items are normally changed.
> 
>  screen-20260220-175928-1771590474355.mp4

i get it you are manually changing the list state so it wont forefully reset the state it works for this way below 

https://github.com/user-attachments/assets/f1d46520-c1bd-465a-9a91-8cec8ddf2b8c

**Comment by MohitMaliFtechiz** [comment]
It is not the way to fix it. The function should fix the functionality. Whether we manually scroll or page changes. 

How do you think it is solving the problem shown in your video? It is already on the top, so changing the filter will get new data, so the state is already on the top. What have we fixed in this?

**Comment by atharvyadav22** [comment]
> It is not the way to fix it. The function should fix the functionality. Whether we manually scroll or page changes.
> 
> How do you think it is solving the problem shown in your video? It is already on the top, so changing the filter will get new data, so the state is already on the top. What have we fixed in this?

I get your point see my code doesn't forcefully scrolls up but as you said 'the state is already on the top.' actually if you look closely it first scrolls up and then filer request is made and it resets there i have already scrolled enough before to apply filters.
I'll update it forcefully scrolling

**Comment by MohitMaliFtechiz** [comment]
I saw your video sample. When the screen is again visible, then `scrollState` automatically restores to 0 position. But i glad that you understand the full problem. Happy to see the proper fix for this.

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz i tried many other ways i either ended up in race condition or missing something this works fine i tried with coroutine too for scroll state to freeze but this handles all the scenarios

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22 Thank you for your efforts. I will review this shortly.

**Comment by atharvyadav22** [comment]
> @atharvyadav22 Thank you for your efforts. I will review this shortly.

Its already solved  just review needed

File: app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt (hunk 1 above)
Comment (MohitMaliFtechiz) [reply app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt]: @atharvyadav22 Are you sure it is emitting continuously while downloading is happening? It should not. Because this is for only fetching the online content. It does not have any link to downlaoding.

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
It is still not working. The one issue is fixed that when downloading the book, it does not go to the top. But the other issue still exists. You tell me you have tested this and it is working fine at your end. Is it my device issue? I have tested this 2 devices, and both have this problem. Can you please show me a video sample of this feature?



https://github.com/user-attachments/assets/47e80d44-d701-4207-8f53-593535de451c

**Comment by atharvyadav22** [comment]
> It is still not working. The one issue is fixed that when downloading the book, it does not go to the top. But the other issue still exists. You tell me you have tested this and it is working fine at your end. Is it my device issue? I have tested this 2 devices, and both have this problem. Can you please show me a video sample of this feature?
> 
>  screen-20260223-152510.mp4

Yes i found it 
last issue i guess left like for some search query data doesnt change so LaunchedEffect isnt triggered 🥲

I have found an solution in ZimViewModel there is already an releated fix using ill use it

**Comment by atharvyadav22** [comment]
This version fixes these condtions below
1.Filters Should Resets scroll.
2. Pagination.
3. Pagination with Search query.
4. Query Changes resets scrolls.
5. Empty query also resets its.
6. Empty to new search query resets scrolls.

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22 Allow me some time. This fix should not be placed under specific conditions. It should be generic for every scenario. Give me some time. I will analyze everthing, and find the best possible solution for this.

**Comment by atharvyadav22** [comment]
> @atharvyadav22 Allow me some time. This fix should not be placed under specific conditions. It should be generic for every scenario. Give me some time. I will analyze everthing, and find the best possible solution for this.

Important thing is i used this approach because it already exists in code base in `ZimManageViewModel` as Bug Fix #4381

**Comment by MohitMaliFtechiz** [comment]
Yeah, that was due to the feature of `StateFlow`, which does not emit the same object again. But yes, this should need special attention before merging to avoid regressions. It is an important part of the app.

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22 I have placed a fix for it that fixes all scenarios, and we don't need to place condition-based scrolling on the list. You can test and give your feedback on this.

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22 Any update here? Have you tested the fix?

@harshsomankar123-tech You have also faced this issue, you can also test this PR fix, and give us your feedback :)

**Comment by atharvyadav22** [comment]
> @atharvyadav22 Any update here? Have you tested the fix?
> 
> @harshsomankar123-tech You have also faced this issue, you can also test this PR fix, and give us your feedback :)

Yes actually while looking at it i found that CI failure of ZimManageViewModelTest. as we discussed that version approach I have found solution so I'll look with this too and test all the scenarios today

**Comment by harshsomankar123-tech** [comment]
@MohitMaliFtechiz Looks good from my side, just rebase needed.

**Comment by atharvyadav22** [comment]
@MohitMaliFtechiz 
Tested all the cases works and rebased too.

**Comment by MohitMaliFtechiz** [comment]
@atharvyadav22, @harshsomankar123-tech, Thank you for testing and giving your feedback on this. 

Now we are almost in the final stage of this PR. @atharvyadav22 I have seen you have added the version in [onlineLibraryState](https://github.com/kiwix/kiwix-android/pull/4707/changes#diff-2b6b4b86dcef1e11f2d82c1da11a16b9907d31acd01b5d6e2b03bede7e6e5864R591), it does not have any effect on this. Because we are already using a copy of the state when new items come, the UI will refresh automatically.

Also, now we don't have to cancel the ongoing request(https://github.com/kiwix/kiwix-android/pull/4707/changes#diff-015b5392651c6a89ea769bcfdfe76441531911f6fe5c7e052a0395c629823d83R550).

When I have made the changes i have removed these things. But after rebasing, these changes have been included, why?

We don't need these changes. So please rebase the PR properly and remove these changes.

**Comment by atharvyadav22** [comment]
thanks actually while rebase i messed up while watching cricket match ill directly force push your changes.

**Review by MohitMaliFtechiz — APPROVED** [review]
@kelson42 Now, LGTM.
