### PR TITLE
Alert Dialogue added while deleting selected Bookmarks

### LINKED ISSUE #1926: Adding Alert Dialogue while deleting selected bookmark.
**Describe the bug**
No warning/alert is shown while deleting selected bookmarks.

**Expected behavior**
A warning should be given when deleting selected bookmarks.

**Steps to reproduce the behavior:**
1. Open Bookmarks
2. Select one or more bookmarks
3. Delete them

**Screenshots**
Webp net-resizeimage (1)

**Environment**
- Version of Kiwix Android : latest develop
- Device : Pixel 4
- OS version : Android 10

### PR DESCRIPTION
**Pull request by 4shutosh**
Fixes #1926 

**Screenshots** 
Webp net-resizeimage (2)

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java [hunk 1]
```diff
@@ -96,6 +96,7 @@ public boolean onPrepareActionMode(ActionMode mode, Menu menu) {
     public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
       refreshAdapter = false;
       if (item.getItemId() == R.id.menu_context_delete) {
+        dialogShower.show(KiwixDialog.DeleteBookmarks.INSTANCE,(Function0<Unit>)() ->{
```
Comment (macgills) [inline core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java]: the indentation should be updated, format this

Comment (4shutosh) [reply core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java]: Done Sir
