### PR TITLE
Remove stale download entries on app startup

### LINKED ISSUE #4639: Downloads don't cancel/resume
**Describe the bug**
Half downloaded files doesn't cancel
**Expected behavior**
It should remove from the list or resume it.
**Steps to reproduce the behavior:**
1.  Download the zim file/files
2. Pause the files
3. close the application
4. Open it again and resume it
-->

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.14
- Device : Samsung
- OS version : 13

**Logs**

### PR DESCRIPTION
**Pull request by harshsomankar123-tech**
fixes #4639 
Summary
Cleans up invalid or inconsistent download entries during the application startup to ensure the UI accurately reflects the system's DownloadManager state.

Key Changes
1. Startup Cleanup: Implemented logic in DownloadManagerRequester.kt to identify and prune stale download records.
2. Sync Logic: Synchronized the app state with DownloadMonitorService during the initialization flow.
3. Test Stabilization: Fixed race conditions in CopyMoveFileHandlerTest by awaiting coroutines and exhausting event queues.
Screenrecording

https://github.com/user-attachments/assets/64dd3f50-34a6-481a-914f-bcef262516c1

### CODE REVIEW

**Comment by harshsomankar123-tech** [comment]
@MohitMaliFtechiz @gouri-panda 
Could you please review this when you get time? Thanks

File: core/src/main/java/org/kiwix/kiwixmobile/core/dao/DownloadRoomDao.kt [hunk 1]
```diff
@@ -48,6 +48,9 @@ abstract class DownloadRoomDao {
   @Inject
   lateinit var libkiwixBookOnDisk: LibkiwixBookOnDisk
 
+  @Query("SELECT * FROM DownloadRoomEntity")
+  abstract fun getAllDownloadsSync(): List<DownloadRoomEntity>
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/dao/DownloadRoomDao.kt]: Why are we adding this method? There is already an `getAllDownloads()` method which returns the same data.

File: core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadMonitorService.kt [hunk 2]
```diff
@@ -100,6 +101,33 @@ class DownloadMonitorService : Service() {
     setupUpdater()
     startForegroundService()
     isDownloadMonitorServiceRunning = true
+    syncRoomDbWithFetchState()
+  }
+
+  private fun syncRoomDbWithFetchState(
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadMonitorService.kt]: This will only remove the stale download when this service starts. What if there are some downloads in progress, and then a download is stale(means removes from the fetch but exists in the downloadRoomDao).

The original issue is download does not resume/cancel. It is not a proper fix for that issue.

The ideal fix should be if a download is stale:

* If the user wants to stop that download, then we should check this and remove it from the downloadRoomDao.
* If the user wants to resume the download, it should restart the download if it is stale.

**Comment by MohitMaliFtechiz** [comment]
@harshsomankar123-tech When you are working on any PR, mark them as draft, and when they are ready for review then make them ready for review and ask for the review. It will be helpful to identify which PRs are still working and which are ready for review.

**Comment by MohitMaliFtechiz** [comment]
@harshsomankar123-tech It is an important PR that needs to be fixed ASAP. Please treat this in priorty.

**Comment by harshsomankar123-tech** [comment]
A few test cases are still pending for coverage. I’ll complete them and update the PR tonight.

File: core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt [hunk 3]
```diff
@@ -43,22 +49,59 @@ class DownloadManagerRequester @Inject constructor(
   }
 
   override fun cancel(downloadId: Long) {
-    fetch.delete(downloadId.toInt())
-    startDownloadMonitorService()
+    fetch.getDownload(downloadId.toInt()) { download ->
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt]: Instead of getting the downloads. You should use the fetch inbuilt method, which returns a callback when a download does not exist in fetch. So you can directly remove the downloads from downloadDao.

Image

Something like:

```kotlin
override fun cancel(downloadId: Long) {
    fetch.delete(downloadId.toInt(), null) {
      downloadRoomDao.deleteDownloadByDownloadId(downloadId)
    }
    startDownloadMonitorService()
  }
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt [hunk 4]
```diff
@@ -43,22 +49,59 @@ class DownloadManagerRequester @Inject constructor(
...
+      }
+      startDownloadMonitorService()
+    }
   }
 
+  @Suppress("InjectDispatcher")
   override fun retryDownload(downloadId: Long) {
-    fetch.retry(downloadId.toInt())
-    startDownloadMonitorService()
+    fetch.getDownload(downloadId.toInt()) { download ->
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt]: Same for this method, there is already a built-in function for this.

Image

So the method should be

```kotlin
override fun retryDownload(downloadId: Long) {
    fetch.retry(downloadId.toInt(), null) {
      reEnqueueStaleDownload(downloadId)
    }
    startDownloadMonitorService()
  }
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt [hunk 5]
```diff
@@ -43,22 +49,59 @@ class DownloadManagerRequester @Inject constructor(
...
+      }
+      startDownloadMonitorService()
+    }
   }
 
+  @Suppress("InjectDispatcher")
   override fun pauseResumeDownload(downloadId: Long, isPause: Boolean) {
     if (isPause) {
-      fetch.resume(downloadId.toInt())
+      fetch.getDownload(downloadId.toInt()) { download ->
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt]: There is the same function for this resume as well.

Image

Something like:

```kotlin
override fun pauseResumeDownload(downloadId: Long, isPause: Boolean) {
    if (isPause) {
      fetch.resume(downloadId.toInt(), null) {
        reEnqueueStaleDownload(downloadId)
      }
    } else {
      fetch.pause(downloadId.toInt())
    }
    startDownloadMonitorService()
  }
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt [hunk 6]
```diff
@@ -43,22 +49,59 @@ class DownloadManagerRequester @Inject constructor(
...
+    }
+  }
+
+  @Suppress("InjectDispatcher")
+  private fun reEnqueueStaleDownload(downloadId: Long) {
+    downloadRoomDao.getEntityForDownloadId(downloadId)?.let { staleEntity ->
+      staleEntity.url?.let { url ->
+        downloadRoomDao.deleteDownloadByDownloadId(downloadId)
+        CoroutineScope(Dispatchers.IO).launch {
+          val request = DownloadRequest(url).toFetchRequest(kiwixDataStore)
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt]: Instead of manually doing this. You should use the `addIfDoesNotExist` function of DownloadRoomDao.

Something like:

```kotlin
 private fun reEnqueueStaleDownload(downloadId: Long) {
    downloadRoomDao.getEntityForDownloadId(downloadId)?.let { staleEntity ->
      staleEntity.url?.let { url ->
        downloadRoomDao.deleteDownloadByDownloadId(downloadId)
        CoroutineScope(Dispatchers.IO).launch {
          downloadRoomDao.addIfDoesNotExist(
            url,
            staleEntity.toBook(),
            this@DownloadManagerRequester
          )
        }
      }
    }
  }
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt [hunk 7]
```diff
@@ -34,33 +38,68 @@ import javax.inject.Inject
...
+      id = downloadId.toInt(),
+      func = null,
+      func2 = {
+        reEnqueueStaleDownload(downloadId)
+      }
+    )
     startDownloadMonitorService()
   }
 
+  @Suppress("InjectDispatcher")
```
Comment (MohitMaliFtechiz) [inline core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerRequester.kt]: This suppression is unnecessary here. Remove it.

File: core/src/test/java/org/kiwix/kiwixmobile/core/downloader/DownloadManagerRequesterTest.kt [hunk 8]
```diff
@@ -0,0 +1,229 @@
...
+
+    requester.cancel(downloadId)
+
+    verify {
+      fetch.delete(
+        id = downloadId.toInt(),
+        func = null,
+        func2 = any<Func<Error>>()
+      )
+    }
```
Comment (MohitMaliFtechiz) [inline core/src/test/java/org/kiwix/kiwixmobile/core/downloader/DownloadManagerRequesterTest.kt:82]: The test setup is good. But we should verify the calling of `startDownloadMonitorService()` to avoid future errors.

File: core/src/test/java/org/kiwix/kiwixmobile/core/downloader/DownloadManagerRequesterTest.kt [hunk 9]
```diff
@@ -0,0 +1,229 @@
...
+    context = mockk(relaxed = true)
+    every { context.getMainActivity() } returns mainActivity
+    every {
+      mainActivity.startDownloadMonitorServiceIfOngoingDownloads()
+    } just Runs
+    every { kiwixDataStore.selectedStorage } returns flowOf("/storage/emulated/0")
+    every { kiwixDataStore.wifiOnly } returns flowOf(false)
+    requester = DownloadManagerRequester(fetch, kiwixDataStore, context, downloadRoomDao)
+  }
+
```
Comment (MohitMaliFtechiz) [inline core/src/test/java/org/kiwix/kiwixmobile/core/downloader/DownloadManagerRequesterTest.kt:69]: We should test the `enqueue` method as well with both network configurations.

```kotlin
@Test
  fun `enqueue should create fetch request with WIFI only config`() = runTest {
    val downloadRequest = mockk<DownloadRequest>(relaxed = true)

    every { kiwixDataStore.wifiOnly } returns flowOf(true)

    val requestSlot = slot<Request>()
    every { fetch.enqueue(capture(requestSlot)) } returns fetch

    val id = requester.enqueue(downloadRequest)

    Assertions.assertEquals(requestSlot.captured.id.toLong(), id)
    Assertions.assertEquals(NetworkType.WIFI_ONLY, requestSlot.captured.networkType)
    Assertions.assertEquals(AUTO_RETRY_MAX_ATTEMPTS, requestSlot.captured.autoRetryMaxAttempts)
  }

  @Test
  fun `enqueue should create fetch request with all network config`() = runTest {
    val downloadRequest = mockk<DownloadRequest>(relaxed = true)

    every { kiwixDataStore.wifiOnly } returns flowOf(false)

    val requestSlot = slot<Request>()
    every { fetch.enqueue(capture(requestSlot)) } returns fetch

    val id = requester.enqueue(downloadRequest)

    Assertions.assertEquals(requestSlot.captured.id.toLong(), id)
    Assertions.assertEquals(NetworkType.ALL, requestSlot.captured.networkType)
    Assertions.assertEquals(AUTO_RETRY_MAX_ATTEMPTS, requestSlot.captured.autoRetryMaxAttempts)
  }
```

**Review by MohitMaliFtechiz — APPROVED** [review]
@harshsomankar123-tech Thank you for making the changes. @kelson42 LGTM, once CI is green, we can merge.
