### PR TITLE
#2106 Crash Report 3.3.1: java.lang.ClassNotFoundException ErrorActivity.onCreate 

### LINKED ISSUE #2106: Crash Report 3.3.1: java.lang.ClassNotFoundException ErrorActivity.onCreate
```
Caused by: java.lang.RuntimeException: 

 
  at android.os.Parcel.readSerializable (Parcel.java:2630)

 
  at android.os.Parcel.readValue (Parcel.java:2416)

 
  at android.os.Parcel.readArrayMapInternal (Parcel.java:2732)

 
  at android.os.BaseBundle.unparcel (BaseBundle.java:269)

 
  at android.os.BaseBundle.containsKey (BaseBundle.java:341)

 
  at org.kiwix.kiwixmobile.core.error.ErrorActivity.onCreate (ErrorActivity.java:99)
```

### PR DESCRIPTION
**Pull request by macgills**
Fixes #2106 

- prevent contains from throwing ClassNotFoundException

### CODE REVIEW

File: core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.java [hunk 1]
```diff
@@ -191,6 +191,14 @@ protected void onCreate(Bundle savedInstanceState) {
     restartButton.setOnClickListener(v -> onRestartClicked());
   }
 
+  private boolean safeContains(Bundle extras, String key) {
+    try {
+      return extras.containsKey(key);
+    }catch (RuntimeException ignore){
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.java:197]:
```suggestion
    } catch (RuntimeException ignore) {
```
