### PR TITLE
fix: Restored position of articles on new launches

### LINKED ISSUE #2567: Kiwix fails to restore state of previously opened article on new launches
After Kiwix is launched, it opens Library instead of Reader, since this version (3.4.1 F-Droid, LineageOS 17.1)

*Edit: It should open last read article, like in versions before.

### PR DESCRIPTION
**Pull request by s-ayush2903**
Fixes #2567

* Added required logging and rewrote the method for restoring the state of previously opened article .
* Kiwix now launches in reader always, except when intro finishes, in this case it opens library, as in this case it is guaranteed that user won't have any book opened if they're opening kiwix for the very first time; rest of the times, kiwix always starts with reader .
* Eliminated flakiness of SearchFragmentTest and made it more stable(although a rewrite to it will be best)

**Visuals** 
Watch right here: https://youtu.be/0A9Dhh6G0-w

### CODE REVIEW

**Comment by s-ayush2903** [comment]
Ah, in the last commit I removed my experimental work that I forgot to commit on another branch as I started on 2567 weeks back and earlier was trying things out locally so today while writing the real changes for 2567 my stupid experiments inadvertently crept in, apologies for that.

**Comment by abdulwd** [comment]
Why not have a switch in settings to turn on/off this behavior

**Comment by s-ayush2903** [comment]
We don't want to have it as a togglable preference, the state of article must be restored in all scenarios, although we need the user preferred behavior in case whether to launch it in reader or library. I'll keep this in a separate PR as #2567 had two issues in it: one was restoring the state of previously opened article and the second was user preference for whether to start kiwix in reader or lib.

**Comment by s-ayush2903** [comment]
Ah, the searchFragmentTest is in a very poor condition, definitely needs a rewrite.

**Comment by s-ayush2903** [comment]
Umm, I'll better change it a bit right here and will probably give it a rewrite in future(would be a cakewalk).

**Comment by s-ayush2903** [comment]
@abdulwd Can you please give it a look now, it is fine now;
* I've mentioned in the description of PR about the changes made and the updated the vid link also, as by the latest commits in this PR, kiwix opens in reader always(except for the first time, why?, I've explained this in PR desc.). 
* And regarding the _togglable feature/pref_ in _settings_ for user, I exchanged a few words with @kelson42 and the conclusion was to handle _togglable feature/pref_ in _settings_ in a new ticket as this would be an entirely new feature to implement and our very first goal is to eradicate the regression reported by the user in the linked issue(i.e., #2567)

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt [hunk 1]
```diff
@@ -250,9 +251,13 @@ class KiwixReaderFragment : CoreReaderFragment() {
     val settings = requireActivity().getSharedPreferences(SharedPreferenceUtil.PREF_KIWIX_MOBILE, 0)
     val zimFile = settings.getString(TAG_CURRENT_FILE, null)
 
-    if (zimFile != null) {
+    if (zimFile != null && File(zimFile).exists()) {
       if (zimReaderContainer.zimFile == null) {
         openZimFile(File(zimFile))
+        Log.d(
+          TAG_KIWIX,
+          "Kiwix normal start, zimFile loaded last time -> Open last used zimFile $zimFile"
```
Comment (abdulwd) [inline app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt:259]: You can just say
```suggestion
          "Opened last used zimFile: $zimFile"
```

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java [hunk 2]
```diff
@@ -1566,14 +1566,16 @@ protected void restoreTabs(@Nullable String zimArticles, @Nullable String zimPos
...
       JSONArray urls = new JSONArray(zimArticles);
       JSONArray positions = new JSONArray(zimPositions);
-      webViewList.clear();
-      currentWebViewIndex=0;
-      tabsAdapter.notifyItemRemoved(0);
-      tabsAdapter.notifyDataSetChanged();
-      for (int i = 0; i < urls.length(); i++) {
-        newTab(UpdateUtils.reformatProviderUrl(urls.getString(i)), i == currentTab)
-          .setScrollY(positions.getInt(i));
+      int i = 0;
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1569]: Use a more meaningful name than `i`.

**Review by abdulwd — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt (hunk 1 above)
Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt:259]: _Kiwix normal start_
We need this piece to differentiate between normal launches and launches via deepLinks or fileManagers, yeah the second part can be changed as per suggestion.

Comment (s-ayush2903) [reply app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt]: 3748b17

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java (hunk 2 above)
Comment (s-ayush2903) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java]: 3748b17

File: core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java [hunk 3]
```diff
@@ -1561,19 +1561,23 @@ private int safelyGetCurrentTab(SharedPreferences settings) {
...
+     unless it is explicitly mentioned in the issue you're fixing */
   protected void restoreTabs(@Nullable String zimArticles, @Nullable String zimPositions,
     int currentTab) {
     try {
       JSONArray urls = new JSONArray(zimArticles);
       JSONArray positions = new JSONArray(zimPositions);
-      webViewList.clear();
-      currentWebViewIndex=0;
-      tabsAdapter.notifyItemRemoved(0);
-      tabsAdapter.notifyDataSetChanged();
```
Comment (abdulwd) [inline core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1572]: Are you sure we don't want to notify data set changed? Won't this create some regression?

Comment (s-ayush2903) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1572]: Well, it didn't create any ill effects when I ran it. I'll stress test it and get back to you

Comment (s-ayush2903) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1572]: 100% sure no regressions :+1: You may check on your own as well

Comment (s-ayush2903) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1572]: This won't be a regression and the application without this as well runs fine. But I believe it would be a good practice to notify the tabsAdapter of the changes taking place.

Comment (abdulwd) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1572]: What about `notifyItemRemoved`, can you do `git blame` on this file and check why was it added.

Comment (s-ayush2903) [reply core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java:1572]: I need not blame it, I remember it very well, it was done as we got the user feedback via stephane that on creating newtabs, the previously existing ones are sent back to their homePage; I'll explain it here:
```kotlin
      currentWebViewIndex=0;
      tabsAdapter.notifyItemRemoved(0);
      tabsAdapter.notifyDataSetChanged();
```


These three lines do not let the user to come back on home page when he creates a new tab. And these calls on adapter saves the state of previously opened tab which wasn't the case when these calls on tabsAdapter were not present, at that time, on clicking the plus button(with multiple open) created a new tab and opened the home page of the book on each and every tab irrespective of their history/previous state. 
Sean handled this issue.

**Review by abdulwd — APPROVED** [review]
