### PR TITLE
Fix for a bug that affects custom apps missing their contents.

### LINKED ISSUE #1364: Custom app crashes when no content found
**Describe the bug**
The behaviour is similar to #1361 as in the app crashes, however this time the app looks in the right place for the contents :)

The current behaviour of the Android code seems odd, as execution in the `OnCreate()` etc. continues irrespective of whether the contents are found, or not.

This behaviour leads to the app crashing shortly after the `zimFileMissingDialog` has been shown on screen. The user has about a second to interract with that dialog before the app dies and the dialog therefore disappears.

**Expected behavior**
- The app should display the missing files dialog (and off this immediate topic, help users to work out how to get the relevant content on their device). 
- The app should not crash!

- Build a custom app e.g. `./gradlew installPhetDebug`
- Start the custom app on the device. (do not copy across a ZIM file to the device.)
- Wait for it to crash.

Environment

- Version of Kiwix Android : 2.5.x (built from master)
- Device : HTC Desire 510
- OS version : 4.4.3

**Logs**
Here's an example of the adb log for an instance of the phet app I've just built:
```
$ adb logcat -s kiwix
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
D/kiwix   (  776): onPause Save current zim file to preferences: /storage/emulated/0/Android/obb/org.kiwix.kiwixcustomphet/main.4.org.kiwix.kiwixcustomphet.obb


D/kiwix   (  923): Setting the ICU directory path to /data/data/org.kiwix.kiwixcustomphet/files/icu
D/kiwix   (  923): Initializing TextToSpeech
D/kiwix   (  923): Kiwix Custom App starting for the first time. Checking Companion ZIM: content.zim
D/kiwix   (  923): BuildConfig.ZIM_FILE_SIZE = 47353289
D/kiwix   (  923): Looking for '/storage/emulated/0/Android/obb/org.kiwix.kiwixcustomphet/main.4.org.kiwix.kiwixcustomphet.obb' with size=47353289
D/kiwix   (  923): No file '/storage/emulated/0/Android/obb/org.kiwix.kiwixcustomphet/main.4.org.kiwix.kiwixcustomphet.obb' found.
D/kiwix   (  923): actionnull
D/kiwix   (  923): TextToSpeech was initialized successfully.
D/kiwix   (  923): Retrieving: content://org.kiwix.kiwixcustomphet.zim.base/null
E/kiwix   (  923): Exception reading article null from zim file
E/kiwix   (  923): java.lang.NullPointerException
E/kiwix   (  923): 	at org.kiwix.kiwixmobile.data.ZimContentProvider$TransferThread.run(ZimContentProvider.java:479)
D/kiwix   (  923): Loaded URL: content://org.kiwix.kiwixcustomphet.zim.base/null
```

** Scope of the problem **
This bug is unlikely to affect users who correctly download the app from Google Play and get the additional file correctly installed by the Google App Installation process. It would affect users who install the app outside Google Play, etc. 

** Notes **
The custom apps seem to perform unnecessary work e.g. scanning for ZIM files (in `searchFiles()`). Perhaps it'd be a good opportunity to revise the implementation for custom apps to tidy up the behaviour of the code for custom apps?

### PR DESCRIPTION
**Pull request by julianharty**
See https://github.com/kiwix/kiwix-android/issues/1364 for details.

Fixes #1364 
Changes: 
- Extracted the code for reading content for custom apps into a separate method.
- Added logic to stop doing irrelevant steps when the content isn't there, as the app isn't going to work without the content
- Added additional ugly logic in the WebView to stop it trying to load content when there's none available in a custom app. This stops the app from crashing because various assumptions e.g. that there's a page to add to the History don't hold true when there's no content... (see logcat output added to the issue).

### CODE REVIEW

File: app/src/main/java/org/kiwix/kiwixmobile/main/KiwixWebViewClient.java [hunk 1]
```diff
@@ -91,6 +92,10 @@ public void onReceivedError(WebView view, int errorCode, String description, Str
 
   @Override
   public void onPageFinished(WebView view, String url) {
+    if (BuildConfig.IS_CUSTOM_APP && url.equals("content://" + BuildConfig.APPLICATION_ID + ".zim.base/null")) {
+      Log.e(TAG_KIWIX, "Abandoning WebView as there's a problem getting the content for this custom app.");
+      return;
+    }
     if ((url.equals("content://" + BuildConfig.APPLICATION_ID + ".zim.base/null"))
         && !BuildConfig.IS_CUSTOM_APP) {
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/main/KiwixWebViewClient.java]: we could change this if statement and inside it have different branches based on `IS_CUSTOM_APP`, DRYer

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixWebViewClient.java]: And I would rather throw an exception and just crash the app than return and continue execution flow.
That is if my assumption is correct that the zim should always be there for custom?

Comment (julianharty) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixWebViewClient.java]: @macgills From what I understand we (the app) shouldn't assume the content will always be on the device _even if the app was installed by the user from Google Play Store_. And for Kiwix apps many are installed using other approaches e.g. users sharing files (about 1/3 of the crash data in Android Vitals for Kiwix indicates the users installed the app from other sources, and that's only a subset who have their devices automatically sending usage and diagnostics to Google). Google provides example code for app developers to add to their app to download the file from Google Play, and we could simply implement this, however it then makes the app and therefore the user effectively dependent on having a working internet connection, a Google account, etc. From discussions with @mhutti1 yesterday we agree we'd like to design and implement a practical approach for the app to obtain the files (possibly where users copy the expansion file (the ZIM file) in the same way they obtained the app). In summary, the app should cope elegantly with the lack of ZIM file and inform the user without crashing. Meanwhile I'll test the app's behaviour (particularly whether it displays the message correctly and doesn't crash) if I modify this code to throw an exception.

Comment (julianharty) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixWebViewClient.java]: Re https://github.com/kiwix/kiwix-android/pull/1365#discussion_r313486523 I'm happy to improve the DRY ness of the code and will have a go at doing so. Thanks for the suggestion.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/main/KiwixWebViewClient.java]: Thanks for the info, my assumption was incorrect.

Exception unnecessary.

```
if (badUrl){
  if(isCustomApp){}
  else{}
}
```
will resolve this conversation

File: app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java [hunk 2]
```diff
@@ -369,7 +369,9 @@ public void onSwipeBottom() {
       } else {
         Log.e(TAG_KIWIX, "Problem finding the content, no more OnCreate() code");
         // What should we do here? exit? I'll investigate empirically.
-        return;
+        // It seems unpredictable behaviour if the code returns at this point as yesterday
```
Comment (macgills) [inline app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: Comments like this don't seem like a great fit for a PR. Maybe this would be best opened as a draft pr? I think this is a work in progress

Comment (mhutti1) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: This is the current behaviour so I think this is a ready pull request. It can be followed up on in the future.

Comment (julianharty) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: What I'd like to propose is to accept this 'fix' since that's what it is - it improves the external behaviour of the current codebase. And we then have a separate discussion about how to develop and support custom Android apps which is a rich topic where various people beyond the 3 of us will provide various perspectives and we can then decide how we *want* the code to behave and how much we want the custom app to be self-healing, etc.

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: This doesn't seem like a fix for a bug? The app still crashes right?
I suppose the scenario is a bit unlikely and the code is no worse off really.

Saying yesterday/today sounds very nontechnical to me but that is a very minor point

Comment (macgills) [reply app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java]: grand
